# Steam's videogames platform 👾

> Source: https://app.jedha.co/course/project-steam-ft/steam-ft

![Steam](https://full-stack-assets.s3.eu-west-3.amazonaws.com/images/Steam_2016_logo_black.png)

## Company's description 📇

**Steam** is a [video game digital distribution](https://en.wikipedia.org/wiki/Digital_distribution_of_video_games "Digital distribution of video games") service and storefront from [Valve](https://en.wikipedia.org/wiki/Valve_Corporation "Valve Corporation"). It was launched as a software client in September 2003 to provide game updates automatically for Valve's games, and expanded to distributing third-party titles in late 2005. Steam offers various features, like [digital rights management](https://en.wikipedia.org/wiki/Digital_rights_management "Digital rights management") (DRM), [game server matchmaking](https://en.wikipedia.org/wiki/Matchmaking_\(video_games\) "Matchmaking (video games)") with [Valve Anti-Cheat](https://en.wikipedia.org/wiki/Valve_Anti-Cheat "Valve Anti-Cheat") measures, [social networking](https://en.wikipedia.org/wiki/Social_networking_service "Social networking service"), and [game streaming](https://en.wikipedia.org/wiki/Video_game_live_streaming "Video game live streaming") services. Steam client's functions include game update automation, cloud storage for [game progress](https://en.wikipedia.org/wiki/Saved_game "Saved game"), and community features such as direct messaging, in-game overlay functions and a virtual [collectable](https://en.wikipedia.org/wiki/Collectable "Collectable") marketplace.

## Project 🚧

You're working for [Ubisoft](www.ubisoft.com), a French video game publisher. They'd like to release a new revolutionary videogame! They asked you conduct a global analysis of the games available on Steam's marketplace in order to better understand the videogames ecosystem and today's trends.

## Goals 🎯

The ultimate goal of this project is to understand what factors affect the popularity or sales of a video game. But your boss asked you to take advantage of this opportunity to analyze the video game market globally.

To carry out this project, you will have to adopt different levels of analysis. Your boss gave you a list of examples of questions that would be interesting:

**Analysis at the "macro" level**

-   Which publisher has released the most games on Steam?
    
-   What are the best rated games?
    
-   Are there years with more releases? Were there more or fewer game releases during the Covid, for example?
    
-   How are the prizes distributed? Are there many games with a discount?
    
-   What are the most represented languages?
    
-   Are there many games prohibited for children under 16/18?
    

**Genres analysis**

-   What are the most represented genres?
    
-   Are there any genres that have a better positive/negative review ratio?
    
-   Do some publishers have favorite genres?
    
-   What are the most lucrative genres?
    

**Platform analysis**

-   Are most games available on Windows/Mac/Linux instead?
    
-   Do certain genres tend to be preferentially available on certain platforms?
    

You're free to follow these guidelines, or to choose a different angle of analysis, as long as your analysis reveals relevant and useful information. 🤓

## Scope of this project 🖼️

You'll have to use **Databricks** and **PySpark** to conduct this EDA. Particularly, you'll have to use [Databrick's visualisation tool](https://docs.databricks.com/visualizations/index.html) to create the visualizations.

The dataset is available in our S3 bucket at the following url: `s3://full-stack-bigdata-datasets/Big_Data/Project_Steam/steam_game_output.json`.

## Helpers 🦮

To help you achieve this project, here are a few tips that should help you:

-   To adopt different levels of analysis, it might be useful to create different dataframes.
    
-   As the dataset is semi-structured with a **nested schema**, Pyspark's methods such as `getField()` and `explode()` may help you.
    
-   There are some text and date fields in this dataset: Pyspark offers utilitary functions to manipulate these types of data efficiently 💡
    
-   You can use agregate functions and `groupBy` to conduct segmented analysis.
    

## Deliverable 📬

To complete this project, you should deliver:

-   One or several notebooks including data manipulation with PySpark and data visualization with Databrick's dashboarding tool.
    
-   To make sure the jury can view all the visualizations, please use the "publish" button on Databricks notebooks to create a public url where a copy of your notebook will be available.
    
-   While using the "publish" button, Databricks may tell you that your notebook's size exceeds the maximal size allowed. If this happens, just split your notebook in several notebooks.
    
-   Please copy-paste the link(s) to your published notebooks into your Github repo such that the jury can access it easily. 😌
    

![](https://full-stack-assets.s3.eu-west-3.amazonaws.com/images/databricks_publish.png)

In [0]:
# import libraries

from pyspark.sql import SparkSession, functions as F

from pyspark.sql.functions import (
    explode, desc,  row_number, col, try_divide, year, try_to_date, count, 
    countDistinct
)

from pyspark.sql.window import Window

# import pandas as pd

In [0]:
# curl https://full-stack-bigdata-datasets.s3.amazonaws.com/Big_Data/Project_Steam/steam_game_output.json
# record a file in local wget -O steam_game_output.json https://full-stack-bigdata-datasets.s3.amazonaws.com/Big_Data/Project_Steam/steam_game_output.json

In [0]:
# from pyspark.sql import SparkSession

filepath = "s3://full-stack-bigdata-datasets/Big_Data/Project_Steam/steam_game_output.json"

df = spark.read.format('json').load(filepath)

In [0]:
# Number of elements in dataframe
print(f"Entries number : {df.count()}")

Entries number : 55691

The dataset is to big for json_normalize method.

In [0]:
type(df)

pyspark.sql.connect.dataframe.DataFrame

In [0]:
df.take(1)

[Row(data=Row(appid=10, categories=['Multi-player', 'Valve Anti-Cheat enabled', 'Online PvP', 'Shared/Split Screen PvP', 'PvP'], ccu=13990, developer='Valve', discount='0', genre='Action', header_image='https://cdn.akamai.steamstatic.com/steam/apps/10/header.jpg?t=1666823513', initialprice='999', languages='English, French, German, Italian, Spanish - Spain, Simplified Chinese, Traditional Chinese, Korean', name='Counter-Strike', negative=5199, owners='10,000,000 .. 20,000,000', platforms=Row(linux=True, mac=True, windows=True), positive=201215, price='999', publisher='Valve', release_date='2000/11/1', required_age='0', short_description="Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role.", tags=Row(1980s=266, 1990's=1191, 2.5D=None, 2D=None, 2D Fighter=None, 2D Platformer=None, 360 Video=None, 3D=None, 3D Fighter=None, 3D Platformer=None, 3D Vision=None, 4 Player Local=None, 4X=None, 6DOF=None, 8-bit Music=None, ATV=None, Abstract=None, Action=5426, Action RPG=None, Action RTS=None, Action Roguelike=None, Action-Adventure=None, Addictive=None, Adventure=None, Agriculture=None, Aliens=None, Alternate History=None, Ambient=None, America=None, Animation & Modeling=None, Anime=None, Arcade=None, Archery=None, Arena Shooter=None, Artificial Intelligence=None, Assassin=227, Asymmetric VR=None, Asynchronous Multiplayer=None, Atmospheric=None, Audio Production=None, Auto Battler=None, Automation=None, Automobile Sim=None, BMX=None, Base-Building=None, Baseball=None, Based On A Novel=None, Basketball=None, Battle Royale=None, Beat 'em up=None, Beautiful=None, Benchmark=None, Bikes=None, Blood=None, Board Game=None, Boss Rush=None, Bowling=None, Boxing=None, Building=None, Bullet Hell=None, Bullet Time=None, CRPG=None, Capitalism=None, Card Battler=None, Card Game=None, Cartoon=None, Cartoony=None, Casual=None, Cats=None, Character Action Game=None, Character Customization=None, Chess=None, Choices Matter=None, Choose Your Own Adventure=None, Cinematic=None, City Builder=None, Class-Based=None, Classic=2784, Clicker=None, Co-op=None, Co-op Campaign=None, Coding=None, Cold War=None, Collectathon=None, Colony Sim=None, Colorful=None, Combat=None, Combat Racing=None, Comedy=None, Comic Book=None, Competitive=1607, Conspiracy=None, Controller=None, Conversation=None, Cooking=None, Cozy=None, Crafting=None, Creature Collector=None, Cricket=None, Crime=None, Crowdfunded=None, Cult Classic=None, Cute=None, Cyberpunk=None, Cycling=None, Dark=None, Dark Comedy=None, Dark Fantasy=None, Dark Humor=None, Dating Sim=None, Deckbuilding=None, Demons=None, Design & Illustration=None, Destruction=None, Detective=None, Difficult=None, Dinosaurs=None, Diplomacy=None, Documentary=None, Dog=None, Dragons=None, Drama=None, Driving=None, Dungeon Crawler=None, Dungeons & Dragons=None, Dynamic Narration=None, Dystopian =None, Early Access=None, Economy=None, Education=None, Electronic=None, Electronic Music=None, Emotional=None, Epic=None, Episodic=None, Escape Room=None, Experience=None, Experimental=None, Exploration=None, FMV=None, FPS=4831, Faith=None, Family Friendly=None, Fantasy=None, Farming=None, Farming Sim=None, Fast-Paced=None, Feature Film=None, Female Protagonist=None, Fighting=None, First-Person=1707, Fishing=None, Flight=None, Football=None, Foreign=None, Free to Play=None, Funny=None, Futuristic=None, Gambling=None, Game Development=None, GameMaker=None, Games Workshop=None, Gaming=None, God Game=None, Golf=None, Gore=None, Gothic=None, Grand Strategy=None, Great Soundtrack=None, Grid-Based Movement=None, Gun Customization=None, Hack and Slash=None, Hacking=None, Hand-drawn=None, Hardware=None, Heist=None, Hentai=None, Hero Shooter=None, Hex Grid=None, Hidden Object=None, Historical=None, Hockey=None, Horror=None, Horses=None, Hunting=None, Idler=None, Illuminati=None, Immersive=None, Immersive Sim=None, Indie=None, Instrumental Music=None, Intentionally Awkward Controls=None, Interactive Fiction=None, Inventory Management=None, Investigation=None, Isometric=None, JRPG=None, Jet=None, Job Simulator=None, Jump Scare=None, Kickstarter=None, LEGO=None, LGBTQ+=None, Lemmings=None, Level Editor=None, Life Sim=None, Linear=None, Local Co-Op=None, Local Multiplayer=None, Logic=None, Loot=None, Looter Shooter=None, Lore-Rich=None, Lovecraftian=None, MMORPG=None, MOBA=None, Magic=None, Mahjong=None, Management=None, Mars=None, Martial Arts=None, Massively Multiplayer=None, Masterpiece=None, Match 3=None, Mature=None, Mechs=None, Medical Sim=None, Medieval=None, Memes=None, Metroidvania=None, Military=632, Mini Golf=None, Minigames=None, Minimalist=None, Mining=None, Mod=None, Moddable=None, Modern=None, Motocross=None, Motorbike=None, Mouse only=None, Movie=None, Multiplayer=3392, Multiple Endings=None, Music=None, Music-Based Procedural Generation=None, Musou=None, Mystery=None, Mystery Dungeon=None, Mythology=None, NSFW=None, Narration=None, Narrative=None, Nature=None, Naval=None, Naval Combat=None, Ninja=None, Noir=None, Nonlinear=None, Nostalgia=131, Nudity=None, Offroad=None, Old School=769, On-Rails Shooter=None, Online Co-Op=None, Open World=None, Open World Survival Craft=None, Otome=None, Outbreak Sim=None, Parkour=None, Parody =None, Party=None, Party Game=None, Party-Based RPG=None, Perma Death=None, Philosophical=None, Photo Editing=None, Physics=None, Pinball=None, Pirates=None, Pixel Graphics=None, Platformer=None, Point & Click=None, Political=None, Political Sim=None, Politics=None, Pool=None, Post-apocalyptic=None, Precision Platformer=None, Procedural Generation=None, Programming=None, Psychedelic=None, Psychological=None, Psychological Horror=None, Puzzle=None, Puzzle-Platformer=None, PvE=None, PvP=881, Quick-Time Events=None, RPG=None, RPGMaker=None, RTS=None, Racing=None, Real Time Tactics=None, Real-Time=None, Real-Time with Pause=None, Realistic=None, Reboot=None, Relaxing=None, Remake=None, Replay Value=None, Resource Management=None, Retro=None, Rhythm=None, Robots=None, Rock Music=None, Rogue-like=None, Rogue-lite=None, Roguelike Deckbuilder=None, Roguevania=None, Romance=None, Rome=None, Rugby=None, Runner=None, Sailing=None, Sandbox=None, Satire=None, Sci-fi=None, Science=None, Score Attack=289, Sequel=None, Sexual Content=None, Shoot 'Em Up=None, Shooter=3353, Shop Keeper=None, Short=None, Side Scroller=None, Silent Protagonist=None, Simulation=None, Singleplayer=None, Skateboarding=None, Skating=None, Skiing=None, Sniper=None, Snooker=None, Snow=None, Snowboarding=None, Soccer=None, Social Deduction=None, Software=None, Software Training=None, Sokoban=None, Solitaire=None, Souls-like=None, Soundtrack=None, Space=None, Space Sim=None, Spaceships=None, Spectacle fighter=None, Spelling=None, Split Screen=None, Sports=None, Stealth=None, Steam Machine=None, Steampunk=None, Story Rich=None, Strategy=614, Strategy RPG=None, Stylized=None, Submarine=None, Superhero=None, Supernatural=None, Surreal=None, Survival=304, Survival Horror=None, Swordplay=None, Tabletop=None, Tactical=1344, Tactical RPG=None, Tanks=None, Team-Based=1864, Tennis=None, Text-Based=None, Third Person=None, Third-Person Shooter=None, Thriller=None, Tile-Matching=None, Time Attack=None, Time Management=None, Time Manipulation=None, Time Travel=None, Top-Down=None, Top-Down Shooter=None, Touch-Friendly=None, Tower Defense=None, TrackIR=None, Trading=None, Trading Card Game=None, Traditional Roguelike=None, Trains=None, Transhumanism=None, Transportation=None, Trivia=None, Turn-Based=None, Turn-Based Combat=None, Turn-Based Strategy=None, Turn-Based Tactics=None, Tutorial=None, Twin Stick Shooter=None, Typing=None, Underground=None, Underwater=None, Unforgiving=None, Utilities=None, VR=None, VR Only=None, Vampire=None, Vehicular Combat=None, Video Production=None, Vikings=None, Villain Protagonist=None, Violent=None, Visual Novel=None, Voice Control=None, Volleyball=None, Voxel=None, Walking Simulator=None, War=None, Wargame=None, Warhammer 40K=None, Web Publishing=None, Well-Written=None, Werewolves=None, Western=None, Wholesome=None, Word Game=None, World War I=None, World War II=None, Wrestling=None, Zombies=None, e-sports=1192), type='game', website=''), id='10')]

In [0]:
df.printSchema()

root
 |-- data: struct (nullable = true)
 |    |-- appid: long (nullable = true)
 |    |-- categories: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- ccu: long (nullable = true)
 |    |-- developer: string (nullable = true)
 |    |-- discount: string (nullable = true)
 |    |-- genre: string (nullable = true)
 |    |-- header_image: string (nullable = true)
 |    |-- initialprice: string (nullable = true)
 |    |-- languages: string (nullable = true)
 |    |-- name: string (nullable = true)
 |    |-- negative: long (nullable = true)
 |    |-- owners: string (nullable = true)
 |    |-- platforms: struct (nullable = true)
 |    |    |-- linux: boolean (nullable = true)
 |    |    |-- mac: boolean (nullable = true)
 |    |    |-- windows: boolean (nullable = true)
 |    |-- positive: long (nullable = true)
 |    |-- price: string (nullable = true)
 |    |-- publisher: string (nullable = true)
 |    |-- release_date: string (nullable = true)
 |    |-- required_age: string (nullable = true)
 |    |-- short_description: string (nullable = true)
 |    |-- tags: struct (nullable = true)
 |    |    |-- 1980s: long (nullable = true)
 |    |    |-- 1990's: long (nullable = true)
 |    |    |-- 2.5D: long (nullable = true)
 |    |    |-- 2D: long (nullable = true)
 |    |    |-- 2D Fighter: long (nullable = true)
 |    |    |-- 2D Platformer: long (nullable = true)
 |    |    |-- 360 Video: long (nullable = true)
 |    |    |-- 3D: long (nullable = true)
 |    |    |-- 3D Fighter: long (nullable = true)
 |    |    |-- 3D Platformer: long (nullable = true)
 |    |    |-- 3D Vision: long (nullable = true)
 |    |    |-- 4 Player Local: long (nullable = true)
 |    |    |-- 4X: long (nullable = true)
 |    |    |-- 6DOF: long (nullable = true)
 |    |    |-- 8-bit Music: long (nullable = true)
 |    |    |-- ATV: long (nullable = true)
 |    |    |-- Abstract: long (nullable = true)
 |    |    |-- Action: long (nullable = true)
 |    |    |-- Action RPG: long (nullable = true)
 |    |    |-- Action RTS: long (nullable = true)
 |    |    |-- Action Roguelike: long (nullable = true)
 |    |    |-- Action-Adventure: long (nullable = true)
 |    |    |-- Addictive: long (nullable = true)
 |    |    |-- Adventure: long (nullable = true)
 |    |    |-- Agriculture: long (nullable = true)
 |    |    |-- Aliens: long (nullable = true)
 |    |    |-- Alternate History: long (nullable = true)
 |    |    |-- Ambient: long (nullable = true)
 |    |    |-- America: long (nullable = true)
 |    |    |-- Animation & Modeling: long (nullable = true)
 |    |    |-- Anime: long (nullable = true)
 |    |    |-- Arcade: long (nullable = true)
 |    |    |-- Archery: long (nullable = true)
 |    |    |-- Arena Shooter: long (nullable = true)
 |    |    |-- Artificial Intelligence: long (nullable = true)
 |    |    |-- Assassin: long (nullable = true)
 |    |    |-- Asymmetric VR: long (nullable = true)
 |    |    |-- Asynchronous Multiplayer: long (nullable = true)
 |    |    |-- Atmospheric: long (nullable = true)
 |    |    |-- Audio Production: long (nullable = true)
 |    |    |-- Auto Battler: long (nullable = true)
 |    |    |-- Automation: long (nullable = true)
 |    |    |-- Automobile Sim: long (nullable = true)
 |    |    |-- BMX: long (nullable = true)
 |    |    |-- Base-Building: long (nullable = true)
 |    |    |-- Baseball: long (nullable = true)
 |    |    |-- Based On A Novel: long (nullable = true)
 |    |    |-- Basketball: long (nullable = true)
 |    |    |-- Battle Royale: long (nullable = true)
 |    |    |-- Beat 'em up: long (nullable = true)
 |    |    |-- Beautiful: long (nullable = true)
 |    |    |-- Benchmark: long (nullable = true)
 |    |    |-- Bikes: long (nullable = true)
 |    |    |-- Blood: long (nullable = true)
 |    |    |-- Board Game: long (nullable = true)
 |    |    |-- Boss Rush: long (nullable = true)
 |    |    |-- Bowling: long (nullable = true)
 |    |    |-- Boxing: long (nullable = true)
 |    |    |-- Building: long (nullable = true)
 |    |    |-- Bullet Hell: long (nullable = true)
 |    |    |-- Bullet Time: long (nullable = true)
 |    |    |-- CRPG: long (nullable = true)
 |    |    |-- Capitalism: long (nullable = true)
 |    |    |-- Card Battler: long (nullable = true)
 |    |    |-- Card Game: long (nullable = true)
 |    |    |-- Cartoon: long (nullable = true)
 |    |    |-- Cartoony: long (nullable = true)
 |    |    |-- Casual: long (nullable = true)
 |    |    |-- Cats: long (nullable = true)
 |    |    |-- Character Action Game: long (nullable = true)
 |    |    |-- Character Customization: long (nullable = true)
 |    |    |-- Chess: long (nullable = true)
 |    |    |-- Choices Matter: long (nullable = true)
 |    |    |-- Choose Your Own Adventure: long (nullable = true)
 |    |    |-- Cinematic: long (nullable = true)
 |    |    |-- City Builder: long (nullable = true)
 |    |    |-- Class-Based: long (nullable = true)
 |    |    |-- Classic: long (nullable = true)
 |    |    |-- Clicker: long (nullable = true)
 |    |    |-- Co-op: long (nullable = true)
 |    |    |-- Co-op Campaign: long (nullable = true)
 |    |    |-- Coding: long (nullable = true)
 |    |    |-- Cold War: long (nullable = true)
 |    |    |-- Collectathon: long (nullable = true)
 |    |    |-- Colony Sim: long (nullable = true)
 |    |    |-- Colorful: long (nullable = true)
 |    |    |-- Combat: long (nullable = true)
 |    |    |-- Combat Racing: long (nullable = true)
 |    |    |-- Comedy: long (nullable = true)
 |    |    |-- Comic Book: long (nullable = true)
 |    |    |-- Competitive: long (nullable = true)
 |    |    |-- Conspiracy: long (nullable = true)
 |    |    |-- Controller: long (nullable = true)
 |    |    |-- Conversation: long (nullable = true)
 |    |    |-- Cooking: long (nullable = true)
 |    |    |-- Cozy: long (nullable = true)
 |    |    |-- Crafting: long (nullable = true)
 |    |    |-- Creature Collector: long (nullable = true)
 |    |    |-- Cricket: long (nullable = true)
 |    |    |-- Crime: long (nullable = true)
 |    |    |-- Crowdfunded: long (nullable = true)
 |    |    |-- Cult Classic: long (nullable = true)
 |    |    |-- Cute: long (nullable = true)
 |    |    |-- Cyberpunk: long (nullable = true)
 |    |    |-- Cycling: long (nullable = true)
 |    |    |-- Dark: long (nullable = true)
 |    |    |-- Dark Comedy: long (nullable = true)
 |    |    |-- Dark Fantasy: long (nullable = true)
 |    |    |-- Dark Humor: long (nullable = true)
 |    |    |-- Dating Sim: long (nullable = true)
 |    |    |-- Deckbuilding: long (nullable = true)
 |    |    |-- Demons: long (nullable = true)
 |    |    |-- Design & Illustration: long (nullable = true)
 |    |    |-- Destruction: long (nullable = true)
 |    |    |-- Detective: long (nullable = true)
 |    |    |-- Difficult: long (nullable = true)
 |    |    |-- Dinosaurs: long (nullable = true)
 |    |    |-- Diplomacy: long (nullable = true)
 |    |    |-- Documentary: long (nullable = true)
 |    |    |-- Dog: long (nullable = true)
 |    |    |-- Dragons: long (nullable = true)
 |    |    |-- Drama: long (nullable = true)
 |    |    |-- Driving: long (nullable = true)
 |    |    |-- Dungeon Crawler: long (nullable = true)
 |    |    |-- Dungeons & Dragons: long (nullable = true)
 |    |    |-- Dynamic Narration: long (nullable = true)
 |    |    |-- Dystopian : long (nullable = true)
 |    |    |-- Early Access: long (nullable = true)
 |    |    |-- Economy: long (nullable = true)
 |    |    |-- Education: long (nullable = true)
 |    |    |-- Electronic: long (nullable = true)
 |    |    |-- Electronic Music: long (nullable = true)
 |    |    |-- Emotional: long (nullable = true)
 |    |    |-- Epic: long (nullable = true)
 |    |    |-- Episodic: long (nullable = true)
 |    |    |-- Escape Room: long (nullable = true)
 |    |    |-- Experience: long (nullable = true)
 |    |    |-- Experimental: long (nullable = true)
 |    |    |-- Exploration: long (nullable = true)
 |    |    |-- FMV: long (nullable = true)
 |    |    |-- FPS: long (nullable = true)
 |    |    |-- Faith: long (nullable = true)
 |    |    |-- Family Friendly: long (nullable = true)
 |    |    |-- Fantasy: long (nullable = true)
 |    |    |-- Farming: long (nullable = true)
 |    |    |-- Farming Sim: long (nullable = true)
 |    |    |-- Fast-Paced: long (nullable = true)
 |    |    |-- Feature Film: long (nullable = true)
 |    |    |-- Female Protagonist: long (nullable = true)
 |    |    |-- Fighting: long (nullable = true)
 |    |    |-- First-Person: long (nullable = true)
 |    |    |-- Fishing: long (nullable = true)
 |    |    |-- Flight: long (nullable = true)
 |    |    |-- Football: long (nullable = true)
 |    |    |-- Foreign: long (nullable = true)
 |    |    |-- Free to Play: long (nullable = true)
 |    |    |-- Funny: long (nullable = true)
 |    |    |-- Futuristic: long (nullable = true)
 |    |    |-- Gambling: long (nullable = true)
 |    |    |-- Game Development: long (nullable = true)
 |    |    |-- GameMaker: long (nullable = true)
 |    |    |-- Games Workshop: long (nullable = true)
 |    |    |-- Gaming: long (nullable = true)
 |    |    |-- God Game: long (nullable = true)
 |    |    |-- Golf: long (nullable = true)
 |    |    |-- Gore: long (nullable = true)
 |    |    |-- Gothic: long (nullable = true)
 |    |    |-- Grand Strategy: long (nullable = true)
 |    |    |-- Great Soundtrack: long (nullable = true)
 |    |    |-- Grid-Based Movement: long (nullable = true)
 |    |    |-- Gun Customization: long (nullable = true)
 |    |    |-- Hack and Slash: long (nullable = true)
 |    |    |-- Hacking: long (nullable = true)
 |    |    |-- Hand-drawn: long (nullable = true)
 |    |    |-- Hardware: long (nullable = true)
 |    |    |-- Heist: long (nullable = true)
 |    |    |-- Hentai: long (nullable = true)
 |    |    |-- Hero Shooter: long (nullable = true)
 |    |    |-- Hex Grid: long (nullable = true)
 |    |    |-- Hidden Object: long (nullable = true)
 |    |    |-- Historical: long (nullable = true)
 |    |    |-- Hockey: long (nullable = true)
 |    |    |-- Horror: long (nullable = true)
 |    |    |-- Horses: long (nullable = true)
 |    |    |-- Hunting: long (nullable = true)
 |    |    |-- Idler: long (nullable = true)
 |    |    |-- Illuminati: long (nullable = true)
 |    |    |-- Immersive: long (nullable = true)
 |    |    |-- Immersive Sim: long (nullable = true)
 |    |    |-- Indie: long (nullable = true)
 |    |    |-- Instrumental Music: long (nullable = true)
 |    |    |-- Intentionally Awkward Controls: long (nullable = true)
 |    |    |-- Interactive Fiction: long (nullable = true)
 |    |    |-- Inventory Management: long (nullable = true)
 |    |    |-- Investigation: long (nullable = true)
 |    |    |-- Isometric: long (nullable = true)
 |    |    |-- JRPG: long (nullable = true)
 |    |    |-- Jet: long (nullable = true)
 |    |    |-- Job Simulator: long (nullable = true)
 |    |    |-- Jump Scare: long (nullable = true)
 |    |    |-- Kickstarter: long (nullable = true)
 |    |    |-- LEGO: long (nullable = true)
 |    |    |-- LGBTQ+: long (nullable = true)
 |    |    |-- Lemmings: long (nullable = true)
 |    |    |-- Level Editor: long (nullable = true)
 |    |    |-- Life Sim: long (nullable = true)
 |    |    |-- Linear: long (nullable = true)
 |    |    |-- Local Co-Op: long (nullable = true)
 |    |    |-- Local Multiplayer: long (nullable = true)
 |    |    |-- Logic: long (nullable = true)
 |    |    |-- Loot: long (nullable = true)
 |    |    |-- Looter Shooter: long (nullable = true)
 |    |    |-- Lore-Rich: long (nullable = true)
 |    |    |-- Lovecraftian: long (nullable = true)
 |    |    |-- MMORPG: long (nullable = true)
 |    |    |-- MOBA: long (nullable = true)
 |    |    |-- Magic: long (nullable = true)
 |    |    |-- Mahjong: long (nullable = true)
 |    |    |-- Management: long (nullable = true)
 |    |    |-- Mars: long (nullable = true)
 |    |    |-- Martial Arts: long (nullable = true)
 |    |    |-- Massively Multiplayer: long (nullable = true)
 |    |    |-- Masterpiece: long (nullable = true)
 |    |    |-- Match 3: long (nullable = true)
 |    |    |-- Mature: long (nullable = true)
 |    |    |-- Mechs: long (nullable = true)
 |    |    |-- Medical Sim: long (nullable = true)
 |    |    |-- Medieval: long (nullable = true)
 |    |    |-- Memes: long (nullable = true)
 |    |    |-- Metroidvania: long (nullable = true)
 |    |    |-- Military: long (nullable = true)
 |    |    |-- Mini Golf: long (nullable = true)
 |    |    |-- Minigames: long (nullable = true)
 |    |    |-- Minimalist: long (nullable = true)
 |    |    |-- Mining: long (nullable = true)
 |    |    |-- Mod: long (nullable = true)
 |    |    |-- Moddable: long (nullable = true)
 |    |    |-- Modern: long (nullable = true)
 |    |    |-- Motocross: long (nullable = true)
 |    |    |-- Motorbike: long (nullable = true)
 |    |    |-- Mouse only: long (nullable = true)
 |    |    |-- Movie: long (nullable = true)
 |    |    |-- Multiplayer: long (nullable = true)
 |    |    |-- Multiple Endings: long (nullable = true)
 |    |    |-- Music: long (nullable = true)
 |    |    |-- Music-Based Procedural Generation: long (nullable = true)
 |    |    |-- Musou: long (nullable = true)
 |    |    |-- Mystery: long (nullable = true)
 |    |    |-- Mystery Dungeon: long (nullable = true)
 |    |    |-- Mythology: long (nullable = true)
 |    |    |-- NSFW: long (nullable = true)
 |    |    |-- Narration: long (nullable = true)
 |    |    |-- Narrative: long (nullable = true)
 |    |    |-- Nature: long (nullable = true)
 |    |    |-- Naval: long (nullable = true)
 |    |    |-- Naval Combat: long (nullable = true)
 |    |    |-- Ninja: long (nullable = true)
 |    |    |-- Noir: long (nullable = true)
 |    |    |-- Nonlinear: long (nullable = true)
 |    |    |-- Nostalgia: long (nullable = true)
 |    |    |-- Nudity: long (nullable = true)
 |    |    |-- Offroad: long (nullable = true)
 |    |    |-- Old School: long (nullable = true)
 |    |    |-- On-Rails Shooter: long (nullable = true)
 |    |    |-- Online Co-Op: long (nullable = true)
 |    |    |-- Open World: long (nullable = true)
 |    |    |-- Open World Survival Craft: long (nullable = true)
 |    |    |-- Otome: long (nullable = true)
 |    |    |-- Outbreak Sim: long (nullable = true)
 |    |    |-- Parkour: long (nullable = true)
 |    |    |-- Parody : long (nullable = true)
 |    |    |-- Party: long (nullable = true)
 |    |    |-- Party Game: long (nullable = true)
 |    |    |-- Party-Based RPG: long (nullable = true)
 |    |    |-- Perma Death: long (nullable = true)
 |    |    |-- Philosophical: long (nullable = true)
 |    |    |-- Photo Editing: long (nullable = true)
 |    |    |-- Physics: long (nullable = true)
 |    |    |-- Pinball: long (nullable = true)
 |    |    |-- Pirates: long (nullable = true)
 |    |    |-- Pixel Graphics: long (nullable = true)
 |    |    |-- Platformer: long (nullable = true)
 |    |    |-- Point & Click: long (nullable = true)
 |    |    |-- Political: long (nullable = true)
 |    |    |-- Political Sim: long (nullable = true)
 |    |    |-- Politics: long (nullable = true)
 |    |    |-- Pool: long (nullable = true)
 |    |    |-- Post-apocalyptic: long (nullable = true)
 |    |    |-- Precision Platformer: long (nullable = true)
 |    |    |-- Procedural Generation: long (nullable = true)
 |    |    |-- Programming: long (nullable = true)
 |    |    |-- Psychedelic: long (nullable = true)
 |    |    |-- Psychological: long (nullable = true)
 |    |    |-- Psychological Horror: long (nullable = true)
 |    |    |-- Puzzle: long (nullable = true)
 |    |    |-- Puzzle-Platformer: long (nullable = true)
 |    |    |-- PvE: long (nullable = true)
 |    |    |-- PvP: long (nullable = true)
 |    |    |-- Quick-Time Events: long (nullable = true)
 |    |    |-- RPG: long (nullable = true)
 |    |    |-- RPGMaker: long (nullable = true)
 |    |    |-- RTS: long (nullable = true)
 |    |    |-- Racing: long (nullable = true)
 |    |    |-- Real Time Tactics: long (nullable = true)
 |    |    |-- Real-Time: long (nullable = true)
 |    |    |-- Real-Time with Pause: long (nullable = true)
 |    |    |-- Realistic: long (nullable = true)
 |    |    |-- Reboot: long (nullable = true)
 |    |    |-- Relaxing: long (nullable = true)
 |    |    |-- Remake: long (nullable = true)
 |    |    |-- Replay Value: long (nullable = true)
 |    |    |-- Resource Management: long (nullable = true)
 |    |    |-- Retro: long (nullable = true)
 |    |    |-- Rhythm: long (nullable = true)
 |    |    |-- Robots: long (nullable = true)
 |    |    |-- Rock Music: long (nullable = true)
 |    |    |-- Rogue-like: long (nullable = true)
 |    |    |-- Rogue-lite: long (nullable = true)
 |    |    |-- Roguelike Deckbuilder: long (nullable = true)
 |    |    |-- Roguevania: long (nullable = true)
 |    |    |-- Romance: long (nullable = true)
 |    |    |-- Rome: long (nullable = true)
 |    |    |-- Rugby: long (nullable = true)
 |    |    |-- Runner: long (nullable = true)
 |    |    |-- Sailing: long (nullable = true)
 |    |    |-- Sandbox: long (nullable = true)
 |    |    |-- Satire: long (nullable = true)
 |    |    |-- Sci-fi: long (nullable = true)
 |    |    |-- Science: long (nullable = true)
 |    |    |-- Score Attack: long (nullable = true)
 |    |    |-- Sequel: long (nullable = true)
 |    |    |-- Sexual Content: long (nullable = true)
 |    |    |-- Shoot 'Em Up: long (nullable = true)
 |    |    |-- Shooter: long (nullable = true)
 |    |    |-- Shop Keeper: long (nullable = true)
 |    |    |-- Short: long (nullable = true)
 |    |    |-- Side Scroller: long (nullable = true)
 |    |    |-- Silent Protagonist: long (nullable = true)
 |    |    |-- Simulation: long (nullable = true)
 |    |    |-- Singleplayer: long (nullable = true)
 |    |    |-- Skateboarding: long (nullable = true)
 |    |    |-- Skating: long (nullable = true)
 |    |    |-- Skiing: long (nullable = true)
 |    |    |-- Sniper: long (nullable = true)
 |    |    |-- Snooker: long (nullable = true)
 |    |    |-- Snow: long (nullable = true)
 |    |    |-- Snowboarding: long (nullable = true)
 |    |    |-- Soccer: long (nullable = true)
 |    |    |-- Social Deduction: long (nullable = true)
 |    |    |-- Software: long (nullable = true)
 |    |    |-- Software Training: long (nullable = true)
 |    |    |-- Sokoban: long (nullable = true)
 |    |    |-- Solitaire: long (nullable = true)
 |    |    |-- Souls-like: long (nullable = true)
 |    |    |-- Soundtrack: long (nullable = true)
 |    |    |-- Space: long (nullable = true)
 |    |    |-- Space Sim: long (nullable = true)
 |    |    |-- Spaceships: long (nullable = true)
 |    |    |-- Spectacle fighter: long (nullable = true)
 |    |    |-- Spelling: long (nullable = true)
 |    |    |-- Split Screen: long (nullable = true)
 |    |    |-- Sports: long (nullable = true)
 |    |    |-- Stealth: long (nullable = true)
 |    |    |-- Steam Machine: long (nullable = true)
 |    |    |-- Steampunk: long (nullable = true)
 |    |    |-- Story Rich: long (nullable = true)
 |    |    |-- Strategy: long (nullable = true)
 |    |    |-- Strategy RPG: long (nullable = true)
 |    |    |-- Stylized: long (nullable = true)
 |    |    |-- Submarine: long (nullable = true)
 |    |    |-- Superhero: long (nullable = true)
 |    |    |-- Supernatural: long (nullable = true)
 |    |    |-- Surreal: long (nullable = true)
 |    |    |-- Survival: long (nullable = true)
 |    |    |-- Survival Horror: long (nullable = true)
 |    |    |-- Swordplay: long (nullable = true)
 |    |    |-- Tabletop: long (nullable = true)
 |    |    |-- Tactical: long (nullable = true)
 |    |    |-- Tactical RPG: long (nullable = true)

We observe 23 different values : data is a only a node, categories, platforms and tags contain nested informations. Let's flatened the dataframe to range datas at same level.

In [0]:
from pyspark.sql.functions import concat_ws

flat_df = df.select("id","data.*", concat_ws(", ", "data.categories").alias("category"))
flat_df.limit(1).display()

id,appid,categories,ccu,developer,discount,genre,header_image,initialprice,languages,name,negative,owners,platforms,positive,price,publisher,release_date,required_age,short_description,tags,type,website,category
10,10,"List(Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP)",13990,Valve,0,Action,https://cdn.akamai.steamstatic.com/steam/apps/10/header.jpg?t=1666823513,999,"English, French, German, Italian, Spanish - Spain, Simplified Chinese, Traditional Chinese, Korean",Counter-Strike,5199,"10,000,000 .. 20,000,000","List(true, true, true)",201215,999,Valve,2000/11/1,0,Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role.,"List(266, 1191, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5426, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 227, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2784, null, null, null, null, null, null, null, null, null, null, null, null, 1607, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 4831, null, null, null, null, null, null, null, null, null, 1707, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 632, null, null, null, null, null, null, null, null, null, null, null, 3392, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 131, null, null, 769, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 881, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 289, null, null, null, 3353, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 614, null, null, null, null, null, null, 304, null, null, null, 1344, null, null, 1864, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1192)",game,,"Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP"

In [0]:
# from pyspark.sql import functions as F

flat_df = flat_df.withColumn(
    "platform",
    F.concat_ws(', ', *[F.when(F.col(f"platforms.{f}"), F.lit(f)) for f in ['linux', 'mac', 'windows']])
)
flat_df.limit(1).display()

id,appid,categories,ccu,developer,discount,genre,header_image,initialprice,languages,name,negative,owners,platforms,positive,price,publisher,release_date,required_age,short_description,tags,type,website,category,platform
10,10,"List(Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP)",13990,Valve,0,Action,https://cdn.akamai.steamstatic.com/steam/apps/10/header.jpg?t=1666823513,999,"English, French, German, Italian, Spanish - Spain, Simplified Chinese, Traditional Chinese, Korean",Counter-Strike,5199,"10,000,000 .. 20,000,000","List(true, true, true)",201215,999,Valve,2000/11/1,0,Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role.,"List(266, 1191, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5426, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 227, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2784, null, null, null, null, null, null, null, null, null, null, null, null, 1607, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 4831, null, null, null, null, null, null, null, null, null, 1707, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 632, null, null, null, null, null, null, null, null, null, null, null, 3392, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 131, null, null, 769, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 881, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 289, null, null, null, 3353, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 614, null, null, null, null, null, null, 304, null, null, null, 1344, null, null, 1864, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1192)",game,,"Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP","linux, mac, windows"

In [0]:
flat_df = flat_df.withColumn("tag", F.to_json(F.col("tags")))
flat_df.limit(1).display()

id,appid,categories,ccu,developer,discount,genre,header_image,initialprice,languages,name,negative,owners,platforms,positive,price,publisher,release_date,required_age,short_description,tags,type,website,category,platform,tag
10,10,"List(Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP)",13990,Valve,0,Action,https://cdn.akamai.steamstatic.com/steam/apps/10/header.jpg?t=1666823513,999,"English, French, German, Italian, Spanish - Spain, Simplified Chinese, Traditional Chinese, Korean",Counter-Strike,5199,"10,000,000 .. 20,000,000","List(true, true, true)",201215,999,Valve,2000/11/1,0,Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role.,"List(266, 1191, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5426, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 227, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2784, null, null, null, null, null, null, null, null, null, null, null, null, 1607, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 4831, null, null, null, null, null, null, null, null, null, 1707, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 632, null, null, null, null, null, null, null, null, null, null, null, 3392, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 131, null, null, 769, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 881, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 289, null, null, null, 3353, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 614, null, null, null, null, null, null, 304, null, null, null, 1344, null, null, 1864, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1192)",game,,"Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP","linux, mac, windows","{""1980s"":266,""1990's"":1191,""Action"":5426,""Assassin"":227,""Classic"":2784,""Competitive"":1607,""FPS"":4831,""First-Person"":1707,""Military"":632,""Multiplayer"":3392,""Nostalgia"":131,""Old School"":769,""PvP"":881,""Score Attack"":289,""Shooter"":3353,""Strategy"":614,""Survival"":304,""Tactical"":1344,""Team-Based"":1864,""e-sports"":1192}"

In [0]:
flat_df = flat_df.drop( "categories", "platforms", "tags")

In [0]:
flat_df.printSchema()

root
 |-- id: string (nullable = true)
 |-- appid: long (nullable = true)
 |-- ccu: long (nullable = true)
 |-- developer: string (nullable = true)
 |-- discount: string (nullable = true)
 |-- genre: string (nullable = true)
 |-- header_image: string (nullable = true)
 |-- initialprice: string (nullable = true)
 |-- languages: string (nullable = true)
 |-- name: string (nullable = true)
 |-- negative: long (nullable = true)
 |-- owners: string (nullable = true)
 |-- positive: long (nullable = true)
 |-- price: string (nullable = true)
 |-- publisher: string (nullable = true)
 |-- release_date: string (nullable = true)
 |-- required_age: string (nullable = true)
 |-- short_description: string (nullable = true)
 |-- type: string (nullable = true)
 |-- website: string (nullable = true)
 |-- category: string (nullable = false)
 |-- platform: string (nullable = false)
 |-- tag: string (nullable = true)

In [0]:
# flat_df.write.csv("df.csv", header=True)

Export a csv with the .write method requires missing write right on working directory in databricks free edition. So, let's use pandas method .tocsv()

In [0]:
# import pandas as pd

# flat_df.toPandas().to_csv("df.csv", index=False)

# Explorary dataset analysis

## 1. Explore dataset

In [0]:
len(flat_df.columns)

23

In [0]:
flat_df.count()

55691

The dataframe has 23 columns and 55691 rows.

Now, let's query on the dataframe. Spark lets us run classic SQL queries on your tables, however, using classic SQL in Spark requires you to load the data in memory before running any query. We will use the .createOrReplaceTempView Spark DataFrame method in order to load the data in memory under a certain table name, we will then be able to run SQL queries on it.

In [0]:
flat_df.createOrReplaceTempView('temp_table') # Creates a temporary view table in memory called temp_table
result = spark.sql("select * from temp_table limit 1")
result.show()

+---+-----+-----+---------+--------+------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+
| id|appid|  ccu|developer|discount| genre|        header_image|initialprice|           languages|          name|negative|              owners|positive|price|publisher|release_date|required_age|   short_description|type|website|            category|           platform|                 tag|
+---+-----+-----+---------+--------+------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+
| 10|   10|13990|    Valve|       0|Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|    Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|
+---+-----+-----+---------+--------+------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+

The .sql method lets you write queries in SQL while benefiting from the distributed computing advantages of Spark.

In [0]:
result = spark.sql("SELECT * FROM temp_table LIMIT 1") # filters elements from temp_table 
# show everything
result.show()

+---+-----+-----+---------+--------+------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+
| id|appid|  ccu|developer|discount| genre|        header_image|initialprice|           languages|          name|negative|              owners|positive|price|publisher|release_date|required_age|   short_description|type|website|            category|           platform|                 tag|
+---+-----+-----+---------+--------+------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+
| 10|   10|13990|    Valve|       0|Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|    Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|
+---+-----+-----+---------+--------+------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+

We observe 
- ccu nombre de joueurs qui jouaient simulatanément au moment où le dataset a été construit
- discount en pourcentage
- prix stocké en centimes de dollars
- owners indique un intervalle pour évaluer le nombre d'acheteurs
- categories la liste varie selon le jeu. Elles permettent aux acheteurs de classer les jeux et fonctionnent comme les étagères d'une bibliothèque.
- duplicated rows ?

some problems :
- unused spaces : sort columns to verify wether it's a display problem or requests problem 
- different spelling : lowercase string columns
- special alphabetic characters on string columns developers '---', "flyingcubicle, - ", "((no-end-parens studio", "revday studio", "+7 software" , "+mpact games, llc."  
- empty entries : '' on website and platform -> verify other columns
- unused columns : id and appid are identifyers, we use name and can delete them, website, header_image 
- des colonnes numériques au format string -> convertir price, initialprice, discount, required_age au format long
- release_date string for datetime

We must verify with steam team before treat these data.
- special alphabetic characters : "," is a separator that we can use to count entries on developers, genre, languages. 
Are " ", None, ., CD PROJEKT RED, [2.21] real publishers and '---', "flyingcubicle, - ", "((no-end-parens studio", "revday studio", "+7 software" , "+mpact games, llc." real developers ?
Are "(none)", " ", "-" real publishers ?
- asiatic characters. We need information even if the langage changes.

Let's sample and observe values on selected columns.

In [0]:
flat_df.select('developer', 'publisher', 'owners', 'ccu', 'website', 'header_image').sample(fraction=0.0001).distinct().show(truncate=False)

+--------------+--------------+-----------+---+-------+-----------------------------------------------------------------------------+
|developer     |publisher     |owners     |ccu|website|header_image                                                                 |
+--------------+--------------+-----------+---+-------+-----------------------------------------------------------------------------+
|Reforged Group|Reforged Group|0 .. 20,000|0  |       |https://cdn.akamai.steamstatic.com/steam/apps/1777080/header.jpg?t=1657901080|
+--------------+--------------+-----------+---+-------+-----------------------------------------------------------------------------+

In [0]:
spark.sql("select * from temp_table limit 5").show()

+-------+-------+-----+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------------+--------+--------------------+--------+-----+--------------------+------------+------------+-------------------------------------+----+--------------------+--------------------+-------------------+--------------------+
|     id|  appid|  ccu|           developer|discount|               genre|        header_image|initialprice|           languages|                name|negative|              owners|positive|price|           publisher|release_date|required_age|                    short_description|type|             website|            category|           platform|                 tag|
+-------+-------+-----+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------------+--------+--------------------+--------+-----+--------------------+------------+------------+-------------------------------------+----+--------------------+--------------------+-------------------+--------------------+
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|      Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|                 Play the world's ...|game|                    |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|
|1000000|1000000|    0|IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|           ASCENXION|       5|         0 .. 20,000|      27|  999|PsychoFlux Entert...|  2021/05/14|           0|                 ASCENXION is a 2D...|game|                    |Single-player, Pa...|            windows|{"2D":159,"Abstra...|
|1000010|1000010|   99|        NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Simplified Chines...|         Crown Trick|     646|  200,000 .. 500,000|    4032|  599|Team17, NEXT Studios|  2020/10/16|           0|                 Enter a labyrinth...|game|                    |Single-player, Pa...|            windows|{"2D":205,"Action...|
|1000030|1000030|   76| Vertigo Gaming Inc.|       0|Action, Indie, Si...|https://cdn.akama...|        1999|             English|Cook, Serve, Deli...|     115|  100,000 .. 200,000|    1575| 1999| Vertigo Gaming Inc.|  2020/10/14|           0|                 Cook, serve and m...|game|http://www.cookse...|Multi-player, Sin...|       mac, windows|{"2D":187,"Action...|
|1000040|1000040|    0|       DoubleC Games|       0|Action, Casual, I...|https://cdn.akama...|         199|  Simplified Chinese|            细胞战争|       1|         0 .. 20,000|       0|  199|       DoubleC Games|  2019/03/30|           0|这是一款打击感十足的细胞主题游戏！...|game|                    |       Single-player|            windows|{"Action":22,"Cas...|
+-------+-------+-----+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------------+--------+--------------------+--------+-----+--------------------+------------+------------+-------------------------------------+----+--------------------+--------------------+-------------------+--------------------+

In [0]:
result = spark.sql("select distinct type from temp_table")
result.show()

+--------+
|    type|
+--------+
|hardware|
|    game|
+--------+

In [0]:
result = spark.sql("select * from temp_table where type = 'hardware'")
result.show(truncate=False)

+------+------+---+---------+--------+-----+----------------------------------------------------------------------------+------------+---------+----------+--------+--------------------+--------+-----+-----------+------------+------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+-----------------------------------------+---------------------------------------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|id    |appid |ccu|developer|discount|genre|header_image                                                                |initialprice|languages|name      |negative|owners              |positive|price|publisher  |release_date|required_age|short_description                                                                                                                                                                                                                                                                |type    |website                                  |category                                     |platform           |tag                                                                                                                                                                                                                    |
+------+------+---+---------+--------+-----+----------------------------------------------------------------------------+------------+---------+----------+--------+--------------------+--------+-----+-----------+------------+------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+-----------------------------------------+---------------------------------------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|353380|353380|0  |         |0       |     |https://cdn.akamai.steamstatic.com/steam/apps/353380/header.jpg?t=1617990330|0           |         |Steam Link|1771    |500,000 .. 1,000,000|5803    |0    |Anima Locus|2015/11/10  |0           |Extend your Steam gaming experience to your mobile device, TV, or another PC - all you need is a local network or internet connection. In addition, the Steam Link app now supports Remote Play Together. Now you can join games hosted on a friend’s PC just by clicking a link.|hardware|https://store.steampowered.com/remoteplay|Full controller support, Remote Play Together|linux, mac, windows|{"Comedy":10,"Competitive":8,"Epic":5,"Great Soundtrack":11,"Hentai":6,"Local Multiplayer":15,"Post-apocalyptic":6,"PvP":10,"RPG":16,"Shooter":23,"Software":39,"Steam Machine":440,"Survival":11,"Survival Horror":17}|
+------+------+---+---------+--------+-----+----------------------------------------------------------------------------+------------+---------+----------+--------+--------------------+--------+-----+-----------+------------+------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+-----------------------------------------+---------------------------------------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Steam link est un outil édité par Anima Locus qui permet d'accéder à un jeu par lien sur le téléphone, une tablette, un autre PC et même d'accéder à un jeu hébergé sur le pc d'un ami. Ce n'est pas un jeu en soi. Il convient de supprimer la colonne type.

In [0]:
result = spark.sql("select distinct name from temp_table where name like'Counter-Strike%'")
result.show(truncate=False)

+--------------------------------+
|name                            |
+--------------------------------+
|Counter-Strike Nexon: Studio    |
|Counter-Strike: Global Offensive|
|Counter-Strike: Source          |
|Counter-Strike: Condition Zero  |
|Counter-Strike                  |
+--------------------------------+

Une entrée ne correspond pas forcément à un nom de jeu. Ici, les informations diffèrent totalement pour le même jeu.

In [0]:
result = spark.sql("select count (distinct name) as games_nb from temp_table")
result.show(truncate=False)

+--------+
|games_nb|
+--------+
|55430   |
+--------+

En réalité, le fichier référence 55430 nom de jeux.

In [0]:
result = spark.sql("select * from temp_table where name like'Alone'")
result.show(truncate=False)

+-------+-------+---+--------------------+--------+-------------------------------------------+-----------------------------------------------------------------------------+------------+---------+-----+--------+-----------+--------+-----+--------------------+------------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+-------+-------------------------------------------------------------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|id     |appid  |ccu|developer           |discount|genre                                      |header_image                                                                 |initialprice|languages|name |negative|owners     |positive|price|publisher           |release_date|required_age|short_description                                                                                                                                                                                                                                                                         |type|website|category                                                     |platform|tag                                                                                                                                                                                                                                                                                        |
+-------+-------+---+--------------------+--------+-------------------------------------------+-----------------------------------------------------------------------------+------------+---------+-----+--------+-----------+--------+-----+--------------------+------------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+-------+-------------------------------------------------------------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|1640090|1640090|0  |1 Flame Studio      |0       |Action, Adventure, Casual                  |https://cdn.akamai.steamstatic.com/steam/apps/1640090/header.jpg?t=1633714853|399         |English  |Alone|1       |0 .. 20,000|0       |399  |1 Flame Studio      |2021/07/29  |0           |An epic, unforgiving platformer in which you navigate hellish challenges to reach the goal in the fastest time possible. Dodge hazards, avoid traps, and conquer obstacles with precision and speed to set your records!                                                                  |game|       |Single-player, Steam Achievements, Full controller support   |windows |{"2D":36,"2D Platformer":46,"Action":48,"Adventure":37,"Casual":46,"Controller":30,"Dark":16,"Fantasy":20,"Minimalist":25,"Platformer":39,"Precision Platformer":52,"PvE":42,"Singleplayer":14,"Stylized":23}                                                                              |
|1789460|1789460|0  |Achilles Game Studio|0       |Indie, Early Access                        |https://cdn.akamai.steamstatic.com/steam/apps/1789460/header.jpg?t=1636628477|1999        |English  |Alone|1       |0 .. 20,000|0       |1999 |Laurentino Maldonado|2021/11/11  |0           |An open world survival crafting game based more on realism. Craft, hunt, farm, build, and more to come.                                                                                                                                                                                   |game|       |Single-player                                                |windows |{"3D":39,"Base-Building":21,"Casual":50,"Crafting":23,"Early Access":22,"Exploration":41,"Indie":21,"Nature":27,"Open World":19,"PvE":17,"Realistic":35,"Sandbox":44,"Singleplayer":15,"Survival":25,"Third Person":29}                                                                    |
|1975890|1975890|0  |Epic Llama Games    |0       |Adventure, Casual, Indie, RPG, Early Access|https://cdn.akamai.steamstatic.com/steam/apps/1975890/header.jpg?t=1667746883|1099        |English  |Alone|0       |0 .. 20,000|3       |1099 |Epic Llama Games    |2022/07/22  |0           |An isometric RPG with citybuilder elements. Collect resources and craft items and weapons. Build a settlement on your island. Hunt in the darkest forests, or slay the undead in the cursed crypts. Explore, claim and restore the blighted islands and become a Jarl worthy of the sagas.|game|       |Single-player, Steam Achievements                            |windows |{"3D":83,"Action RPG":87,"Adventure":89,"Base-Building":77,"Building":73,"CRPG":104,"Casual":46,"Character Customization":85,"City Builder":95,"Crafting":71,"Early Access":65,"Exploration":98,"Fantasy":75,"Indie":121,"Isometric":80,"PvE":89,"RPG":110,"Relaxing":79,"Singleplayer":66}|
|837930 |837930 |0  |Killed Pixel Games  |0       |Adventure, Indie, Simulation, Strategy     |https://cdn.akamai.steamstatic.com/steam/apps/837930/header.jpg?t=1634197114 |99          |English  |Alone|5       |0 .. 20,000|18      |99   |Killed Pixel Games  |2018/05/1   |0           |Alone is a Pixelated Survival Game set in the extremely cold Siberian Wilderness in 1983, Soviet Union.                                                                                                                                                                                   |game|       |Single-player, Steam Achievements                            |windows |{"Adventure":20,"Indie":22,"Pixel Graphics":7,"Simulation":21,"Strategy":20,"Survival":5}                                                                                                                                                                                                  |
|871870 |871870 |0  |Avasion             |0       |Adventure, Casual, Indie                   |https://cdn.akamai.steamstatic.com/steam/apps/871870/header.jpg?t=1529593260 |99          |English  |Alone|13      |0 .. 20,000|23      |99   |Avasion             |2018/06/21  |0           |Alone is a 3D Puzzle Sidescroller with heavy focus on environment puzzles. You wake up alone in your camp and find your friends gone. Set off into the seemingly nice forest to discover its secrets, but be careful not to lose yourself on the way.                                     |game|       |Single-player, Partial Controller Support, Steam Achievements|windows |{"Adventure":21,"Casual":21,"Indie":21}                                                                                                                                                                                                                                                    |
+-------+-------+---+--------------------+--------+-------------------------------------------+-----------------------------------------------------------------------------+------------+---------+-----+--------+-----------+--------+-----+--------------------+------------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+-------+-------------------------------------------------------------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Mais en détail le jeu Alone qui est référencé 5 fois contient des données description, developer, publisher, genre, price, initialprice, positive, negative, release_date, category, tag totalement différentes. Je ne peux pas garantir que ces jeux soient identiques. Il manque les informations concernant la marque, les brevets éventuels, voire les registres.

In [0]:
result = spark.sql("select count(appid) as appid_nb, name from temp_table group by name order by appid_nb desc limit 5")
result.show(truncate=False)

+--------+------+
|appid_nb|name  |
+--------+------+
|5       |Alone |
|4       |Bounce|
|4       |Escape|
|4       |Dodge |
|4       |Lost  |
+--------+------+

In [0]:
result = spark.sql("select count(appid) as appid_nb from temp_table where appid != id ")
result.show(truncate=False)

+--------+
|appid_nb|
+--------+
|0       |
+--------+

appid et id ont des valeurs identiques mais le format diffère. 
Arbitrage : conserver appid car il est au format long, adapté pour stocker des valeurs numériques.

In [0]:
from pyspark.sql.functions import col

string_cols = [field.name for field in flat_df.schema.fields if field.dataType.simpleString() == 'string']

for c in string_cols:
    count = flat_df.filter(col(c) == '').count()
    if count > 0:
        print(f"{c}: {count}")

developer: 127
genre: 161
languages: 11
publisher: 132
release_date: 99
short_description: 37
website: 25217
category: 970

In [0]:
result = spark.sql("select * from temp_table where release_date = ''")
result.show()

+-------+-------+---+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------------+--------+--------------------+--------+-----+--------------------+------------+------------+--------------------+----+--------------------+--------------------+-------------------+--------------------+
|     id|  appid|ccu|           developer|discount|               genre|        header_image|initialprice|           languages|                name|negative|              owners|positive|price|           publisher|release_date|required_age|   short_description|type|             website|            category|           platform|                 tag|
+-------+-------+---+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------------+--------+--------------------+--------+-----+--------------------+------------+------------+--------------------+----+--------------------+--------------------+-------------------+--------------------+
| 102500| 102500| 51|Big Huge Games, 3...|       0|         Action, RPG|https://cdn.akama...|           0|English, French, ...|Kingdoms of Amalu...|    1492|2,000,000 .. 5,00...|   11184|    0|38 Studios, Elect...|            |          15|The minds of New ...|game|http://www.ea.com...|Single-player, Pa...|            windows|{"Action":426,"Ac...|
|1075950|1075950|  0|V1 Interactive, Inc.|       0|    Action, Strategy|https://cdn.akama...|           0|             English|Disintegration Te...|     342|         0 .. 20,000|    1144|    0|    Private Division|            |           0|Pilot a heavily a...|game|https://www.disin...|Multi-player, Sin...|            windows|{"Action":78,"FPS...|
|1173590|1173590|  8|StarChart-Interac...|       0|Free to Play, Ind...|https://cdn.akama...|           0|             English|Dominus Galaxia: ...|      31|         0 .. 20,000|     162|    0|StarChart-Interac...|            |           0|Dominus Galaxia i...|game|https://dominusga...|Multi-player, Sin...|linux, mac, windows|{"4X":8,"Free to ...|
|1269260|1269260|  5|               Valve|       0|            Strategy|https://cdn.akama...|           0|English, French, ...|    Artifact Foundry|     306|         0 .. 20,000|     379|    0|               Valve|            |           0|Artifact Foundry,...|game|                    |Multi-player, Sin...|linux, mac, windows|{"Board Game":41,...|
|1321650|1321650|  0|Bobby Schwind, Ma...|       0|Action, Adventure...|https://cdn.akama...|           0|             English|Rocket Ghost Aidan 2|       0|         0 .. 20,000|      14|    0|       Bobby Schwind|            |           0|Scared to play ca...|game|https://gamesbybo...|Single-player, St...|            windows|{"2D":25,"2D Plat...|
|1402480|1402480|  2|    24 Entertainment|       0|   Action, Adventure|https://cdn.akama...|           0|English, Japanese...|NARAKA: BLADEPOIN...|      22|         0 .. 20,000|     100|    0|    24 Entertainment|            |           0|NARAKA: BLADEPOIN...|game|                    |Multi-player, Onl...|            windows|{"Action":59,"Adv...|
|  15540|  15540|  0| Dejobaan Games, LLC|       0|Action, Indie, Ea...|https://cdn.akama...|           0|             English|1... 2... 3... KI...|     383|   50,000 .. 100,000|     151|    0| Dejobaan Games, LLC|            |           0|Battle your favor...|game|http://dejobaan.c...|Single-player, St...|            windows|{"Action":40,"Ear...|
| 201830| 201830|  2|      Telltale Games|       0|           Adventure|https://cdn.akama...|           0|English, French, ...|Jurassic Park: Th...|     638|  200,000 .. 500,000|    1313|    0|      Telltale Games|            |           0|Experience a bran...|game|http://www.tellta...|Single-player, Pa...|       mac, windows|{"Action":38,"Adv...|
| 202170| 202170| 39|  United Front Games|       0|   Action, Adventure|https://cdn.akama...|           0|English, French, ...|       Sleeping Dogs|     922|2,000,000 .. 5,00...|   15808|    0|         Square Enix|            |          15|As Wei Shen, an u...|game|http://sleepingdo...|Single-player, St...|            windows|{"Action":849,"Ad...|
| 203680| 203680|  6|         Codemasters|       0|              Racing|https://cdn.akama...|           0|English, German, ...|       F1 RACE STARS|     395|500,000 .. 1,000,000|    1439|    0|Codemasters, Elec...|            |           0|F1 RACE STARS™ is...|game|http://www.f1race...|Multi-player, Sin...|            windows|{"3D Vision":24,"...|
| 203810| 203810|  0|The Chinese Room,...|       0|Adventure, Casual...|https://cdn.akama...|         999|             English|         Dear Esther|    1494|  200,000 .. 500,000|    4638|  999|         Secret Mode|            |           0|Begin a journey t...|game|http://www.dear-e...|Single-player, Pa...|       mac, windows|{"Adventure":248,...|
| 204960| 204960|  0|      Golgoth Studio|       0|       Casual, Indie|https://cdn.akama...|           0|English, German, ...|      Magical Drop V|     204|    20,000 .. 50,000|     223|    0|UTV Ignition Ente...|            |           0|Magical Drop V is...|game|http://www.magica...|Multi-player, Sin...|            windows|{"Anime":30,"Arca...|
| 205250| 205250|  0|                  UL|       0|           Utilities|https://cdn.akama...|           0|English, French, ...|      3DMark Vantage|       2|         0 .. 20,000|      18|    0|                  UL|            |           0|Test your PC's pe...|game|https://benchmark...|  Steam Leaderboards|            windows|{"Benchmark":16,"...|
| 208500| 208500| 68|         Codemasters|       0|Racing, Simulatio...|https://cdn.akama...|           0|English, German, ...|             F1 2012|     276|  200,000 .. 500,000|    3574|    0|Codemasters, Elec...|            |           0|The next game in ...|game|http://www.formul...|Multi-player, Sin...|            windows|{"Automobile Sim"...|
| 209270| 209270|  0| Robot Entertainment|       0|     Indie, Strategy|https://cdn.akama...|           0|English, German, ...|        Hero Academy|     235|  100,000 .. 200,000|     510|    0| Robot Entertainment|            |           0|Test your skills ...|game|http://www.robote...|Multi-player, Sin...|linux, mac, windows|{"Asynchronous Mu...|
| 209520| 209520|  0|     The Binary Mill|       0|Casual, Indie, Ra...|https://cdn.akama...|           0|             English|Mini Motor Racing...|     236|   50,000 .. 100,000|     437|    0|     The Binary Mill|            |           0|Little Cars, BIG ...|game|http://www.thebin...|Single-player, St...|            windows|{"Arcade":11,"Cas...|
| 210350| 210350|  2|                    |       0|                    |https://cdn.akama...|           0|English, Not supp...|        Max Payne RU|      40|    20,000 .. 50,000|     321|    0|      Rockstar Games|            |           0|                    |game|                    |                    |            windows|{"Action":11,"Atm...|
| 210550| 210550|  1|Rovio Entertainme...|       0|              Casual|https://cdn.akama...|           0|             English|   Angry Birds Space|      50|    20,000 .. 50,000|     467|    0|Rovio Entertainme...|            |           0|The #1 mobile gam...|game|http://www.angryb...|Single-player, St...|            windows|{"2D":15,"Action"...|
| 214560| 214560| 10|  Klei Entertainment|       0|Action, Adventure...|https://cdn.akama...|         499|English, German, ...|   Mark of the Ninja|     469|1,000,000 .. 2,00...|   15248|  499|   Microsoft Studios|            |           0|In Mark of the Ni...|game|http://www.markof...|Single-player, St...|linux, mac, windows|{"2D":532,"Action...|
| 215450| 215450|  0|              Alkemi|       0|Action, Casual, I...|https://cdn.akama...|         799|English, German, ...|        Transcripted|       3|         0 .. 20,000|      50|  799|              Alkemi|            |           0|After 3 years, Tr...|game|                    |Single-player, Pa...|       mac, windows|{"Action":20,"Cas...|
+-------+-------+---+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------------+--------+--------------------+--------+-----+--------------------+------------+------------+--------------------+----+--------------------+--------------------+-------------------+--------------------+
only showing top 20 rows

In [0]:
from pyspark.sql.functions import col, sum as spark_sum

all_cols = flat_df.columns
string_cols = [f.name for f in flat_df.schema.fields if f.dataType.simpleString() == 'string']

flat_df.select([spark_sum((col(c).isNull() | ((col(c) == '') if c in string_cols else False)).cast('int')).alias(c) for c in all_cols]).show()

+---+-----+---+---------+--------+-----+------------+------------+---------+----+--------+------+--------+-----+---------+------------+------------+-----------------+----+-------+--------+--------+---+
| id|appid|ccu|developer|discount|genre|header_image|initialprice|languages|name|negative|owners|positive|price|publisher|release_date|required_age|short_description|type|website|category|platform|tag|
+---+-----+---+---------+--------+-----+------------+------------+---------+----+--------+------+--------+-----+---------+------------+------------+-----------------+----+-------+--------+--------+---+
|  0|    0|  0|      127|       0|  161|           0|           0|       11|   0|       0|     0|       0|    0|      132|          99|           0|               37|   0|  25217|     970|       0|  0|
+---+-----+---+---------+--------+-----+------------+------------+---------+----+--------+------+--------+-----+---------+------------+------------+-----------------+----+-------+--------+--------+---+

In pyspark, missing values are empty values.

There are 55691 rows. Website misses on one half rows. Other missing values should be converted.

In [0]:
flat_df.count() == flat_df.dropDuplicates().count()

True

There is no duplicated rows.

In [0]:
(flat_df.count() - flat_df.dropDuplicates().count())

0

There is no duplicated value.

## 2. Clean data

Let's record clean_data under a new dataframe and create a new temp view.

In [0]:
clean_df = flat_df
clean_df.createOrReplaceTempView('table')

In [0]:
result = clean_df \
    .filter(clean_df.name == 'Alone')
result.show(truncate=False)

+-------+-------+---+--------------------+--------+-------------------------------------------+-----------------------------------------------------------------------------+------------+---------+-----+--------+-----------+--------+-----+--------------------+------------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+-------+-------------------------------------------------------------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|id     |appid  |ccu|developer           |discount|genre                                      |header_image                                                                 |initialprice|languages|name |negative|owners     |positive|price|publisher           |release_date|required_age|short_description                                                                                                                                                                                                                                                                         |type|website|category                                                     |platform|tag                                                                                                                                                                                                                                                                                        |
+-------+-------+---+--------------------+--------+-------------------------------------------+-----------------------------------------------------------------------------+------------+---------+-----+--------+-----------+--------+-----+--------------------+------------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+-------+-------------------------------------------------------------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|1640090|1640090|0  |1 Flame Studio      |0       |Action, Adventure, Casual                  |https://cdn.akamai.steamstatic.com/steam/apps/1640090/header.jpg?t=1633714853|399         |English  |Alone|1       |0 .. 20,000|0       |399  |1 Flame Studio      |2021/07/29  |0           |An epic, unforgiving platformer in which you navigate hellish challenges to reach the goal in the fastest time possible. Dodge hazards, avoid traps, and conquer obstacles with precision and speed to set your records!                                                                  |game|       |Single-player, Steam Achievements, Full controller support   |windows |{"2D":36,"2D Platformer":46,"Action":48,"Adventure":37,"Casual":46,"Controller":30,"Dark":16,"Fantasy":20,"Minimalist":25,"Platformer":39,"Precision Platformer":52,"PvE":42,"Singleplayer":14,"Stylized":23}                                                                              |
|1789460|1789460|0  |Achilles Game Studio|0       |Indie, Early Access                        |https://cdn.akamai.steamstatic.com/steam/apps/1789460/header.jpg?t=1636628477|1999        |English  |Alone|1       |0 .. 20,000|0       |1999 |Laurentino Maldonado|2021/11/11  |0           |An open world survival crafting game based more on realism. Craft, hunt, farm, build, and more to come.                                                                                                                                                                                   |game|       |Single-player                                                |windows |{"3D":39,"Base-Building":21,"Casual":50,"Crafting":23,"Early Access":22,"Exploration":41,"Indie":21,"Nature":27,"Open World":19,"PvE":17,"Realistic":35,"Sandbox":44,"Singleplayer":15,"Survival":25,"Third Person":29}                                                                    |
|1975890|1975890|0  |Epic Llama Games    |0       |Adventure, Casual, Indie, RPG, Early Access|https://cdn.akamai.steamstatic.com/steam/apps/1975890/header.jpg?t=1667746883|1099        |English  |Alone|0       |0 .. 20,000|3       |1099 |Epic Llama Games    |2022/07/22  |0           |An isometric RPG with citybuilder elements. Collect resources and craft items and weapons. Build a settlement on your island. Hunt in the darkest forests, or slay the undead in the cursed crypts. Explore, claim and restore the blighted islands and become a Jarl worthy of the sagas.|game|       |Single-player, Steam Achievements                            |windows |{"3D":83,"Action RPG":87,"Adventure":89,"Base-Building":77,"Building":73,"CRPG":104,"Casual":46,"Character Customization":85,"City Builder":95,"Crafting":71,"Early Access":65,"Exploration":98,"Fantasy":75,"Indie":121,"Isometric":80,"PvE":89,"RPG":110,"Relaxing":79,"Singleplayer":66}|
|837930 |837930 |0  |Killed Pixel Games  |0       |Adventure, Indie, Simulation, Strategy     |https://cdn.akamai.steamstatic.com/steam/apps/837930/header.jpg?t=1634197114 |99          |English  |Alone|5       |0 .. 20,000|18      |99   |Killed Pixel Games  |2018/05/1   |0           |Alone is a Pixelated Survival Game set in the extremely cold Siberian Wilderness in 1983, Soviet Union.                                                                                                                                                                                   |game|       |Single-player, Steam Achievements                            |windows |{"Adventure":20,"Indie":22,"Pixel Graphics":7,"Simulation":21,"Strategy":20,"Survival":5}                                                                                                                                                                                                  |
|871870 |871870 |0  |Avasion             |0       |Adventure, Casual, Indie                   |https://cdn.akamai.steamstatic.com/steam/apps/871870/header.jpg?t=1529593260 |99          |English  |Alone|13      |0 .. 20,000|23      |99   |Avasion             |2018/06/21  |0           |Alone is a 3D Puzzle Sidescroller with heavy focus on environment puzzles. You wake up alone in your camp and find your friends gone. Set off into the seemingly nice forest to discover its secrets, but be careful not to lose yourself on the way.                                     |game|       |Single-player, Partial Controller Support, Steam Achievements|windows |{"Adventure":21,"Casual":21,"Indie":21}                                                                                                                                                                                                                                                    |
+-------+-------+---+--------------------+--------+-------------------------------------------+-----------------------------------------------------------------------------+------------+---------+-----+--------+-----------+--------+-----+--------------------+------------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+-------+-------------------------------------------------------------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### positive / negative / ccu

positive, negative et ccu sont des chiffres. Ils seront convertis.

### price

### required_age

In [0]:
result = clean_df \
    .select('required_age') \
    .distinct() \
    .orderBy('required_age')
result.display()

required_age
0
10
12
13
14
15
16
17
18
180
20
21+
3
35
5
6
7
7+
8
9
MA 15+

Plusieurs valeurs aberrantes : 180 et 35. Dans le monde, les jeux sont autorisés à partir de 18 ans https://fr.wikipedia.org/wiki/Syst%C3%A8me_d%27%C3%A9valuation_des_jeux_vid%C3%A9o sauf pour l'arabie saoudite et la corée à 21 ans. MA15+ est une notation australienne qui signifie autorisé à partir de 15 ans. 
Arbitrages : 
- 180 et 35 ramenés à 18 ans
- Nous allons standardiser tous les numéros suivis de + dans la mesure où les jeux sont autorisés à partir de l'âge indiqué.

In [0]:
rules = [
    (r'\+|MA |180|35')
    ]
rule = "|".join(rules)
result = clean_df \
    .filter(col("required_age").cast('string').rlike(rule)) \
    .select('required_age') \
    .distinct() \
    .orderBy('required_age')

display(result)

required_age
180
21+
35
7+
MA 15+

In [0]:
from pyspark.sql.functions import regexp_replace, col

rules = [
    (r'\+|MA ', ''),
    (r'35|180', '18')
]

for search, replace in rules:
    clean_df = clean_df.withColumn("required_age", regexp_replace(col("required_age"), search, replace))
clean_df.show()

+-------+-------+-----+----------------------------+--------+--------------------+--------------------+------------+--------------------+------------------------------------+--------+--------------------+--------+-----+----------------------------+------------+------------+-------------------------------------+----+--------------------+--------------------+-------------------+--------------------+
|     id|  appid|  ccu|                   developer|discount|               genre|        header_image|initialprice|           languages|                                name|negative|              owners|positive|price|                   publisher|release_date|required_age|                    short_description|type|             website|            category|           platform|                 tag|
+-------+-------+-----+----------------------------+--------+--------------------+--------------------+------------+--------------------+------------------------------------+--------+--------------------+--------+-----+----------------------------+------------+------------+-------------------------------------+----+--------------------+--------------------+-------------------+--------------------+
|     10|     10|13990|                       Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|                      Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|                       Valve|   2000/11/1|           0|                 Play the world's ...|game|                    |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|
|1000000|1000000|    0|        IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|                           ASCENXION|       5|         0 .. 20,000|      27|  999|        PsychoFlux Entert...|  2021/05/14|           0|                 ASCENXION is a 2D...|game|                    |Single-player, Pa...|            windows|{"2D":159,"Abstra...|
|1000010|1000010|   99|                NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Simplified Chines...|                         Crown Trick|     646|  200,000 .. 500,000|    4032|  599|        Team17, NEXT Studios|  2020/10/16|           0|                 Enter a labyrinth...|game|                    |Single-player, Pa...|            windows|{"2D":205,"Action...|
|1000030|1000030|   76|         Vertigo Gaming Inc.|       0|Action, Indie, Si...|https://cdn.akama...|        1999|             English|                Cook, Serve, Deli...|     115|  100,000 .. 200,000|    1575| 1999|         Vertigo Gaming Inc.|  2020/10/14|           0|                 Cook, serve and m...|game|http://www.cookse...|Multi-player, Sin...|       mac, windows|{"2D":187,"Action...|
|1000040|1000040|    0|               DoubleC Games|       0|Action, Casual, I...|https://cdn.akama...|         199|  Simplified Chinese|                            细胞战争|       1|         0 .. 20,000|       0|  199|               DoubleC Games|  2019/03/30|           0|这是一款打击感十足的细胞主题游戏！...|game|                    |       Single-player|            windows|{"Action":22,"Cas...|
|1000080|1000080|    3|          IndieLeague Studio|      60|Action, Adventure...|https://cdn.akama...|        1999|Simplified Chines...|                             Zengeon|     462|  100,000 .. 200,000|    1018|  799|                    2P Games|  2019/06/24|           0|                 Zengeon is an ani...|game|                    |Multi-player, Sin...|       mac, windows|{"Action":138,"Ac...|
|1000100|1000100|    0|                    七月九日|       0|Adventure, Indie,...|https://cdn.akama...|        1299|Japanese, Simplif...|干支セトラ　陽ノ卷｜干支etc.　陽之卷|       6|         0 .. 20,000|      18| 1299|             Starship Studio|  2019/01/24|           0|耐用年数を超えて綻びゆく都市風水を...|game|http://0709.noor....|Single-player, St...|            windows|{"Adventure":20,"...|
|1000110|1000110|    0|          重庆环游者网络科技|       0|Action, Adventure...|https://cdn.akama...|           0|English, Simplifi...|            Jumping Master(跳跳大咖)|      34|    20,000 .. 50,000|      50|    0|          重庆环游者网络科技|   2019/04/8|           0|                 Jumping Master is...|game|http://www.huanyz...|Multi-player, Sin...|            windows|{"Action":24,"Adv...|
|1000130|1000130|    0|            Simon Codrington|       0|       Casual, Indie|https://cdn.akama...|         299|             English|                       Cube Defender|       0|         0 .. 20,000|       6|  299|            Simon Codrington|   2019/01/6|           0|                 Build turrets and...|game|                    |Single-player, St...|       mac, windows|{"Action":10,"Cas...|
|1000280|1000280|    0|                Villain Role|       0|          Indie, RPG|https://cdn.akama...|        1399|English, Simplifi...|                Tower of Origin2-...|      12|         0 .. 20,000|      32| 1399|                Villain Role|   2021/09/9|           0|                 As the protagonis...|game|https://weibo.com...|       Single-player|            windows|{"2D":101,"Anime"...|
|1000310|1000310|    0|海南众铖互娱网络科技有限公司|       0|Action, RPG, Stra...|https://cdn.akama...|          99|  Simplified Chinese|                      人气动漫大乱斗|       5|         0 .. 20,000|       1|   99|海南众铖互娱网络科技有限公司|  2019/12/17|           0|这是一款动漫呆萌与战斗激情完美交融...|game|                    |Multi-player, Sin...|            windows|{"Action":31,"Ani...|
|1000360|1000360|   59|                      Kubold|       0|Action, Early Access|https://cdn.akama...|        1699|English, Simplifi...|                       Hellish Quart|     315|  200,000 .. 500,000|    4031| 1699|                      Kubold|  2021/02/16|           0|                 A physics-based, ...|game|https://www.helli...|Multi-player, Sin...|            windows|{"3D Fighter":201...|
|1000370|1000370|    0|                 LFiO Studio|       0|               Indie|https://cdn.akama...|           0|             English|                      SurReal Subway|       1|         0 .. 20,000|       0|    0|                 LFiO Studio|   2019/01/3|           0|                 It's a Horror gam...|game|                    |       Single-player|            windows|{"Horror":13,"Ind...|
|1000380|1000380|    0|            Fireroot Studios|       0|Action, Adventure...|https://cdn.akama...|           0|             English|                        Rogue Reaper|      87|  100,000 .. 200,000|     309|    0|            Fireroot Studios|   2019/02/1|           0|                 Rogue Reaper is a...|game|https://roguereap...|Single-player, St...|            windows|{"3D Platformer":...|
|1000410|1000410|    6|                   KillPixel|       0|Action, Early Access|https://cdn.akama...|        2499|             English|                 WRATH: Aeon of Ruin|     328|    20,000 .. 50,000|    1212| 2499|        3D Realms, Fulqru...|  2019/11/22|           0|                 3D Realms, creato...|game|http://www.wrath....|       Single-player|            windows|{"1990's":8,"Acti...|
|1000470|1000470|    0|                DarkDes Labs|       0|Adventure, Indie,...|https://cdn.akama...|         499|English, Russian,...|                Drawngeon: Dungeo...|      13|    20,000 .. 50,000|      55|  499|                DarkDes Labs|  2019/05/24|           0|                 Inkland - the han...|game|                    |Single-player, St...|            windows|{"Adventure":158,...|
|1000480|1000480|    0|                Meadow Games|       0|Action, Indie, RP...|https://cdn.akama...|         999|             English|                       Battle Motion|       6|         0 .. 20,000|       9|  999|                Meadow Games|   2019/02/4|           0|                 Single-player act...|game|                    |       Single-player|linux, mac, windows|{"Action":32,"Com...|
|1000500|1000500|    0|                    Amonga99|       0|Action, Casual, I...|https://cdn.akama...|         699|English, French, ...|                The Undisputables...|       3|  100,000 .. 200,000|       9|  699|                    Amonga99|   2021/12/5|           0|                 The Undisputables...|game|https://amonga99.com|Multi-player, Sin...|linux, mac, windows|{"Action":298,"Ba...|
|1000510|1000510|    0|            1337 Game Design|       0|           Education|https://cdn.akama...|           0|             English|                The Marvellous Ma...|      21|    20,000 .. 50,000|     104|    0|            1337 Game Design|  2019/02/11|           0|                 The Marvellous Ma...|game|https://www.1337g...|                    |            windows|{"Education":21,"...|
|1000540|1000540|    0|              Hellride Games|       0|Casual, Free to P...|https://cdn.akama...|           0|             English|                    Tactical Control|      12|    20,000 .. 50,000|      53|    0|              Hellride Games|  2019/03/21|           0|                 Tactical Control:...|game|                    |Multi-player, Sta...|            windows|{"Casual":26,"Fre...|
+-------+-------+-----+----------------------------+--------+--------------------+--------------------+------------+--------------------+------------------------------------+--------+--------------------+--------+-----+----------------------------+------------+------------+-------------------------------------+----+--------------------+--------------------+-------------------+--------------------+
only showing top 20 rows

In [0]:
rules = [
    (r'\+|MA |180|35')
    ]
rule = "|".join(rules)
result = clean_df \
    .filter(col("required_age").cast('string').rlike(rule)) \
    .select('required_age') \
    .distinct() \
    .orderBy('required_age')

result.show()

+------------+
|required_age|
+------------+
+------------+

In [0]:
clean_df.printSchema()

root
 |-- id: string (nullable = true)
 |-- appid: long (nullable = true)
 |-- ccu: long (nullable = true)
 |-- developer: string (nullable = true)
 |-- discount: string (nullable = true)
 |-- genre: string (nullable = true)
 |-- header_image: string (nullable = true)
 |-- initialprice: string (nullable = true)
 |-- languages: string (nullable = true)
 |-- name: string (nullable = true)
 |-- negative: long (nullable = true)
 |-- owners: string (nullable = true)
 |-- positive: long (nullable = true)
 |-- price: string (nullable = true)
 |-- publisher: string (nullable = true)
 |-- release_date: string (nullable = true)
 |-- required_age: string (nullable = true)
 |-- short_description: string (nullable = true)
 |-- type: string (nullable = true)
 |-- website: string (nullable = true)
 |-- category: string (nullable = false)
 |-- platform: string (nullable = false)
 |-- tag: string (nullable = true)

### languages

In [0]:
rules = [
    r'#lang_',
    r'all with full audio support',
    r'full audio',
    r'not supported',
    r'text only',
    r'traditional',
    r'simplified',
    r'\- brazil',
    r'\- portugal',
    r'\(gurmukhi\)',
    r'\- latin america',
    r'\- spain',
    r'english dutch  english',
    r'slovak(?!ian)',
    r';',
    r'\[b\]\*\[/b\]',
    r';',
    r'\[b\]\*\[/b\]',
    r'\r\n'
    r' ,'
    r',(\s*,)+'
    r',\s*'
    r'^,+|,+$'
    ]
rule = "|".join(rules)

result = clean_df \
    .filter(clean_df["languages"].rlike(rule)) \
    .select('languages')

display(result)

languages
"English, French, German, Italian, Spanish - Spain, Portuguese - Portugal, Japanese, Traditional Chinese, Korean, #lang_slovakian, Dutch, Russian, Hungarian, Czech, Polish"
"English, French, German, Italian, Spanish - Spain, Japanese, (all with full audio support)"
"English[b]*[/b], German, French, Italian, Spanish - Spain, Russian [b]*[/b]"
"English, French, German, Spanish - Spain, Italian, Czech, Russian, Hungarian, Polish, Traditional Chinese (text only)"
"English, French, Spanish - Spain, Italian, German;, Russian, Polish, Japanese, German, Korean"
"English, French, Spanish - Spain, Italian, German;, Japanese, German"
"English[b]*[/b], German, French, Polish, Spanish - Spain, Italian [b]*[/b]"
"English[b]*[/b], French, German[b]*[/b], Italian, Spanish - Spain [b]*[/b]"
"English[b]*[/b], French[b]*[/b], Italian[b]*[/b], German[b]*[/b], Spanish - Spain[b]*[/b], Russian, Polish, Korean[b]*[/b], Japanese [b]*[/b]"
"English (full audio), French, German, Italian, Spanish - Spain, English"
"English, French, German, Italian, Spanish - Spain, Portuguese - Portugal, Japanese, Traditional Chinese, Korean, #lang_slovakian, Dutch, Russian, Hungarian, Czech, Polish"

Languages regroupe des informations hétérogènes : langues, variantes locales dans certains pays, prise en charge des langues audio. Elle nécessite un nettoyage et une extraction des données par ligne.

In [0]:
from pyspark.sql.functions import regexp_replace, col, trim

rules = [
    (r'#lang_|\(all with full audio support\)|\(text only\)|\(full audio\)|Traditional|Simplified|\- Brazil|\- Portugal|\(Gurmukhi\)|\- Latin America|\- Spain|;|\[b\]\*\[\/b\]|, ', ', '),
    (r'Not supported\,', ''),
    (r'English Dutch  English', 'English, Dutch'),
    (r'Slovak(?!ian)', 'Slovakian'),
    (r'\r\n', ', '),
    (r' ,', ','),
    (r',(\s*,)+', ','),
    (r',\s*', ', '),
    (r'^,+|,+$', ''),
]

for search, replace in rules:
    clean_df = clean_df.withColumn("languages", trim(regexp_replace(col("languages"), search, replace)))

clean_df.show(truncate=False)

+-------+-------+-----+----------------------------+--------+--------------------------------------------------------------+-----------------------------------------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------+--------+------------------------+--------+-----+-----------------------------+------------+------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|id     |appid  |ccu  |developer                   |discount|genre                                                         |header_image                                                                 |initialprice|languages                                                                                                                                                                                                                                                              |name                                          |negative|owners                  |positive|price|publisher                    |release_date|required_age|short_description                                                                                                                                                                                                                                                                                                          |type|website                                |category                                                                                                                                                                                                                                               |platform           |tag                                                                                                                                                                                                                                                                                                                                                              |
+-------+-------+-----+----------------------------+--------+--------------------------------------------------------------+-----------------------------------------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------+--------+------------------------+--------+-----+-----------------------------+------------+------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|10     |10     |13990|Valve                       |0       |Action                                                        |https://cdn.akamai.steamstatic.com/steam/apps/10/header.jpg?t=1666823513     |999         |English, French, German, Italian, Spanish, Chinese, Chinese, Korean                                                                                                                                                                                                    |Counter-Strike                                |5199    |10,000,000 .. 20,000,000|201215  |999  |Valve                        |2000/11/1   |0           |Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role.|game|                                       |Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP                                                                                                                                                                       |linux, mac, windows|{"1980s":266,"1990's":1191,"Action":5426,"Assassin":227,"Classic":2784,"Competitive":1607,"FPS":4831,"First-Person":1707,"Military":632,"Multiplayer":3392,"Nostalgia":131,"Old School":769,"PvP":881,"Score Attack":289,"Shooter":3353,"Strategy":614,"Survival":304,"Tactical":1344,"Team-Based":1864,"e-sports":1192}                                         |
|1000000|1000000|0    |IndigoBlue Game Studio      |0       |Action, Adventure, Indie                                      |https://cdn.akamai.steamstatic.com/steam/apps/1000000/header.jpg?t=1655723048|999         |English, Korean, Chinese                                                                                                                                                                                                                                               |ASCENXION                                     |5       |0 .. 20,000             |27      |999  |PsychoFlux Entertainment     |2021/05/14  |0           |ASCENXION is a 2D shoot 'em up game where you explore the field to progress. Players must overcome puzzles, traps, elite units, boss fights, and other various obstacles while navigating the field. Grow stronger through rewards earned, to uncover the truth of this world.                                             |game|                                       |Single-player, Partial Controller Support, Steam Achievements, Steam Cloud                                                                                                                                                                             |windows            |{"2D":159,"Abstract":111,"Action":138,"Adventure":73,"Atmospheric":88,"Bullet Hell":179,"Colorful":124,"Controller":148,"Difficult":161,"GameMaker":51,"Great Soundtrack":38,"Indie":69,"Metroidvania":181,"Minimalist":136,"Robots":100,"Shoot 'Em Up":186,"Shooter":159,"Side Scroller":175,"Singleplayer":71,"Twin Stick Shooter":170}                        |
|1000010|1000010|99   |NEXT Studios                |70      |Adventure, Indie, RPG, Strategy                               |https://cdn.akamai.steamstatic.com/steam/apps/1000010/header.jpg?t=1655724189|1999        |Chinese, English, Japanese, Chinese, French, German, Spanish, Russian, Portuguese                                                                                                                                                                                      |Crown Trick                                   |646     |200,000 .. 500,000      |4032    |599  |Team17, NEXT Studios         |2020/10/16  |0           |Enter a labyrinth that moves as you move, where mastering the elements is key to defeating enemies and uncovering the mysteries of this underground world. With a new experience awaiting every time you enter the dungeon, let the power bestowed by the crown guide you in this challenging adventure!                   |game|                                       |Single-player, Partial Controller Support, Steam Achievements, Steam Cloud, Steam Trading Cards                                                                                                                                                        |windows            |{"2D":205,"Action-Adventure":179,"Adventure":225,"Difficult":189,"Dungeon Crawler":225,"Fantasy":179,"Female Protagonist":217,"Magic":171,"Perma Death":231,"RPG":237,"Replay Value":192,"Rogue-like":268,"Rogue-lite":226,"Singleplayer":211,"Strategy":225,"Tactical":184,"Top-Down":178,"Turn-Based":222,"Turn-Based Combat":254,"Turn-Based Strategy":216}   |
|1000030|1000030|76   |Vertigo Gaming Inc.         |0       |Action, Indie, Simulation, Strategy                           |https://cdn.akamai.steamstatic.com/steam/apps/1000030/header.jpg?t=1660866300|1999        |English                                                                                                                                                                                                                                                                |Cook, Serve, Delicious! 3?!                   |115     |100,000 .. 200,000      |1575    |1999 |Vertigo Gaming Inc.          |2020/10/14  |0           |Cook, serve and manage your food truck as you dish out hundreds of different foods across war-torn America in this massive sequel to the million-selling series!                                                                                                                                                           |game|http://www.cookservedelicious.com      |Multi-player, Single-player, Co-op, Steam Achievements, Steam Cloud, Shared/Split Screen, Full controller support, Steam Trading Cards, Shared/Split Screen Co-op, Remote Play on Phone, Remote Play on Tablet, Remote Play on TV, Remote Play Together|mac, windows       |{"2D":187,"Action":175,"Arcade":200,"Casual":209,"Co-op":175,"Co-op Campaign":123,"Comedy":176,"Cooking":119,"Difficult":208,"Family Friendly":175,"Fast-Paced":120,"Funny":184,"Local Co-Op":163,"Local Multiplayer":158,"Management":213,"Multiplayer":157,"Simulation":182,"Singleplayer":134,"Strategy":190,"Typing":221}                                    |
|1000040|1000040|0    |DoubleC Games               |0       |Action, Casual, Indie, Simulation                             |https://cdn.akamai.steamstatic.com/steam/apps/1000040/header.jpg?t=1627033870|199         |Chinese                                                                                                                                                                                                                                                                |细胞战争                                      |1       |0 .. 20,000             |0       |199  |DoubleC Games                |2019/03/30  |0           |这是一款打击感十足的细胞主题游戏！操作简单但活下去却不简单，“你”作为侵入人体的细菌病毒，通过与细胞之间的战斗来获得基因变异点数和进入下一关的资格，每种细菌病毒都有独特的能力和攻击效果，你是否可以破坏五大器官并占领人体呢！？                                                                                             |game|                                       |Single-player                                                                                                                                                                                                                                          |windows            |{"Action":22,"Casual":22,"Indie":21,"Simulation":20}                                                                                                                                                                                                                                                                                                             |
|1000080|1000080|3    |IndieLeague Studio          |60      |Action, Adventure, Indie, RPG                                 |https://cdn.akamai.steamstatic.com/steam/apps/1000080/header.jpg?t=1667062553|1999        |Chinese, English, Chinese, Japanese, Korean                                                                                                                                                                                                                            |Zengeon                                       |462     |100,000 .. 200,000      |1018    |799  |2P Games                     |2019/06/24  |0           |Zengeon is an anime infused Action RPG and Roguelite with a selection of unique characters and varying play-styles. Slaughter your way through demonic hordes and colossal bosses with hundreds of combination and skill possibilities!                                                                                    |game|                                       |Multi-player, Single-player, Steam Achievements, Full controller support, Steam Trading Cards                                                                                                                                                          |mac, windows       |{"Action":138,"Action RPG":77,"Action Roguelike":111,"Adventure":115,"Anime":84,"Casual":31,"Co-op":34,"Early Access":38,"Female Protagonist":36,"Hack and Slash":57,"Indie":128,"JRPG":30,"Linear":51,"Multiplayer":62,"Online Co-Op":38,"RPG":121,"Rogue-like":53,"Rogue-lite":67,"Sexual Content":33,"Singleplayer":46}                                       |
|1000100|1000100|0    |七月九日                    |0       |Adventure, Indie, RPG, Strategy                               |https://cdn.akamai.steamstatic.com/steam/apps/1000100/header.jpg?t=1561522270|1299        |Japanese, Chinese, Chinese                                                                                                                                                                                                                                             |干支セトラ　陽ノ卷｜干支etc.　陽之卷          |6       |0 .. 20,000             |18      |1299 |Starship Studio              |2019/01/24  |0           |耐用年数を超えて綻びゆく都市風水を修復するため、次代の風水師候補に選ばれた主人公。 綻びから襲い来る妖異を討ち祓い、半年後の認定試験に挑むため与えられたのは、十二支――陰陽五行の化身である１２人の男達だった。 それは、400年に渡る首都繁栄の終焉。                                                                          |game|http://0709.noor.jp/etc                |Single-player, Steam Achievements, Steam Cloud                                                                                                                                                                                                         |windows            |{"Adventure":20,"Anime":11,"Dating Sim":10,"Indie":20,"RPG":20,"Strategy":20}                                                                                                                                                                                                                                                                                    |
|1000110|1000110|0    |重庆环游者网络科技          |0       |Action, Adventure, Casual, Free to Play, Massively Multiplayer|https://cdn.akamai.steamstatic.com/steam/apps/1000110/header.jpg?t=1562917106|0           |English, Chinese, Chinese                                                                                                                                                                                                                                              |Jumping Master(跳跳大咖)                      |34      |20,000 .. 50,000        |50      |0    |重庆环游者网络科技           |2019/04/8   |0           |Jumping Master is a innovative casual competitive game fully merged with classic gameplay of mushroom game. It aims to help us revisit the classic mushroom game in our chlidhood.                                                                                                                                         |game|http://www.huanyz.com/bzjj/            |Multi-player, Single-player, Co-op, Online PvP, Online Co-op, PvP                                                                                                                                                                                      |windows            |{"Action":24,"Adventure":23,"Casual":24,"Free to Play":26,"Massively Multiplayer":25}                                                                                                                                                                                                                                                                            |
|1000130|1000130|0    |Simon Codrington            |0       |Casual, Indie                                                 |https://cdn.akamai.steamstatic.com/steam/apps/1000130/header.jpg?t=1646024900|299         |English                                                                                                                                                                                                                                                                |Cube Defender                                 |0       |0 .. 20,000             |6       |299  |Simon Codrington             |2019/01/6   |0           |Build turrets and destroy wave after wave of cube enemies in this minimalist and addictive tower defence game. Battle it out with a bunch of cube enemies and blast them off the map with a range of unique turrets.                                                                                                       |game|                                       |Single-player, Steam Achievements, Steam Leaderboards                                                                                                                                                                                                  |mac, windows       |{"Action":10,"Casual":31,"Colorful":10,"Indie":31,"Sandbox":11,"Strategy":10,"Tower Defense":16}                                                                                                                                                                                                                                                                 |

In [0]:
rules = [
    r'#lang_',
    r'all with full audio support',
    r'full audio',
    r'not supported',
    r'text only',
    r'traditional',
    r'simplified',
    r'\- brazil',
    r'\- portugal',
    r'\(gurmukhi\)',
    r'\- latin america',
    r'\- spain',
    r'english dutch  english',
    r'slovak(?!ian)',
    r';',
    r'\[b\]\*\[/b\]',
    r'\r\n'
    r' ,'
    r',(\s*,)+'
    r',\s*'
    r'^,+|,+$'
    ]

rule = "|".join(rules)

result = clean_df \
    .select('languages') \
    .filter(clean_df["languages"].rlike(rule))
result.show(truncate=False)

+---------+
|languages|
+---------+
+---------+

In [0]:
from pyspark.sql.functions import explode, split, trim, col
clean_df = clean_df.withColumn("language", explode(split(trim(col("languages")), ", ")))
clean_df.show()

+-------+-------+-----+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+--------------------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+----------+
|     id|  appid|  ccu|           developer|discount|               genre|        header_image|initialprice|           languages|          name|negative|              owners|positive|price|           publisher|release_date|required_age|   short_description|type|website|            category|           platform|                 tag|  language|
+-------+-------+-----+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+--------------------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+----------+
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|   English|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|    French|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|    German|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|   Italian|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|   Spanish|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|   Chinese|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|   Chinese|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|    Korean|
|1000000|1000000|    0|IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|     ASCENXION|       5|         0 .. 20,000|      27|  999|PsychoFlux Entert...|  2021/05/14|           0|ASCENXION is a 2D...|game|       |Single-player, Pa...|            windows|{"2D":159,"Abstra...|   English|
|1000000|1000000|    0|IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|     ASCENXION|       5|         0 .. 20,000|      27|  999|PsychoFlux Entert...|  2021/05/14|           0|ASCENXION is a 2D...|game|       |Single-player, Pa...|            windows|{"2D":159,"Abstra...|    Korean|
|1000000|1000000|    0|IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|     ASCENXION|       5|         0 .. 20,000|      27|  999|PsychoFlux Entert...|  2021/05/14|           0|ASCENXION is a 2D...|game|       |Single-player, Pa...|            windows|{"2D":159,"Abstra...|   Chinese|
|1000010|1000010|   99|        NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Chinese, English,...|   Crown Trick|     646|  200,000 .. 500,000|    4032|  599|Team17, NEXT Studios|  2020/10/16|           0|Enter a labyrinth...|game|       |Single-player, Pa...|            windows|{"2D":205,"Action...|   Chinese|
|1000010|1000010|   99|        NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Chinese, English,...|   Crown Trick|     646|  200,000 .. 500,000|    4032|  599|Team17, NEXT Studios|  2020/10/16|           0|Enter a labyrinth...|game|       |Single-player, Pa...|            windows|{"2D":205,"Action...|   English|
|1000010|1000010|   99|        NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Chinese, English,...|   Crown Trick|     646|  200,000 .. 500,000|    4032|  599|Team17, NEXT Studios|  2020/10/16|           0|Enter a labyrinth...|game|       |Single-player, Pa...|            windows|{"2D":205,"Action...|  Japanese|
|1000010|1000010|   99|        NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Chinese, English,...|   Crown Trick|     646|  200,000 .. 500,000|    4032|  599|Team17, NEXT Studios|  2020/10/16|           0|Enter a labyrinth...|game|       |Single-player, Pa...|            windows|{"2D":205,"Action...|   Chinese|
|1000010|1000010|   99|        NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Chinese, English,...|   Crown Trick|     646|  200,000 .. 500,000|    4032|  599|Team17, NEXT Studios|  2020/10/16|           0|Enter a labyrinth...|game|       |Single-player, Pa...|            windows|{"2D":205,"Action...|    French|
|1000010|1000010|   99|        NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Chinese, English,...|   Crown Trick|     646|  200,000 .. 500,000|    4032|  599|Team17, NEXT Studios|  2020/10/16|           0|Enter a labyrinth...|game|       |Single-player, Pa...|            windows|{"2D":205,"Action...|    German|
|1000010|1000010|   99|        NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Chinese, English,...|   Crown Trick|     646|  200,000 .. 500,000|    4032|  599|Team17, NEXT Studios|  2020/10/16|           0|Enter a labyrinth...|game|       |Single-player, Pa...|            windows|{"2D":205,"Action...|   Spanish|
|1000010|1000010|   99|        NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Chinese, English,...|   Crown Trick|     646|  200,000 .. 500,000|    4032|  599|Team17, NEXT Studios|  2020/10/16|           0|Enter a labyrinth...|game|       |Single-player, Pa...|            windows|{"2D":205,"Action...|   Russian|
|1000010|1000010|   99|        NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Chinese, English,...|   Crown Trick|     646|  200,000 .. 500,000|    4032|  599|Team17, NEXT Studios|  2020/10/16|           0|Enter a labyrinth...|game|       |Single-player, Pa...|            windows|{"2D":205,"Action...|Portuguese|
+-------+-------+-----+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+--------------------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+----------+
only showing top 20 rows

In [0]:
from pyspark.sql.functions import count

duplicated_entries = clean_df \
    .groupBy('name', "language") \
    .agg(count("language").alias("duplicated_language")) \
    .filter(col('duplicated_language') > 1) \
    .orderBy('duplicated_language', ascending=False)
duplicated_entries.show()

+----------------+--------+-------------------+
|            name|language|duplicated_language|
+----------------+--------+-------------------+
|           Alone| English|                  5|
|          Escape| English|                  4|
|          Bounce| English|                  4|
|           Dodge| English|                  4|
|         Endless| Chinese|                  4|
|            Lost| English|                  4|
|          Aurora| English|                  4|
|   Hide and Seek| English|                  3|
|        Parasite| English|                  3|
|Dungeon Warriors| Chinese|                  3|
|       The Tower| English|                  3|
|        The Line| Spanish|                  3|
|           Surge| English|                  3|
|         Arcadia| English|                  3|
|     Dark Matter| English|                  3|
|        The Tree| Chinese|                  3|
|         Trapped| English|                  3|
|           Chaos| English|                  3|
|         Mimicry| Spanish|                  3|
|          Azrael| English|                  3|
+----------------+--------+-------------------+
only showing top 20 rows

In [0]:
clean_df.describe().toPandas()

  summary  ...   language
0   count  ...     201056
1    mean  ...       None
2  stddev  ...       None
3     min  ...
4     max  ...  slovakian

[5 rows x 25 columns]

### Genre

In [0]:
from pyspark.sql.functions import explode, split, trim, col
clean_df = clean_df.withColumn("extracted_genre", explode(split(trim(col("genre")), ", ")))
clean_df.show()

+-------+-------+-----+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+--------------------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+--------+---------------+
|     id|  appid|  ccu|           developer|discount|               genre|        header_image|initialprice|           languages|          name|negative|              owners|positive|price|           publisher|release_date|required_age|   short_description|type|website|            category|           platform|                 tag|language|extracted_genre|
+-------+-------+-----+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+--------------------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+--------+---------------+
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...| English|         Action|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|  French|         Action|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|  German|         Action|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...| Italian|         Action|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...| Spanish|         Action|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...| Chinese|         Action|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...| Chinese|         Action|
|     10|     10|13990|               Valve|       0|              Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,000,000 .. 20,...|  201215|  999|               Valve|   2000/11/1|           0|Play the world's ...|game|       |Multi-player, Val...|linux, mac, windows|{"1980s":266,"199...|  Korean|         Action|
|1000000|1000000|    0|IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|     ASCENXION|       5|         0 .. 20,000|      27|  999|PsychoFlux Entert...|  2021/05/14|           0|ASCENXION is a 2D...|game|       |Single-player, Pa...|            windows|{"2D":159,"Abstra...| English|         Action|
|1000000|1000000|    0|IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|     ASCENXION|       5|         0 .. 20,000|      27|  999|PsychoFlux Entert...|  2021/05/14|           0|ASCENXION is a 2D...|game|       |Single-player, Pa...|            windows|{"2D":159,"Abstra...| English|      Adventure|
|1000000|1000000|    0|IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|     ASCENXION|       5|         0 .. 20,000|      27|  999|PsychoFlux Entert...|  2021/05/14|           0|ASCENXION is a 2D...|game|       |Single-player, Pa...|            windows|{"2D":159,"Abstra...| English|          Indie|
|1000000|1000000|    0|IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|     ASCENXION|       5|         0 .. 20,000|      27|  999|PsychoFlux Entert...|  2021/05/14|           0|ASCENXION is a 2D...|game|       |Single-player, Pa...|            windows|{"2D":159,"Abstra...|  Korean|         Action|
|1000000|1000000|    0|IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|     ASCENXION|       5|         0 .. 20,000|      27|  999|PsychoFlux Entert...|  2021/05/14|           0|ASCENXION is a 2D...|game|       |Single-player, Pa...|            windows|{"2D":159,"Abstra...|  Korean|      Adventure|
|1000000|1000000|    0|IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|     ASCENXION|       5|         0 .. 20,000|      27|  999|PsychoFlux Entert...|  2021/05/14|           0|ASCENXION is a 2D...|game|       |Single-player, Pa...|            windows|{"2D":159,"Abstra...|  Korean|          Indie|
|1000000|1000000|    0|IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|     ASCENXION|       5|         0 .. 20,000|      27|  999|PsychoFlux Entert...|  2021/05/14|           0|ASCENXION is a 2D...|game|       |Single-player, Pa...|            windows|{"2D":159,"Abstra...| Chinese|         Action|
|1000000|1000000|    0|IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|     ASCENXION|       5|         0 .. 20,000|      27|  999|PsychoFlux Entert...|  2021/05/14|           0|ASCENXION is a 2D...|game|       |Single-player, Pa...|            windows|{"2D":159,"Abstra...| Chinese|      Adventure|
|1000000|1000000|    0|IndigoBlue Game S...|       0|Action, Adventure...|https://cdn.akama...|         999|English, Korean, ...|     ASCENXION|       5|         0 .. 20,000|      27|  999|PsychoFlux Entert...|  2021/05/14|           0|ASCENXION is a 2D...|game|       |Single-player, Pa...|            windows|{"2D":159,"Abstra...| Chinese|          Indie|
|1000010|1000010|   99|        NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Chinese, English,...|   Crown Trick|     646|  200,000 .. 500,000|    4032|  599|Team17, NEXT Studios|  2020/10/16|           0|Enter a labyrinth...|game|       |Single-player, Pa...|            windows|{"2D":205,"Action...| Chinese|      Adventure|
|1000010|1000010|   99|        NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Chinese, English,...|   Crown Trick|     646|  200,000 .. 500,000|    4032|  599|Team17, NEXT Studios|  2020/10/16|           0|Enter a labyrinth...|game|       |Single-player, Pa...|            windows|{"2D":205,"Action...| Chinese|          Indie|
|1000010|1000010|   99|        NEXT Studios|      70|Adventure, Indie,...|https://cdn.akama...|        1999|Chinese, English,...|   Crown Trick|     646|  200,000 .. 500,000|    4032|  599|Team17, NEXT Studios|  2020/10/16|           0|Enter a labyrinth...|game|       |Single-player, Pa...|            windows|{"2D":205,"Action...| Chinese|            RPG|
+-------+-------+-----+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+--------------------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+--------+---------------+
only showing top 20 rows

In [0]:
result = clean_df \
    .select('extracted_genre') \
    .agg(countDistinct('extracted_genre').alias('genre_nb'))
result.show(truncate=False)

+--------+
|genre_nb|
+--------+
|29      |
+--------+

In [0]:
from pyspark.sql.functions import count

duplicated_entries = clean_df \
    .select('appid', 'name', 'extracted_genre') \
    .dropDuplicates(['appid', 'extracted_genre']) \
    .groupBy('name', 'extracted_genre') \
    .agg(count("extracted_genre").alias("duplicated_genre")) \
    .filter(col('duplicated_genre') > 1) \
    .orderBy('duplicated_genre', ascending=False)
duplicated_entries.show(truncate=False)

+---------------+---------------+----------------+
|name           |extracted_genre|duplicated_genre|
+---------------+---------------+----------------+
|Alone          |Adventure      |4               |
|Escape         |Indie          |4               |
|Lost           |Adventure      |4               |
|Alone          |Indie          |4               |
|Bounce         |Casual         |4               |
|Lost           |Indie          |4               |
|Dodge          |Indie          |4               |
|Trapped        |Adventure      |3               |
|Puzzle Box     |Casual         |3               |
|Fireflies      |Indie          |3               |
|Escape         |Adventure      |3               |
|Puzzle Box     |Adventure      |3               |
|Arena          |Indie          |3               |
|Cube           |Casual         |3               |
|Parasite       |Indie          |3               |
|Lost           |Casual         |3               |
|Dark Matter    |Indie          |3               |
|Alone          |Casual         |3               |
|Northern Lights|Indie          |3               |
|Bounce         |Indie          |3               |
+---------------+---------------+----------------+
only showing top 20 rows

In [0]:
clean_df.describe().toPandas()

  summary                  id  ...   language extracted_genre
0   count              575714  ...     575714          575714
1    mean  1044526.4804468886  ...       None            None
2  stddev   511398.6888631175  ...       None            None
3     min                  10  ...
4     max              999990  ...  slovakian  Web Publishing

[5 rows x 26 columns]

### tag

In [0]:
result = clean_df \
    .select('appid', 'tag') \
    .distinct() \
    .limit(1)
result.show(truncate=False)

+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|appid|tag                                                                                                                                                                                                                                                                                                                     |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|10   |{"1980s":266,"1990's":1191,"Action":5426,"Assassin":227,"Classic":2784,"Competitive":1607,"FPS":4831,"First-Person":1707,"Military":632,"Multiplayer":3392,"Nostalgia":131,"Old School":769,"PvP":881,"Score Attack":289,"Shooter":3353,"Strategy":614,"Survival":304,"Tactical":1344,"Team-Based":1864,"e-sports":1192}|
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

In [0]:
type(clean_df['tag'])

pyspark.sql.connect.column.Column

Les tags sont couplés à un nombre de votes. Pour les conserver, il est nécessaire de mapper les informations avant de les extraire.

In [0]:
from pyspark.sql.functions import from_json, explode, col
from pyspark.sql.types import MapType, StringType, IntegerType

tag_schema = MapType(StringType(), IntegerType())

clean_df = clean_df \
    .dropDuplicates(['appid']) \
    .withColumn("tag_map", from_json(col("tag"), tag_schema)) \
    .select('*', explode(col("tag_map")).alias("extracted_tag", "tag_vote_nb"))

clean_df.show(truncate=False)

+-------+-------+---+----------------------+--------+-------------------------------------------------------------------------+-----------------------------------------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------+----------------+--------+----------------+--------+-----+----------------------+------------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+------------------------------------+--------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+-----------+
|id     |appid  |ccu|developer             |discount|genre                                                                    |header_image                                                                 |initialprice|languages                                                                                                                                |name            |negative|owners          |positive|price|publisher             |release_date|required_age|short_description                                                                                                                                                                                                                                                                                   |type|website                             |category                                                                  |platform|tag                                                                                                                                                                                                                                     |language|extracted_genre|tag_map                                                                                                                                                                                                                                                                |extracted_tag    |tag_vote_nb|
+-------+-------+---+----------------------+--------+-------------------------------------------------------------------------+-----------------------------------------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------+----------------+--------+----------------+--------+-----+----------------------+------------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+------------------------------------+--------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+-----------+
|1002420|1002420|0  |Shindenken            |0       |Action, Indie                                                            |https://cdn.akamai.steamstatic.com/steam/apps/1002420/header.jpg?t=1666986454|799         |English, Japanese                                                                                                                        |Agartha         |3       |0 .. 20,000     |7       |799  |Fruitbat Factory      |2019/03/20  |0           |Agartha is an puzzle platformer where you play various adventurers carving out their way through countless levels using very limited resources.                                                                                                                                                     |game|https://fruitbatfactory.com/agartha/|Single-player, Partial Controller Support, Steam Achievements, Steam Cloud|windows |{"2D":60,"Action":74,"Destruction":35,"Exploration":44,"Indie":68,"Nature":32,"Ninja":26,"Physics":48,"Pixel Graphics":57,"Platformer":54,"Puzzle":46,"Puzzle-Platformer":39,"Retro":30,"Sandbox":41,"Singleplayer":28,"Underground":24}|English |Action         |{2D -> 60, Action -> 74, Destruction -> 35, Exploration -> 44, Indie -> 68, Nature -> 32, Ninja -> 26, Physics -> 48, Pixel Graphics -> 57, Platformer -> 54, Puzzle -> 46, Puzzle-Platformer -> 39, Retro -> 30, Sandbox -> 41, Singleplayer -> 28, Underground -> 24}|2D               |60         |
|1002420|1002420|0  |Shindenken            |0       |Action, Indie                                                            |https://cdn.akamai.steamstatic.com/steam/apps/1002420/header.jpg?t=1666986454|799         |English, Japanese                                                                                                                        |Agartha         |3       |0 .. 20,000     |7       |799  |Fruitbat Factory      |2019/03/20  |0           |Agartha is an puzzle platformer where you play various adventurers carving out their way through countless levels using very limited resources.                                                                                                                                                     |game|https://fruitbatfactory.com/agartha/|Single-player, Partial Controller Support, Steam Achievements, Steam Cloud|windows |{"2D":60,"Action":74,"Destruction":35,"Exploration":44,"Indie":68,"Nature":32,"Ninja":26,"Physics":48,"Pixel Graphics":57,"Platformer":54,"Puzzle":46,"Puzzle-Platformer":39,"Retro":30,"Sandbox":41,"Singleplayer":28,"Underground":24}|English |Action         |{2D -> 60, Action -> 74, Destruction -> 35, Exploration -> 44, Indie -> 68, Nature -> 32, Ninja -> 26, Physics -> 48, Pixel Graphics -> 57, Platformer -> 54, Puzzle -> 46, Puzzle-Platformer -> 39, Retro -> 30, Sandbox -> 41, Singleplayer -> 28, Underground -> 24}|Action           |74         |
|1002420|1002420|0  |Shindenken            |0       |Action, Indie                                                            |https://cdn.akamai.steamstatic.com/steam/apps/1002420/header.jpg?t=1666986454|799         |English, Japanese                                                                                                                        |Agartha         |3       |0 .. 20,000     |7       |799  |Fruitbat Factory      |2019/03/20  |0           |Agartha is an puzzle platformer where you play various adventurers carving out their way through countless levels using very limited resources.                                                                                                                                                     |game|https://fruitbatfactory.com/agartha/|Single-player, Partial Controller Support, Steam Achievements, Steam Cloud|windows |{"2D":60,"Action":74,"Destruction":35,"Exploration":44,"Indie":68,"Nature":32,"Ninja":26,"Physics":48,"Pixel Graphics":57,"Platformer":54,"Puzzle":46,"Puzzle-Platformer":39,"Retro":30,"Sandbox":41,"Singleplayer":28,"Underground":24}|English |Action         |{2D -> 60, Action -> 74, Destruction -> 35, Exploration -> 44, Indie -> 68, Nature -> 32, Ninja -> 26, Physics -> 48, Pixel Graphics -> 57, Platformer -> 54, Puzzle -> 46, Puzzle-Platformer -> 39, Retro -> 30, Sandbox -> 41, Singleplayer -> 28, Underground -> 24}|Destruction      |35         |
|1002420|1002420|0  |Shindenken            |0       |Action, Indie                                                            |https://cdn.akamai.steamstatic.com/steam/apps/1002420/header.jpg?t=1666986454|799         |English, Japanese                                                                                                                        |Agartha         |3       |0 .. 20,000     |7       |799  |Fruitbat Factory      |2019/03/20  |0           |Agartha is an puzzle platformer where you play various adventurers carving out their way through countless levels using very limited resources.                                                                                                                                                     |game|https://fruitbatfactory.com/agartha/|Single-player, Partial Controller Support, Steam Achievements, Steam Cloud|windows |{"2D":60,"Action":74,"Destruction":35,"Exploration":44,"Indie":68,"Nature":32,"Ninja":26,"Physics":48,"Pixel Graphics":57,"Platformer":54,"Puzzle":46,"Puzzle-Platformer":39,"Retro":30,"Sandbox":41,"Singleplayer":28,"Underground":24}|English |Action         |{2D -> 60, Action -> 74, Destruction -> 35, Exploration -> 44, Indie -> 68, Nature -> 32, Ninja -> 26, Physics -> 48, Pixel Graphics -> 57, Platformer -> 54, Puzzle -> 46, Puzzle-Platformer -> 39, Retro -> 30, Sandbox -> 41, Singleplayer -> 28, Underground -> 24}|Exploration      |44         |
|1002420|1002420|0  |Shindenken            |0       |Action, Indie                                                            |https://cdn.akamai.steamstatic.com/steam/apps/1002420/header.jpg?t=1666986454|799         |English, Japanese                                                                                                                        |Agartha         |3       |0 .. 20,000     |7       |799  |Fruitbat Factory      |2019/03/20  |0           |Agartha is an puzzle platformer where you play various adventurers carving out their way through countless levels using very limited resources.                                                                                                                                                     |game|https://fruitbatfactory.com/agartha/|Single-player, Partial Controller Support, Steam Achievements, Steam Cloud|windows |{"2D":60,"Action":74,"Destruction":35,"Exploration":44,"Indie":68,"Nature":32,"Ninja":26,"Physics":48,"Pixel Graphics":57,"Platformer":54,"Puzzle":46,"Puzzle-Platformer":39,"Retro":30,"Sandbox":41,"Singleplayer":28,"Underground":24}|English |Action         |{2D -> 60, Action -> 74, Destruction -> 35, Exploration -> 44, Indie -> 68, Nature -> 32, Ninja -> 26, Physics -> 48, Pixel Graphics -> 57, Platformer -> 54, Puzzle -> 46, Puzzle-Platformer -> 39, Retro -> 30, Sandbox -> 41, Singleplayer -> 28, Underground -> 24}|Indie            |68         |
|1002420|1002420|0  |Shindenken            |0       |Action, Indie                                                            |https://cdn.akamai.steamstatic.com/steam/apps/1002420/header.jpg?t=1666986454|799         |English, Japanese                                                                                                                        |Agartha         |3       |0 .. 20,000     |7       |799  |Fruitbat Factory      |2019/03/20  |0           |Agartha is an puzzle platformer where you play various adventurers carving out their way through countless levels using very limited resources.                                                                                                                                                     |game|https://fruitbatfactory.com/agartha/|Single-player, Partial Controller Support, Steam Achievements, Steam Cloud|windows |{"2D":60,"Action":74,"Destruction":35,"Exploration":44,"Indie":68,"Nature":32,"Ninja":26,"Physics":48,"Pixel Graphics":57,"Platformer":54,"Puzzle":46,"Puzzle-Platformer":39,"Retro":30,"Sandbox":41,"Singleplayer":28,"Underground":24}|English |Action         |{2D -> 60, Action -> 74, Destruction -> 35, Exploration -> 44, Indie -> 68, Nature -> 32, Ninja -> 26, Physics -> 48, Pixel Graphics -> 57, Platformer -> 54, Puzzle -> 46, Puzzle-Platformer -> 39, Retro -> 30, Sandbox -> 41, Singleplayer -> 28, Underground -> 24}|Nature           |32         |
|1002420|1002420|0  |Shindenken            |0       |Action, Indie                                                            |https://cdn.akamai.steamstatic.com/steam/apps/1002420/header.jpg?t=1666986454|799         |English, Japanese                                                                                                                        |Agartha         |3       |0 .. 20,000     |7       |799  |Fruitbat Factory      |2019/03/20  |0           |Agartha is an puzzle platformer where you play various adventurers carving out their way through countless levels using very limited resources.                                                                                                                                                     |game|https://fruitbatfactory.com/agartha/|Single-player, Partial Controller Support, Steam Achievements, Steam Cloud|windows |{"2D":60,"Action":74,"Destruction":35,"Exploration":44,"Indie":68,"Nature":32,"Ninja":26,"Physics":48,"Pixel Graphics":57,"Platformer":54,"Puzzle":46,"Puzzle-Platformer":39,"Retro":30,"Sandbox":41,"Singleplayer":28,"Underground":24}|English |Action         |{2D -> 60, Action -> 74, Destruction -> 35, Exploration -> 44, Indie -> 68, Nature -> 32, Ninja -> 26, Physics -> 48, Pixel Graphics -> 57, Platformer -> 54, Puzzle -> 46, Puzzle-Platformer -> 39, Retro -> 30, Sandbox -> 41, Singleplayer -> 28, Underground -> 24}|Ninja            |26         |
|1002420|1002420|0  |Shindenken            |0       |Action, Indie                                                            |https://cdn.akamai.steamstatic.com/steam/apps/1002420/header.jpg?t=1666986454|799         |English, Japanese                                                                                                                        |Agartha         |3       |0 .. 20,000     |7       |799  |Fruitbat Factory      |2019/03/20  |0           |Agartha is an puzzle platformer where you play various adventurers carving out their way through countless levels using very limited resources.                                                                                                                                                     |game|https://fruitbatfactory.com/agartha/|Single-player, Partial Controller Support, Steam Achievements, Steam Cloud|windows |{"2D":60,"Action":74,"Destruction":35,"Exploration":44,"Indie":68,"Nature":32,"Ninja":26,"Physics":48,"Pixel Graphics":57,"Platformer":54,"Puzzle":46,"Puzzle-Platformer":39,"Retro":30,"Sandbox":41,"Singleplayer":28,"Underground":24}|English |Action         |{2D -> 60, Action -> 74, Destruction -> 35, Exploration -> 44, Indie -> 68, Nature -> 32, Ninja -> 26, Physics -> 48, Pixel Graphics -> 57, Platformer -> 54, Puzzle -> 46, Puzzle-Platformer -> 39, Retro -> 30, Sandbox -> 41, Singleplayer -> 28, Underground -> 24}|Physics          |48         |
|1002420|1002420|0  |Shindenken            |0       |Action, Indie                                                            |https://cdn.akamai.steamstatic.com/steam/apps/1002420/header.jpg?t=1666986454|799         |English, Japanese                                                                                                                        |Agartha         |3       |0 .. 20,000     |7       |799  |Fruitbat Factory      |2019/03/20  |0           |Agartha is an puzzle platformer where you play various adventurers carving out their way through countless levels using very limited resources.                                                                                                                                                     |game|https://fruitbatfactory.com/agartha/|Single-player, Partial Controller Support, Steam Achievements, Steam Cloud|windows |{"2D":60,"Action":74,"Destruction":35,"Exploration":44,"Indie":68,"Nature":32,"Ninja":26,"Physics":48,"Pixel Graphics":57,"Platformer":54,"Puzzle":46,"Puzzle-Platformer":39,"Retro":30,"Sandbox":41,"Singleplayer":28,"Underground":24}|English |Action         |{2D -> 60, Action -> 74, Destruction -> 35, Exploration -> 44, Indie -> 68, Nature -> 32, Ninja -> 26, Physics -> 48, Pixel Graphics -> 57, Platformer -> 54, Puzzle -> 46, Puzzle-Platformer -> 39, Retro -> 30, Sandbox -> 41, Singleplayer -> 28, Underground -> 24}|Pixel Graphics   |57         |
|1002420|1002420|0  |Shindenken            |0       |Action, Indie                                                            |https://cdn.akamai.steamstatic.com/steam/apps/1002420/header.jpg?t=1666986454|799         |English, Japanese                                                                                                                        |Agartha         |3       |0 .. 20,000     |7       |799  |Fruitbat Factory      |2019/03/20  |0           |Agartha is an puzzle platformer where you play various adventurers carving out their way through countless levels using very limited resources.                                                                                                                                                     |game|https://fruitbatfactory.com/agartha/|Single-player, Partial Controller Support, Steam Achievements, Steam Cloud|windows |{"2D":60,"Action":74,"Destruction":35,"Exploration":44,"Indie":68,"Nature":32,"Ninja":26,"Physics":48,"Pixel Graphics":57,"Platformer":54,"Puzzle":46,"Puzzle-Platformer":39,"Retro":30,"Sandbox":41,"Singleplayer":28,"Underground":24}|English |Action         |{2D -> 60, Action -> 74, Destruction -> 35, Exploration -> 44, Indie -> 68, Nature -> 32, Ninja -> 26, Physics -> 48, Pixel Graphics -> 57, Platformer -> 54, Puzzle -> 46, Puzzle-Platformer -> 39, Retro -> 30, Sandbox -> 41, Singleplayer -> 28, Underground -> 24}|Platformer       |54         |

In [0]:
result = clean_df \
    .select('appid', 'extracted_tag') \
    .dropDuplicates(['appid']) \
    .agg(countDistinct('extracted_tag').alias('tag_nb'))
result.show(truncate=False)

+------+
|tag_nb|
+------+
|230   |
+------+

In [0]:
duplicated_entries = clean_df \
    .select('appid', 'name', 'publisher', 'extracted_tag') \
    .dropDuplicates(['appid', 'extracted_tag']) \
    .groupBy('name', "extracted_tag") \
    .agg(count("extracted_tag").alias('duplicated_tag')) \
    .filter(col('duplicated_tag') > 1) \
    .orderBy(desc('duplicated_tag'))
duplicated_entries.show(truncate=False)

+---------------+-------------+--------------+
|name           |extracted_tag|duplicated_tag|
+---------------+-------------+--------------+
|Bounce         |Casual       |4             |
|Escape         |Indie        |4             |
|Aurora         |Indie        |4             |
|Alone          |Indie        |4             |
|Dodge          |Indie        |4             |
|Alone          |Casual       |4             |
|Dodge          |Casual       |4             |
|Escape         |Singleplayer |4             |
|Lost           |Adventure    |4             |
|Alone          |Adventure    |4             |
|Lost           |Casual       |3             |
|Escape         |Adventure    |3             |
|Surge          |Indie        |3             |
|Hide and Seek  |Multiplayer  |3             |
|Aurora         |Casual       |3             |
|Northern Lights|Indie        |3             |
|Cube           |Indie        |3             |
|Lost           |Singleplayer |3             |
|Chaos          |Action       |3             |
|Vortex         |Sci-fi       |3             |
+---------------+-------------+--------------+
only showing top 20 rows

At each data extract, duplicated entries are generated. So, we will filter on distinct appid to get precises informations.

appid est bien un identifiant unique de jeu. Arbitrage : nous considérons chaque appid comme un jeu différent bien que le nom puisse être identique

### platform

In [0]:
result = clean_df \
    .select('appid', 'platform') \
    .distinct() \
    .limit(1)
result.show()

+-------+--------+
|  appid|platform|
+-------+--------+
|1001380| windows|
+-------+--------+

In [0]:
from pyspark.sql.functions import explode, split, trim, col
clean_df = clean_df.withColumn("extracted_platform", explode(split(trim(col("platform")), ", ")))
clean_df.show()

+-------+-----------------+--------------------+----------------+--------------------+-----------+-----------------+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+------------------+
|  appid|        developer|               genre|       languages|                name|     owners|        publisher|   short_description|            category|platform|                 tag|language|extracted_genre|extracted_tag|tag_vote_nb|ccu|discount|initialprice|negative|positive|price|release_date|required_age|extracted_platform|
+-------+-----------------+--------------------+----------------+--------------------+-----------+-----------------+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+------------------+
|1000980|        koopa yao|action, adventure...|english, chinese|          kill tiger|0 .. 20,000|        koopa yao|as the excellent ...|single-player, fu...| windows|{"action":22,"adv...| english|         action|       action|         22|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|           windows|
|1000980|        koopa yao|action, adventure...|english, chinese|          kill tiger|0 .. 20,000|        koopa yao|as the excellent ...|single-player, fu...| windows|{"action":22,"adv...| english|         action|       action|         22|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|           windows|
|1000980|        koopa yao|action, adventure...|english, chinese|          kill tiger|0 .. 20,000|        koopa yao|as the excellent ...|single-player, fu...| windows|{"action":22,"adv...| english|         action|       action|         22|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|           windows|
|1000980|        koopa yao|action, adventure...|english, chinese|          kill tiger|0 .. 20,000|        koopa yao|as the excellent ...|single-player, fu...| windows|{"action":22,"adv...| english|         action|    adventure|         20|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|           windows|
|1000980|        koopa yao|action, adventure...|english, chinese|          kill tiger|0 .. 20,000|        koopa yao|as the excellent ...|single-player, fu...| windows|{"action":22,"adv...| english|         action|    adventure|         20|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|           windows|
|1000980|        koopa yao|action, adventure...|english, chinese|          kill tiger|0 .. 20,000|        koopa yao|as the excellent ...|single-player, fu...| windows|{"action":22,"adv...| english|         action|    adventure|         20|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|           windows|
|1000980|        koopa yao|action, adventure...|english, chinese|          kill tiger|0 .. 20,000|        koopa yao|as the excellent ...|single-player, fu...| windows|{"action":22,"adv...| english|         action|        indie|         21|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|           windows|
|1000980|        koopa yao|action, adventure...|english, chinese|          kill tiger|0 .. 20,000|        koopa yao|as the excellent ...|single-player, fu...| windows|{"action":22,"adv...| english|         action|        indie|         21|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|           windows|
|1000980|        koopa yao|action, adventure...|english, chinese|          kill tiger|0 .. 20,000|        koopa yao|as the excellent ...|single-player, fu...| windows|{"action":22,"adv...| english|         action|        indie|         21|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|           windows|
|1003850|dark sun pictures|action, adventure...|         english|dark sun pictures...|0 .. 20,000|dark sun pictures|new free shooting...|single-player, pa...| windows|{"action":21,"act...| english|         action|       action|         21|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|           windows|
|1003850|dark sun pictures|action, adventure...|         english|dark sun pictures...|0 .. 20,000|dark sun pictures|new free shooting...|single-player, pa...| windows|{"action":21,"act...| english|         action|       action|         21|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|           windows|
|1003850|dark sun pictures|action, adventure...|         english|dark sun pictures...|0 .. 20,000|dark sun pictures|new free shooting...|single-player, pa...| windows|{"action":21,"act...| english|         action|       action|         21|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|           windows|
|1003850|dark sun pictures|action, adventure...|         english|dark sun pictures...|0 .. 20,000|dark sun pictures|new free shooting...|single-player, pa...| windows|{"action":21,"act...| english|         action|       action|         21|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|           windows|
|1003850|dark sun pictures|action, adventure...|         english|dark sun pictures...|0 .. 20,000|dark sun pictures|new free shooting...|single-player, pa...| windows|{"action":21,"act...| english|         action|   action rpg|          9|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|           windows|
|1003850|dark sun pictures|action, adventure...|         english|dark sun pictures...|0 .. 20,000|dark sun pictures|new free shooting...|single-player, pa...| windows|{"action":21,"act...| english|         action|   action rpg|          9|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|           windows|
|1003850|dark sun pictures|action, adventure...|         english|dark sun pictures...|0 .. 20,000|dark sun pictures|new free shooting...|single-player, pa...| windows|{"action":21,"act...| english|         action|   action rpg|          9|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|           windows|
|1003850|dark sun pictures|action, adventure...|         english|dark sun pictures...|0 .. 20,000|dark sun pictures|new free shooting...|single-player, pa...| windows|{"action":21,"act...| english|         action|   action rpg|          9|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|           windows|
|1003850|dark sun pictures|action, adventure...|         english|dark sun pictures...|0 .. 20,000|dark sun pictures|new free shooting...|single-player, pa...| windows|{"action":21,"act...| english|         action|    adventure|         19|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|           windows|
|1003850|dark sun pictures|action, adventure...|         english|dark sun pictures...|0 .. 20,000|dark sun pictures|new free shooting...|single-player, pa...| windows|{"action":21,"act...| english|         action|    adventure|         19|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|           windows|
|1003850|dark sun pictures|action, adventure...|         english|dark sun pictures...|0 .. 20,000|dark sun pictures|new free shooting...|single-player, pa...| windows|{"action":21,"act...| english|         action|    adventure|         19|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|           windows|
+-------+-----------------+--------------------+----------------+--------------------+-----------+-----------------+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+------------------+
only showing top 20 rows

In [0]:
from pyspark.sql.functions import count

result = clean_df \
    .select('appid', 'extracted_platform') \
    .dropDuplicates(['appid']) \
    .groupBy('extracted_platform') \
    .agg(count("extracted_platform").alias("games_nb")) \
    .orderBy('games_nb', ascending=False)
result.show(truncate=False)

+------------------+--------+
|extracted_platform|games_nb|
+------------------+--------+
|windows           |41164   |
|linux             |8435    |
|mac               |5957    |
+------------------+--------+

### a) treatments

Let's clean data. First, delete unused spaces with trim method.

In [0]:
from pyspark.sql.functions import trim

clean_df = clean_df.select([trim(col(c)).alias(c) for c in clean_df.columns])
clean_df.show()

+-------+-------+---+--------------------+--------+--------------------+--------------------+------------+--------------------+----------------+--------+----------------+--------+-----+--------------------+------------+------------+--------------------+----+--------------------+--------------------+--------+--------------------+--------+---------------+-----------------+-----------+
|     id|  appid|ccu|           developer|discount|               genre|        header_image|initialprice|           languages|            name|negative|          owners|positive|price|           publisher|release_date|required_age|   short_description|type|             website|            category|platform|                 tag|language|extracted_genre|    extracted_tag|tag_vote_nb|
+-------+-------+---+--------------------+--------+--------------------+--------------------+------------+--------------------+----------------+--------+----------------+--------+-----+--------------------+------------+------------+--------------------+----+--------------------+--------------------+--------+--------------------+--------+---------------+-----------------+-----------+
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|               2D|         60|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|           Action|         74|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|      Destruction|         35|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|      Exploration|         44|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|            Indie|         68|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|           Nature|         32|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|            Ninja|         26|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|          Physics|         48|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|   Pixel Graphics|         57|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|       Platformer|         54|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|           Puzzle|         46|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|Puzzle-Platformer|         39|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|            Retro|         30|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|          Sandbox|         41|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|     Singleplayer|         28|
|1002420|1002420|  0|          Shindenken|       0|       Action, Indie|https://cdn.akama...|         799|   English, Japanese|         Agartha|       3|     0 .. 20,000|       7|  799|    Fruitbat Factory|  2019/03/20|           0|Agartha is an puz...|game|https://fruitbatf...|Single-player, Pa...| windows|{"2D":60,"Action"...| English|         Action|      Underground|         24|
|1003010|1003010|  1|Open World Intera...|       0|Action, Adventure...|https://cdn.akama...|           0|English, French, ...|Clicker Warriors|      70|20,000 .. 50,000|      45|    0|Open World Intera...|  2019/10/22|           0|Get ready to batt...|game|https://www.click...|Single-player, In...| windows|{"Action":30,"Adv...| English|         Action|           Action|         30|
|1003010|1003010|  1|Open World Intera...|       0|Action, Adventure...|https://cdn.akama...|           0|English, French, ...|Clicker Warriors|      70|20,000 .. 50,000|      45|    0|Open World Intera...|  2019/10/22|           0|Get ready to batt...|game|https://www.click...|Single-player, In...| windows|{"Action":30,"Adv...| English|         Action|        Adventure|         31|
|1003010|1003010|  1|Open World Intera...|       0|Action, Adventure...|https://cdn.akama...|           0|English, French, ...|Clicker Warriors|      70|20,000 .. 50,000|      45|    0|Open World Intera...|  2019/10/22|           0|Get ready to batt...|game|https://www.click...|Single-player, In...| windows|{"Action":30,"Adv...| English|         Action|           Casual|         35|
|1003010|1003010|  1|Open World Intera...|       0|Action, Adventure...|https://cdn.akama...|           0|English, French, ...|Clicker Warriors|      70|20,000 .. 50,000|      45|    0|Open World Intera...|  2019/10/22|           0|Get ready to batt...|game|https://www.click...|Single-player, In...| windows|{"Action":30,"Adv...| English|         Action|          Clicker|         32|
+-------+-------+---+--------------------+--------+--------------------+--------------------+------------+--------------------+----------------+--------+----------------+--------+-----+--------------------+------------+------------+--------------------+----+--------------------+--------------------+--------+--------------------+--------+---------------+-----------------+-----------+
only showing top 20 rows

### convert numbers
Then, convert numerical columns positive, negative, ccu, price, initialprice, discount, required_age from string to int.

In [0]:
from pyspark.sql.functions import col

string_cols = ['positive', 'negative', 'ccu', 'price', 'initialprice', 'discount', 'required_age']

clean_df = clean_df.withColumns({c: col(c).cast('int') for c in string_cols})
# clean_df = clean_df.withColumn('ccu', col('ccu').cast('int'))

Then, convert release_date from string to datetime

to_date() ne passe pas en raison de valeurs non conformes. Comptez le nombre de segments (/) pour chaque valeur distincte de 'release_date', afin de voir toutes les structures présentes (3 segments, 2 segments, etc.).

In [0]:
from pyspark.sql.functions import col, split, size

clean_df.select('release_date', size(split(col('release_date'), '/')).alias('partition_nb')) \
    .distinct() \
    .groupBy('partition_nb') \
    .count() \
    .show()

+------------+-----+
|partition_nb|count|
+------------+-----+
|           3| 3937|
|           2|   73|
|           1|    1|
+------------+-----+

Résultat clair: Trois structures existent dans 'release_date':

3 segments (3937 lignes): format complet 'yyyy/M/d'
2 segments (73 lignes): année/mois seulement, ex '2019/01'
1 segment (1 ligne): probablement juste l'année

In [0]:
from pyspark.sql.functions import to_date, col, when, split, size, concat, lit

nb_segments = size(split(col('release_date'), '/'))

clean_df = clean_df.withColumn(
    'release_date',
    when(col('release_date') == '', None)
    .when(nb_segments == 3, to_date(col('release_date'), 'yyyy/M/d'))
    .when(nb_segments == 2, to_date(concat(col('release_date'), lit('/1')), 'yyyy/M/d'))
    .when(nb_segments == 1, to_date(concat(col('release_date'), lit('/1/1')), 'yyyy/M/d'))
    .otherwise(None)
)
clean_df.select('release_date').show(5, truncate=False)

+------------+
|release_date|
+------------+
|2019-01-03  |
|2019-01-03  |
|2022-07-15  |
|2022-07-15  |
|2022-07-15  |
+------------+
only showing top 5 rows

In [0]:
price_cols = [ 'price', 'initialprice']

for c in price_cols:
    clean_df = clean_df.withColumn(c, col(c) / 100)
clean_df.select('price', 'initialprice').show(5)

+-----+------------+
|price|initialprice|
+-----+------------+
|  0.0|         0.0|
|  0.0|         0.0|
| 8.99|        8.99|
| 8.99|        8.99|
| 8.99|        8.99|
+-----+------------+
only showing top 5 rows

Then, deal with latest missing values.

In [0]:
from pyspark.sql.functions import col, when, to_date, lit

for field in clean_df.schema.fields:
    c = field.name
    if field.dataType.simpleString() == 'string':
        clean_df = clean_df.withColumn(c, when(col(c) == '', 'None').otherwise(col(c)))
    elif c == 'release_date':
        clean_df = clean_df.withColumn(c, when(col(c).isNull(), to_date(lit('1900-01-01'), 'yyyy-MM-dd')).otherwise(col(c)))

clean_df.filter(col('release_date') == to_date(lit('1900-01-01'), 'yyyy-MM-dd')).show(1)

+------+------+---+--------------+--------+---------+--------------------+------------+--------------------+--------------------+--------+------------------+--------+-----+--------------+------------+------------+--------------------+----+--------------------+--------------------+------------+--------------------+--------+---------------+-------------+-----------+
|    id| appid|ccu|     developer|discount|    genre|        header_image|initialprice|           languages|                name|negative|            owners|positive|price|     publisher|release_date|required_age|   short_description|type|             website|            category|    platform|                 tag|language|extracted_genre|extracted_tag|tag_vote_nb|
+------+------+---+--------------+--------+---------+--------------------+------------+--------------------+--------------------+--------+------------------+--------+-----+--------------+------------+------------+--------------------+----+--------------------+--------------------+------------+--------------------+--------+---------------+-------------+-----------+
|201830|201830|  2|Telltale Games|       0|Adventure|https://cdn.akama...|         0.0|English, French, ...|Jurassic Park: Th...|     638|200,000 .. 500,000|    1313|  0.0|Telltale Games|  1900-01-01|           0|Experience a bran...|game|http://www.tellta...|Single-player, Pa...|mac, windows|{"Action":38,"Adv...| English|      Adventure|       Action|         38|
+------+------+---+--------------+--------+---------+--------------------+------------+--------------------+--------------------+--------+------------------+--------+-----+--------------+------------+------------+--------------------+----+--------------------+--------------------+------------+--------------------+--------+---------------+-------------+-----------+
only showing top 1 row

In [0]:
result = clean_df.filter(col('release_date').isNull()).count()

Then, lowercase all values.

In [0]:
from pyspark.sql.functions import lower, col

string_cols = [f.name for f in clean_df.schema.fields if f.dataType.simpleString() == 'string']

clean_df = clean_df.select([lower(col(c)).alias(c) for c in string_cols] + [col(c) for c in clean_df.columns if c not in string_cols])
clean_df.show(1)

+-------+-------+----------+-------------+--------------------+-----------------+-------+-----------+----------------+--------------------+----+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
|     id|  appid| developer|        genre|        header_image|        languages|   name|     owners|       publisher|   short_description|type|             website|            category|platform|                 tag|language|extracted_genre|extracted_tag|tag_vote_nb|ccu|discount|initialprice|negative|positive|price|release_date|required_age|
+-------+-------+----------+-------------+--------------------+-----------------+-------+-----------+----------------+--------------------+----+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
|1002420|1002420|shindenken|action, indie|https://cdn.akama...|english, japanese|agartha|0 .. 20,000|fruitbat factory|agartha is an puz...|game|https://fruitbatf...|single-player, pa...| windows|{"2d":60,"action"...| english|         action|           2d|         60|  0|       0|        7.99|       3|       7| 7.99|  2019-03-20|           0|
+-------+-------+----------+-------------+--------------------+-----------------+-------+-----------+----------------+--------------------+----+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
only showing top 1 row

Endly, drop unused columns.

In [0]:
clean_df = clean_df.drop('id', 'type', 'header_image', 'website', 'tag_map')

### b) verify clean_df dataframe

In [0]:
clean_df.createOrReplaceTempView('table') # Refresh the temporary view table in memory
result = spark.sql("select * from table limit 1")
result.show()

+-------+---------+--------------------+----------------+----------+-----------+---------+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
|  appid|developer|               genre|       languages|      name|     owners|publisher|   short_description|            category|platform|                 tag|language|extracted_genre|extracted_tag|tag_vote_nb|ccu|discount|initialprice|negative|positive|price|release_date|required_age|
+-------+---------+--------------------+----------------+----------+-----------+---------+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
|1000980|koopa yao|action, adventure...|english, chinese|kill tiger|0 .. 20,000|koopa yao|as the excellent ...|single-player, fu...| windows|{"action":22,"adv...| english|         action|       action|         22|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|
+-------+---------+--------------------+----------------+----------+-----------+---------+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+

In [0]:
clean_df.printSchema()

root
 |-- appid: string (nullable = true)
 |-- developer: string (nullable = true)
 |-- genre: string (nullable = true)
 |-- languages: string (nullable = true)
 |-- name: string (nullable = true)
 |-- owners: string (nullable = true)
 |-- publisher: string (nullable = true)
 |-- short_description: string (nullable = true)
 |-- category: string (nullable = false)
 |-- platform: string (nullable = false)
 |-- tag: string (nullable = true)
 |-- language: string (nullable = false)
 |-- extracted_genre: string (nullable = false)
 |-- extracted_tag: string (nullable = false)
 |-- tag_vote_nb: string (nullable = true)
 |-- ccu: integer (nullable = true)
 |-- discount: integer (nullable = true)
 |-- initialprice: double (nullable = true)
 |-- negative: integer (nullable = true)
 |-- positive: integer (nullable = true)
 |-- price: double (nullable = true)
 |-- release_date: date (nullable = true)
 |-- required_age: integer (nullable = true)

In [0]:
# Number of elements in dataframe
print(f"Entries number : {clean_df.count()}")

Entries number : 675491

In [0]:
result = spark.sql("select * from table limit(5)")
result.show()

+-------+-----------------+--------------------+----------------+--------------------+-----------+-----------------+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
|  appid|        developer|               genre|       languages|                name|     owners|        publisher|   short_description|            category|platform|                 tag|language|extracted_genre|extracted_tag|tag_vote_nb|ccu|discount|initialprice|negative|positive|price|release_date|required_age|
+-------+-----------------+--------------------+----------------+--------------------+-----------+-----------------+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
|1000980|        koopa yao|action, adventure...|english, chinese|          kill tiger|0 .. 20,000|        koopa yao|as the excellent ...|single-player, fu...| windows|{"action":22,"adv...| english|         action|       action|         22|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|
|1000980|        koopa yao|action, adventure...|english, chinese|          kill tiger|0 .. 20,000|        koopa yao|as the excellent ...|single-player, fu...| windows|{"action":22,"adv...| english|         action|    adventure|         20|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|
|1000980|        koopa yao|action, adventure...|english, chinese|          kill tiger|0 .. 20,000|        koopa yao|as the excellent ...|single-player, fu...| windows|{"action":22,"adv...| english|         action|        indie|         21|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|
|1003850|dark sun pictures|action, adventure...|         english|dark sun pictures...|0 .. 20,000|dark sun pictures|new free shooting...|single-player, pa...| windows|{"action":21,"act...| english|         action|       action|         21|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
|1003850|dark sun pictures|action, adventure...|         english|dark sun pictures...|0 .. 20,000|dark sun pictures|new free shooting...|single-player, pa...| windows|{"action":21,"act...| english|         action|   action rpg|          9|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
+-------+-----------------+--------------------+----------------+--------------------+-----------+-----------------+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+

In [0]:
clean_df.select('name', 'release_date', 'developer', 'publisher', 'owners', 'ccu').sample(fraction=0.0001).show(truncate=False)

+------------------------------------------+------------+----------------------------+-------------------------------------------+--------------------+----+
|name                                      |release_date|developer                   |publisher                                  |owners              |ccu |
+------------------------------------------+------------+----------------------------+-------------------------------------------+--------------------+----+
|mr.mine                                   |2020-09-30  |austin oblouk               |playsaurus                                 |500,000 .. 1,000,000|1449|
|коты воители                              |2021-05-21  |ioaan prepodobniy           |piece of voxel                             |0 .. 20,000         |0   |
|rambo the video game + baker team dlc     |2014-02-21  |teyon                       |reef entertainment                         |0 .. 20,000         |1   |
|trivia vault basketball trivia            |2018-03-03  |ripknot systems             |ripknot systems                            |0 .. 20,000         |0   |
|killer: infected one of us                |2021-02-01  |dreamteamgames              |dreamteamgames                             |0 .. 20,000         |0   |
|meditation 2 ~ wisdom and christian art   |2020-05-24  |kooly from paris            |kooly from paris                           |0 .. 20,000         |0   |
|the rainbow world                         |2019-12-19  |gobigd                      |gobigd                                     |0 .. 20,000         |0   |
|seed of life                              |2021-08-11  |madlight                    |leonardo interactive                       |20,000 .. 50,000    |0   |
|pick, shoot, repeat!                      |2020-01-21  |wa tran                     |unknown magic                              |0 .. 20,000         |0   |
|malice & greed                            |2021-03-22  |xendra                      |xendra                                     |0 .. 20,000         |0   |
|boss hunter                               |2022-07-08  |ck studio                   |ck studio                                  |0 .. 20,000         |0   |
|endless knight                            |2019-12-31  |will sykes games            |will sykes games                           |0 .. 20,000         |0   |
|no more heroes 3                          |2022-10-11  |grasshopper manufacture inc.|xseed games, marvelous usa, inc., marvelous|0 .. 20,000         |19  |
|apollo 11 vr hd                           |2018-11-23  |immersive vr education ltd. |immersive vr education ltd.                |20,000 .. 50,000    |1   |
|this is my dungeon                        |2020-11-15  |amagumo horn                |amagumo horn                               |0 .. 20,000         |0   |
|the hex                                   |2018-10-16  |daniel mullins games        |daniel mullins games                       |50,000 .. 100,000   |34  |
|silicon dreams  |  cyberpunk interrogation|2021-04-20  |james patton, clockwork bird|clockwork bird                             |20,000 .. 50,000    |2   |
|7 wonders of the ancient world            |2014-02-18  |mumbojumbo                  |mumbojumbo                                 |50,000 .. 100,000   |7   |
|generals & rulers                         |2019-05-31  |hamsters gaming             |hamsters gaming                            |20,000 .. 50,000    |0   |
|tnn motorsports hardcore tr               |2015-08-10  |asc games                   |console classics                           |0 .. 20,000         |0   |
+------------------------------------------+------------+----------------------------+-------------------------------------------+--------------------+----+
only showing top 20 rows

Verify missing values.

In [0]:
from pyspark.sql.functions import col, sum as spark_sum

all_cols = clean_df.columns
string_cols = [f.name for f in clean_df.schema.fields if f.dataType.simpleString() == 'string']

clean_df.select([spark_sum((col(c).isNull() | ((col(c) == '') if c in string_cols else False)).cast('int')).alias(c) for c in all_cols])

clean_df.show()

+-------+--------------------+--------------------+--------------------+--------------------+-----------------+--------------------+--------------------+--------------------+------------+--------------------+--------+---------------+--------------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
|  appid|           developer|               genre|           languages|                name|           owners|           publisher|   short_description|            category|    platform|                 tag|language|extracted_genre|       extracted_tag|tag_vote_nb|ccu|discount|initialprice|negative|positive|price|release_date|required_age|
+-------+--------------------+--------------------+--------------------+--------------------+-----------------+--------------------+--------------------+--------------------+------------+--------------------+--------+---------------+--------------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
|1000980|           koopa yao|action, adventure...|    english, chinese|          kill tiger|      0 .. 20,000|           koopa yao|as the excellent ...|single-player, fu...|     windows|{"action":22,"adv...| english|         action|              action|         22|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|
|1000980|           koopa yao|action, adventure...|    english, chinese|          kill tiger|      0 .. 20,000|           koopa yao|as the excellent ...|single-player, fu...|     windows|{"action":22,"adv...| english|         action|           adventure|         20|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|
|1000980|           koopa yao|action, adventure...|    english, chinese|          kill tiger|      0 .. 20,000|           koopa yao|as the excellent ...|single-player, fu...|     windows|{"action":22,"adv...| english|         action|               indie|         21|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|
|1003850|   dark sun pictures|action, adventure...|             english|dark sun pictures...|      0 .. 20,000|   dark sun pictures|new free shooting...|single-player, pa...|     windows|{"action":21,"act...| english|         action|              action|         21|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
|1003850|   dark sun pictures|action, adventure...|             english|dark sun pictures...|      0 .. 20,000|   dark sun pictures|new free shooting...|single-player, pa...|     windows|{"action":21,"act...| english|         action|          action rpg|          9|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
|1003850|   dark sun pictures|action, adventure...|             english|dark sun pictures...|      0 .. 20,000|   dark sun pictures|new free shooting...|single-player, pa...|     windows|{"action":21,"act...| english|         action|           adventure|         19|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
|1003850|   dark sun pictures|action, adventure...|             english|dark sun pictures...|      0 .. 20,000|   dark sun pictures|new free shooting...|single-player, pa...|     windows|{"action":21,"act...| english|         action|massively multipl...|         10|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
|1003850|   dark sun pictures|action, adventure...|             english|dark sun pictures...|      0 .. 20,000|   dark sun pictures|new free shooting...|single-player, pa...|     windows|{"action":21,"act...| english|         action|                 rpg|         20|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
|1003850|   dark sun pictures|action, adventure...|             english|dark sun pictures...|      0 .. 20,000|   dark sun pictures|new free shooting...|single-player, pa...|     windows|{"action":21,"act...| english|         action|            strategy|         19|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
|1005000|           workroom7|casual, simulatio...|english, french, ...|argonauts agency:...|      0 .. 20,000|              8floor|argonauts agency:...|single-player, st...|mac, windows|{"casual":22,"sim...| english|         casual|              casual|         22|  3|       0|        5.99|       2|      35| 5.99|  2019-02-22|           0|
|1005000|           workroom7|casual, simulatio...|english, french, ...|argonauts agency:...|      0 .. 20,000|              8floor|argonauts agency:...|single-player, st...|mac, windows|{"casual":22,"sim...| english|         casual|          simulation|         20|  3|       0|        5.99|       2|      35| 5.99|  2019-02-22|           0|
|1005000|           workroom7|casual, simulatio...|english, french, ...|argonauts agency:...|      0 .. 20,000|              8floor|argonauts agency:...|single-player, st...|mac, windows|{"casual":22,"sim...| english|         casual|            strategy|         20|  3|       0|        5.99|       2|      35| 5.99|  2019-02-22|           0|
|1005000|           workroom7|casual, simulatio...|english, french, ...|argonauts agency:...|      0 .. 20,000|              8floor|argonauts agency:...|single-player, st...|mac, windows|{"casual":22,"sim...| english|         casual|     time management|          6|  3|       0|        5.99|       2|      35| 5.99|  2019-02-22|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|                  2d|        600|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|              action|        586|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|              arcade|        560|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|         bullet hell|        633|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|             cartoon|        583|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|            cartoony|        609|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|              comedy|        607|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
+-------+--------------------+--------------------+--------------------+--------------------+-----------------+--------------------+--------------------+--------------------+------------+--------------------+--------+---------------+--------------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
only showing top 20 rows

In [0]:
result = spark.sql("select * from table where developer = 'none' or genre = 'none' or languages = 'none' or publisher = 'none' or short_description = 'none' or category = 'none'")
result.limit(1).show()

+-------+---------+--------------------+---------+----------+-----------+--------------+--------------------+--------+------------+--------------------+--------+--------------------+--------------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
|  appid|developer|               genre|languages|      name|     owners|     publisher|   short_description|category|    platform|                 tag|language|     extracted_genre|       extracted_tag|tag_vote_nb|ccu|discount|initialprice|negative|positive|price|release_date|required_age|
+-------+---------+--------------------+---------+----------+-----------+--------------+--------------------+--------+------------+--------------------+--------+--------------------+--------------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
|1091220|mark imel|animation & model...|  english|wavelength|0 .. 20,000|wavelength llc|do you like music...|    none|mac, windows|{"animation & mod...| english|animation & modeling|animation & modeling|         22|  0|       0|        1.99|       3|       0| 1.99|  2019-07-10|           0|
+-------+---------+--------------------+---------+----------+-----------+--------------+--------------------+--------+------------+--------------------+--------+--------------------+--------------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+

In [0]:
result = clean_df \
    .filter(col('release_date') == to_date(lit('1900-01-01'), 'yyyy-MM-dd'))
result.limit(1).show()

+------+--------------------+-----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
| appid|           developer|      genre|           languages|                name|              owners|           publisher|   short_description|            category|platform|                 tag|language|extracted_genre|extracted_tag|tag_vote_nb|ccu|discount|initialprice|negative|positive|price|release_date|required_age|
+------+--------------------+-----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
|102500|big huge games, 3...|action, rpg|english, french, ...|kingdoms of amalu...|2,000,000 .. 5,00...|38 studios, elect...|the minds of new ...|single-player, pa...| windows|{"action":426,"ac...| english|         action|       action|        426| 51|       0|         0.0|    1492|   11184|  0.0|  1900-01-01|          15|
+------+--------------------+-----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+

In [0]:

clean_df.describe().toPandas()

  summary               appid  ...               price        required_age
0   count              675491  ...              675491              675491
1    mean  1124553.3754513382  ...    8.58866704367016  0.2294538343219969
2  stddev   543840.8404732038  ...  10.689922628840996  1.9065147496365704
3     min                  10  ...                 0.0                   0
4     max              999990  ...               999.0                  21

[5 rows x 23 columns]

In [0]:
result = clean_df \
    .filter(col('release_date') != to_date(lit('1900-01-01'), 'yyyy-MM-dd')) \
    .select( \
        F.min("release_date").alias("min_release_date"),
        F.max("release_date").alias("max_release_date"))
result.show()

+----------------+----------------+
|min_release_date|max_release_date|
+----------------+----------------+
|      1997-06-30|      2022-11-11|
+----------------+----------------+

# TO DO Nico graph time series

## 3. Analysis at the "macro" level

### publisher

#### Which publisher has released the most games on Steam?

In [0]:
from pyspark.sql.functions import count, desc

publisher_leader = clean_df \
    .select(clean_df['publisher'],'appid', 'release_date') \
    .dropDuplicates(['appid']) \
    .groupBy('publisher') \
    .agg(
        count('appid').alias('game_nb'),
        count('release_date').alias('release_nb')
        ) \
    .orderBy(desc('release_nb')) \
    .limit(1)
result.show()

+----------------+----------------+
|min_release_date|max_release_date|
+----------------+----------------+
|      1997-06-30|      2022-11-11|
+----------------+----------------+

#### What is Ubisoft's position as publisher ?

In [0]:
from pyspark.sql.functions import count, desc

publisher_rank = clean_df \
    .select(clean_df['publisher'],'appid', 'release_date') \
    .dropDuplicates(['appid']) \
    .groupBy('publisher') \
    .agg( \
        count('appid').alias('game_nb'), \
        count('release_date').alias('release_nb')) \
    .withColumn('rank', row_number().over(Window
    .orderBy(desc('release_nb')))) \
    .filter(clean_df.publisher.isin(['big fish games', 'ubisoft','valve']))
publisher_rank.show()

/databricks/python/lib/python3.12/site-packages/pyspark/sql/connect/expressions.py:1163: UserWarning: WARN WindowExpression: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
  warnings.warn(

+--------------+-------+----------+----+
|     publisher|game_nb|release_nb|rank|
+--------------+-------+----------+----+
|big fish games|    423|       423|   1|
|       ubisoft|    127|       127|  10|
|         valve|     35|        35| 101|
+--------------+-------+----------+----+

### name

#### How many games on steam ?

In [0]:
games_nb = clean_df \
    .select('appid') \
    .distinct() \
    .count()

labels_nb = clean_df \
    .select('name').distinct() \
    .count()
print(f"Games number : {games_nb}\nLabels number = {labels_nb}")

Games number : 55556
Labels number = 55201

### developer

#### How many developers indicated on steam ?

In [0]:
developper_nb = clean_df \
    .select(clean_df['developer']) \
    .distinct() \
    .count()
print(f"Developer number : {developper_nb}")

Developer number : 34474

#### Which developer most contribute to games on steam ?

In [0]:
result = clean_df \
    .select(clean_df['developer'],'appid') \
    .distinct() \
    .groupBy('developer') \
    .agg(countDistinct('appid').alias('game_nb')) \
    .orderBy(desc('game_nb')) \
    .limit(5)
result.show(truncate=False)

+------------------------+-------+
|developer               |game_nb|
+------------------------+-------+
|choice of games         |140    |
|none                    |131    |
|creobit                 |122    |
|laush dmitriy sergeevich|106    |
|sokpop collective       |98     |
+------------------------+-------+

### positive / negative / ccu

#### What are the best rated games?

In [0]:
result = clean_df \
    .select(clean_df['appid'],'name', 'publisher','positive', 'negative') \
    .dropDuplicates(['appid']) \
    .orderBy('positive', ascending=False) \
    .limit(5)
result.show(truncate=False)

+------+--------------------------------+--------------+--------+--------+
|appid |name                            |publisher     |positive|negative|
+------+--------------------------------+--------------+--------+--------+
|730   |counter-strike: global offensive|valve         |5943345 |787093  |
|570   |dota 2                          |valve         |1534895 |317916  |
|271590|grand theft auto v              |rockstar games|1229265 |213379  |
|578080|pubg: battlegrounds             |krafton, inc. |1185361 |908515  |
|105600|terraria                        |re-logic      |1014711 |22380   |
+------+--------------------------------+--------------+--------+--------+

Users evaluate a game by like or dislike.
In 2022, in absolute value, games with the best positive advices number are :
- first kingdom rush from ironhide with 9998 positive advices. 
- 2d, crysis from electronic arts from electronic arts with 9996 positive advices. 
- 3d neon chrome from 10 tons ltd and baseball 20 from out of the park developements exaequo with 999 positive advices.

In [0]:
from pyspark.sql.functions import col, try_divide

result = clean_df \
    .select(clean_df['appid'],'name', 'publisher','positive', 'negative') \
    .dropDuplicates(['appid']) \
    .groupBy('appid',  'name', 'publisher') \
    .agg( \
        F.sum('positive').alias('positive_sum'), \
        F.sum('negative').alias('negative_sum') \
        ) \
    .filter((col('positive_sum') > 0) & (col('negative_sum') > 0)) \
    .withColumn('ratio', col('positive_sum') /  col('negative_sum')) \
    .orderBy(desc('positive_sum')) \
    .limit(5)
result.show(truncate=False)

+------+--------------------------------+--------------+------------+------------+------------------+
|appid |name                            |publisher     |positive_sum|negative_sum|ratio             |
+------+--------------------------------+--------------+------------+------------+------------------+
|730   |counter-strike: global offensive|valve         |5943345     |787093      |7.551007314256384 |
|570   |dota 2                          |valve         |1534895     |317916      |4.82798915436782  |
|271590|grand theft auto v              |rockstar games|1229265     |213379      |5.760946484893077 |
|578080|pubg: battlegrounds             |krafton, inc. |1185361     |908515      |1.3047236424274777|
|105600|terraria                        |re-logic      |1014711     |22380       |45.34008042895442 |
+------+--------------------------------+--------------+------------+------------+------------------+

In 2022, in relational value, counter-strike: global offensive from valve has a better ratio with 7,55. 2d dota 2 with 4,82. 3d, grand theft auto v

What are worst rated games ?

In [0]:
from pyspark.sql.functions import col, try_divide

result = clean_df \
    .select(clean_df['appid'],'name', 'publisher','positive', 'negative') \
    .dropDuplicates(['appid']) \
    .groupBy('appid',  'name') \
    .agg( \
        F.sum('positive').alias('positive_sum'), \
        F.sum('negative').alias('negative_sum') \
        ) \
    .filter((col('positive_sum') > 0) & (col('negative_sum') > 0)) \
    .withColumn('ratio', col('positive_sum') /  col('negative_sum')) \
    .orderBy(desc('positive_sum')) \
    .limit(10)
result.show(truncate=False)

+------+--------------------------------+------------+------------+------------------+
|appid |name                            |positive_sum|negative_sum|ratio             |
+------+--------------------------------+------------+------------+------------------+
|730   |counter-strike: global offensive|5943345     |787093      |7.551007314256384 |
|570   |dota 2                          |1534895     |317916      |4.82798915436782  |
|271590|grand theft auto v              |1229265     |213379      |5.760946484893077 |
|578080|pubg: battlegrounds             |1185361     |908515      |1.3047236424274777|
|105600|terraria                        |1014711     |22380       |45.34008042895442 |
|359550|tom clancy's rainbow six siege  |942910      |143247      |6.582406612354884 |
|4000  |garry's mod                     |861240      |29998       |28.709913994266284|
|440   |team fortress 2                 |846407      |57423       |14.739860334709089|
|252490|rust                            |732513      |112154      |6.5313140859889085|
|550   |left 4 dead 2                   |643836      |16828       |38.25980508676016 |
+------+--------------------------------+------------+------------+------------------+

In [0]:
result = clean_df \
    .select(clean_df['appid'],'name', 'publisher','positive', 'negative') \
    .dropDuplicates(['appid']) \
    .orderBy('negative', ascending=True) \
    .limit(20)
result.show(truncate=False)

+-------+-----------------------------------------------------+-------------------+--------+--------+
|appid  |name                                                 |publisher          |positive|negative|
+-------+-----------------------------------------------------+-------------------+--------+--------+
|2072140|epic astro story                                     |kairosoft co.,ltd  |8       |0       |
|1475350|breath                                               |herbherth          |9       |0       |
|1530240|toodles & toddlers                                   |uglybaby games     |6       |0       |
|1297030|sycamore                                             |[untitleddev]      |2       |0       |
|1721480|haunted game                                         |marcus ferron games|3       |0       |
|1505570|labyrinth 3                                          |saarse             |3       |0       |
|688050 |boidwatch                                            |longship llc       |1       |0       |
|1378250|px art                                               |xiangsu tang       |2       |0       |
|2082290|monkey milk                                          |poala productions  |3       |0       |
|1727910|hope trigger                                         |adisa game studio  |3       |0       |
|1741670|hedgie simulator                                     |eltar              |4       |0       |
|1124380|one gun 2: stickman                                  |erow.dev           |2       |0       |
|2087940|non-stop raiders                                     |next in game       |15      |0       |
|387780 |professor teaches access 2013 & 365                  |individual software|1       |0       |
|1793680|the holy chalice                                     |austin mcdaniel    |3       |0       |
|1618510|poulet poulet                                        |r/t games          |5       |0       |
|2083680|pegsoli+                                             |acerola software   |1       |0       |
|1089520|nigel: the minuscule adventure                       |nigel productions  |1       |0       |
|2138920|budgie genetics simulator                            |niki cilliers      |1       |0       |
|568160 |mayan prophecies: ship of spirits collector's edition|big fish games     |8       |0       |
+-------+-----------------------------------------------------+-------------------+--------+--------+

In [0]:
from pyspark.sql.functions import col, try_divide

result = clean_df \
    .select(clean_df['appid'],'name', 'publisher','positive', 'negative') \
    .dropDuplicates(['appid']) \
    .groupBy('appid',  'name') \
    .agg( \
        F.sum('positive').alias('positive_sum'), \
        F.sum('negative').alias('negative_sum') \
        ) \
    .filter((col('positive_sum') > 0) & (col('negative_sum') > 0)) \
    .withColumn('ratio', col('positive_sum') /  col('negative_sum')) \
    .orderBy(desc('positive_sum')) \
    .limit(10)
result.show(truncate=False)

+------+--------------------------------+------------+------------+------------------+
|appid |name                            |positive_sum|negative_sum|ratio             |
+------+--------------------------------+------------+------------+------------------+
|730   |counter-strike: global offensive|5943345     |787093      |7.551007314256384 |
|570   |dota 2                          |1534895     |317916      |4.82798915436782  |
|271590|grand theft auto v              |1229265     |213379      |5.760946484893077 |
|578080|pubg: battlegrounds             |1185361     |908515      |1.3047236424274777|
|105600|terraria                        |1014711     |22380       |45.34008042895442 |
|359550|tom clancy's rainbow six siege  |942910      |143247      |6.582406612354884 |
|4000  |garry's mod                     |861240      |29998       |28.709913994266284|
|440   |team fortress 2                 |846407      |57423       |14.739860334709089|
|252490|rust                            |732513      |112154      |6.5313140859889085|
|550   |left 4 dead 2                   |643836      |16828       |38.25980508676016 |
+------+--------------------------------+------------+------------+------------------+

In absolute value, Counter-Strike: Global Offensive has more positive advices (65,4M). Yet Terraria has a better ratio : 45,34 positive advices for 1 negative advice against 7,5 on Counter-Strike. Then, Terraria is proportianaly more liked.

#### Quels sont les jeux les plus utilisés au moment où le dataset a été construit ?

In [0]:
from pyspark.sql.functions import col, try_divide

result = clean_df \
    .select('appid', 'name', 'publisher', 'ccu') \
    .distinct() \
    .orderBy(desc('ccu'))
result.show(truncate=False)

+-------+--------------------------------+-----------------------+------+
|appid  |name                            |publisher              |ccu   |
+-------+--------------------------------+-----------------------+------+
|730    |counter-strike: global offensive|valve                  |874053|
|570    |dota 2                          |valve                  |852995|
|578080 |pubg: battlegrounds             |krafton, inc.          |339287|
|1172470|apex legends                    |electronic arts        |314468|
|1599340|lost ark                        |amazon games           |273088|
|1938090|call of duty: modern warfare ii |activision             |206441|
|271590 |grand theft auto v              |rockstar games         |140671|
|1063730|new world                       |amazon games           |127379|
|252490 |rust                            |facepunch studios      |121146|
|1203220|naraka: bladepoint              |netease games global   |116729|
|431960 |wallpaper engine                |wallpaper engine team  |109428|
|440    |team fortress 2                 |valve                  |108900|
|552500 |warhammer: vermintide 2         |fatshark               |85953 |
|236390 |war thunder                     |gaijin distribution kft|71685 |
|346110 |ark: survival evolved           |studio wildcard        |70578 |
|304930 |unturned                        |smartly dressed games  |59366 |
|105600 |terraria                        |re-logic               |58984 |
|1085660|destiny 2                       |bungie                 |57116 |
|1222670|the sims 4                      |electronic arts        |55459 |
|221100 |dayz                            |bohemia interactive    |53885 |
+-------+--------------------------------+-----------------------+------+
only showing top 20 rows

#### Et quels sont les jeux les plus achetés ?

In [0]:
from pyspark.sql.functions import col, try_divide

result = clean_df \
    .select('appid', 'owners') \
    .distinct() \
    .groupBy('owners') \
    .agg( \
        F.count('owners').alias('owners_sum')) \
    .orderBy('owners_sum')
result.show(truncate=False)

+--------------------------+----------+
|owners                    |owners_sum|
+--------------------------+----------+
|200,000,000 .. 500,000,000|1         |
|50,000,000 .. 100,000,000 |4         |
|20,000,000 .. 50,000,000  |21        |
|10,000,000 .. 20,000,000  |41        |
|5,000,000 .. 10,000,000   |97        |
|2,000,000 .. 5,000,000    |335       |
|1,000,000 .. 2,000,000    |526       |
|500,000 .. 1,000,000      |933       |
|200,000 .. 500,000        |2162      |
|100,000 .. 200,000        |2518      |
|50,000 .. 100,000         |3695      |
|20,000 .. 50,000          |7285      |
|0 .. 20,000               |37938     |
+--------------------------+----------+

In [0]:
from pyspark.sql.functions import col, regexp_replace, split, desc

result = clean_df \
    .select('appid', 'name', 'publisher', 'owners', 'release_date') \
    .distinct() \
    .withColumn('owners_num', regexp_replace(split(col('owners'), ' ')[0], ',', '').cast('long')) \
    .orderBy(desc('owners_num')) \
    .drop('owners_num') \
    .limit(10)
result.show(truncate=False)

+-------+--------------------------------+---------------------------------------------+--------------------------+------------+
|appid  |name                            |publisher                                    |owners                    |release_date|
+-------+--------------------------------+---------------------------------------------+--------------------------+------------+
|570    |dota 2                          |valve                                        |200,000,000 .. 500,000,000|2013-07-09  |
|440    |team fortress 2                 |valve                                        |50,000,000 .. 100,000,000 |2007-10-10  |
|578080 |pubg: battlegrounds             |krafton, inc.                                |50,000,000 .. 100,000,000 |2017-12-21  |
|730    |counter-strike: global offensive|valve                                        |50,000,000 .. 100,000,000 |2012-08-21  |
|1063730|new world                       |amazon games                                 |50,000,000 .. 100,000,000 |2021-09-28  |
|1085660|destiny 2                       |bungie                                       |20,000,000 .. 50,000,000  |2019-10-01  |
|1245620|elden ring                      |fromsoftware inc., bandai namco entertainment|20,000,000 .. 50,000,000  |2022-02-24  |
|105600 |terraria                        |re-logic                                     |20,000,000 .. 50,000,000  |2011-05-16  |
|359550 |tom clancy's rainbow six siege  |ubisoft                                      |20,000,000 .. 50,000,000  |2015-12-01  |
|1097150|fall guys: ultimate knockout    |ravenscourt                                  |20,000,000 .. 50,000,000  |2020-08-03  |
+-------+--------------------------------+---------------------------------------------+--------------------------+------------+

Les jeux les plus plébiscités kingdom rush, crysis et neon chrome ne sont pas forcément les plus utilisés ou les plus achetés :
- dota 2 est le jeu le plus vendu avec 200 000 000 à 500 000 000 utilisateurs. 
- counter-strike: global offensive est plus utilisé avec 874053 utilisateursmais n'a que 50 000 000 à 100 000 000 d'acheteurs. 
Nous constatons Avec la release_date, on s'aperçoit que dota 2 et conter-strike global offensive sont anciens.

In [0]:
result = clean_df.groupBy('owners').agg(F.count('*').alias('count')).orderBy(desc('count'))
result.show(truncate=False)

+--------------------------+------+
|owners                    |count |
+--------------------------+------+
|0 .. 20,000               |427363|
|20,000 .. 50,000          |90967 |
|50,000 .. 100,000         |49817 |
|100,000 .. 200,000        |36601 |
|200,000 .. 500,000        |34016 |
|500,000 .. 1,000,000      |16781 |
|1,000,000 .. 2,000,000    |10056 |
|2,000,000 .. 5,000,000    |6644  |
|5,000,000 .. 10,000,000   |1911  |
|10,000,000 .. 20,000,000  |815   |
|20,000,000 .. 50,000,000  |420   |
|50,000,000 .. 100,000,000 |80    |
|200,000,000 .. 500,000,000|20    |
+--------------------------+------+

Are there years with more releases? Were there more or fewer game releases during the Covid, for example?

In [0]:
from pyspark.sql.functions import (
    col, year, try_to_date, count, countDistinct
)

result = (clean_df \
    .select("name", "release_date") \
    .distinct() \
    .withColumn( \
        "release_year", \
        year(try_to_date(col("release_date"), "yyyy/M/d")) \
    ) \
    .filter(col("release_year").isNotNull()) \
    .groupBy("release_year") \
    .agg( \
        count("*").alias("release_nb"), \
        countDistinct("name").alias("name_nb") \
    ) \
    .filter((col('release_nb') > 0) & (col('name_nb') > 0)) \
    .withColumn('ratio', col('release_nb') /  col('name_nb')) \
    .orderBy(desc("release_year")) \
)

result.show()

+------------+----------+-------+------------------+
|release_year|release_nb|name_nb|             ratio|
+------------+----------+-------+------------------+
|        2022|      7454|   7446|1.0010744023636853|
|        2021|      8823|   8809| 1.001589283687138|
|        2020|      8304|   8292|1.0014471780028944|
|        2019|      6940|   6936|1.0005767012687428|
|        2018|      7610|   7598|1.0015793629902605|
|        2017|      5987|   5982| 1.000835840855901|
|        2016|      4182|   4181|1.0002391772303276|
|        2015|      2574|   2573|1.0003886513797124|
|        2014|      1557|   1557|               1.0|
|        2013|       471|    471|               1.0|
|        2012|       345|    345|               1.0|
|        2011|       267|    267|               1.0|
|        2010|       288|    288|               1.0|
|        2009|       309|    309|               1.0|
|        2008|       159|    159|               1.0|
|        2007|        98|     98|               1.0|
|        2006|        61|     61|               1.0|
|        2005|         6|      6|               1.0|
|        2004|         6|      6|               1.0|
|        2003|         3|      3|               1.0|
+------------+----------+-------+------------------+
only showing top 20 rows

Yes. There are years with more releases. 
- In absolute value, 2014 to 2022. There are more releases after the covid's year in 2021 with 8676. 
- In prortional value, 2015 to 2022. Releases become higher than games since 2015. Yet, releases are higher on 2020, the covid's year with 1.0011 releases for one game.  
We observe that Covid accentuated the trend which returns then at normal pace in 2022 with 7401 and 1.00094.

In [0]:
result = spark.sql("SELECT * FROM table") # filters elements from my_table where position
# show everything
result.show()

+-------+--------------------+--------------------+--------------------+--------------------+-----------------+--------------------+--------------------+--------------------+------------+--------------------+--------+---------------+--------------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
|  appid|           developer|               genre|           languages|                name|           owners|           publisher|   short_description|            category|    platform|                 tag|language|extracted_genre|       extracted_tag|tag_vote_nb|ccu|discount|initialprice|negative|positive|price|release_date|required_age|
+-------+--------------------+--------------------+--------------------+--------------------+-----------------+--------------------+--------------------+--------------------+------------+--------------------+--------+---------------+--------------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
|1000980|           koopa yao|action, adventure...|    english, chinese|          kill tiger|      0 .. 20,000|           koopa yao|as the excellent ...|single-player, fu...|     windows|{"action":22,"adv...| english|         action|              action|         22|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|
|1000980|           koopa yao|action, adventure...|    english, chinese|          kill tiger|      0 .. 20,000|           koopa yao|as the excellent ...|single-player, fu...|     windows|{"action":22,"adv...| english|         action|           adventure|         20|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|
|1000980|           koopa yao|action, adventure...|    english, chinese|          kill tiger|      0 .. 20,000|           koopa yao|as the excellent ...|single-player, fu...|     windows|{"action":22,"adv...| english|         action|               indie|         21|  0|       0|        6.99|       0|       1| 6.99|  2019-03-01|           0|
|1003850|   dark sun pictures|action, adventure...|             english|dark sun pictures...|      0 .. 20,000|   dark sun pictures|new free shooting...|single-player, pa...|     windows|{"action":21,"act...| english|         action|              action|         21|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
|1003850|   dark sun pictures|action, adventure...|             english|dark sun pictures...|      0 .. 20,000|   dark sun pictures|new free shooting...|single-player, pa...|     windows|{"action":21,"act...| english|         action|          action rpg|          9|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
|1003850|   dark sun pictures|action, adventure...|             english|dark sun pictures...|      0 .. 20,000|   dark sun pictures|new free shooting...|single-player, pa...|     windows|{"action":21,"act...| english|         action|           adventure|         19|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
|1003850|   dark sun pictures|action, adventure...|             english|dark sun pictures...|      0 .. 20,000|   dark sun pictures|new free shooting...|single-player, pa...|     windows|{"action":21,"act...| english|         action|massively multipl...|         10|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
|1003850|   dark sun pictures|action, adventure...|             english|dark sun pictures...|      0 .. 20,000|   dark sun pictures|new free shooting...|single-player, pa...|     windows|{"action":21,"act...| english|         action|                 rpg|         20|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
|1003850|   dark sun pictures|action, adventure...|             english|dark sun pictures...|      0 .. 20,000|   dark sun pictures|new free shooting...|single-player, pa...|     windows|{"action":21,"act...| english|         action|            strategy|         19|  0|       0|        0.99|       1|       1| 0.99|  2019-01-25|           0|
|1005000|           workroom7|casual, simulatio...|english, french, ...|argonauts agency:...|      0 .. 20,000|              8floor|argonauts agency:...|single-player, st...|mac, windows|{"casual":22,"sim...| english|         casual|              casual|         22|  3|       0|        5.99|       2|      35| 5.99|  2019-02-22|           0|
|1005000|           workroom7|casual, simulatio...|english, french, ...|argonauts agency:...|      0 .. 20,000|              8floor|argonauts agency:...|single-player, st...|mac, windows|{"casual":22,"sim...| english|         casual|          simulation|         20|  3|       0|        5.99|       2|      35| 5.99|  2019-02-22|           0|
|1005000|           workroom7|casual, simulatio...|english, french, ...|argonauts agency:...|      0 .. 20,000|              8floor|argonauts agency:...|single-player, st...|mac, windows|{"casual":22,"sim...| english|         casual|            strategy|         20|  3|       0|        5.99|       2|      35| 5.99|  2019-02-22|           0|
|1005000|           workroom7|casual, simulatio...|english, french, ...|argonauts agency:...|      0 .. 20,000|              8floor|argonauts agency:...|single-player, st...|mac, windows|{"casual":22,"sim...| english|         casual|     time management|          6|  3|       0|        5.99|       2|      35| 5.99|  2019-02-22|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|                  2d|        600|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|              action|        586|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|              arcade|        560|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|         bullet hell|        633|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|             cartoon|        583|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|            cartoony|        609|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
|1005410|wide right intera...|       action, indie|english, russian,...|      freedom finger|50,000 .. 100,000|wide right intera...|freedom finger is...|single-player, st...|mac, windows|{"2d":600,"action...| english|         action|              comedy|        607|  0|       0|        7.99|       8|     112| 7.99|  2019-09-27|           0|
+-------+--------------------+--------------------+--------------------+--------------------+-----------------+--------------------+--------------------+--------------------+------------+--------------------+--------+---------------+--------------------+-----------+---+--------+------------+--------+--------+-----+------------+------------+
only showing top 20 rows

# TO DO Nico graph avec quartiles ? time series ?

### prices

In [0]:
### Prices

#### How are the prices distributed?

In [0]:
result = clean_df \
    .select(clean_df['name'], 'price') \
    .orderBy('price')
display(result)

Databricks visualization. Run in Databricks to view.

In [0]:
result = clean_df \
    .groupBy('price') \
    .agg( \
        F.count('price').alias('game_nb')) \
    .orderBy('price')
display(result)

price,game_nb
0.0,81061
0.28,186
0.29,173
0.3,30
0.31,43
0.37,215
0.38,121
0.39,101
0.41,98
0.44,20
0.45,11
0.49,3854
0.5,327
0.51,360
0.53,30
0.54,204
0.56,17
0.57,30
0.59,1298
0.61,17
0.62,6
0.64,35
0.65,6
0.67,19
0.69,546
0.71,9
0.74,334
0.75,40
0.76,17
0.77,42
0.79,620
0.8,14
0.81,37
0.83,40
0.84,61
0.89,321
0.9,303
0.91,53
0.95,14
0.98,8
0.99,54205
1.0,170
1.03,43
1.04,105
1.07,20
1.09,56
1.11,5
1.19,614
1.23,27
1.24,287
1.29,114
1.32,5
1.33,15
1.34,42
1.35,7
1.36,14
1.39,218
1.4,3
1.42,14
1.45,3
1.47,29
1.49,1012
1.5,32
1.54,58
1.55,20
1.58,15
1.59,368
1.64,20
1.69,97
1.74,143
1.79,334
1.83,20
1.87,8
1.88,3
1.89,34
1.91,20
1.94,37
1.95,3
1.97,44
1.98,12
1.99,48189
2.0,92
2.03,7
2.09,359
2.14,20
2.16,20
2.19,165
2.22,20
2.24,198
2.29,20
2.3,15
2.36,17
2.39,412
2.44,43
2.45,7
2.49,1378
2.5,44
2.51,20
2.54,26
2.59,151
2.63,12
2.69,136
2.71,50
2.74,20
2.79,228
2.88,10
2.9,20
2.93,20
2.94,10
2.99,41330
3.0,91
3.03,11
3.09,61
3.14,20
3.19,80
3.24,81
3.29,24
3.33,17
3.39,84
3.49,675
3.5,20
3.59,326
3.6,16
3.69,14
3.73,20
3.74,427
3.75,5
3.77,40
3.79,39
3.86,20
3.88,14
3.89,127
3.91,20
3.97,36
3.99,28315
4.0,76
4.19,165
4.2,87
4.24,47
4.28,10
4.3,15
4.33,13
4.39,59
4.49,624
4.54,60
4.59,20
4.63,20
4.64,20
4.79,225
4.85,20
4.88,6
4.89,30
4.93,57
4.94,33
4.95,2
4.99,71169
5.0,272
5.09,141
5.1,40
5.14,3
5.19,75
5.24,113
5.29,20
5.39,65
5.49,88
5.5,20
5.57,20
5.58,20
5.59,133
5.65,5
5.69,6
5.73,15
5.77,15
5.79,20
5.84,23
5.9,8
5.94,23
5.99,22094
6.0,26
6.1,14
6.19,6
6.23,20
6.24,95
6.29,144
6.31,20
6.36,20
6.39,106
6.49,207
6.59,40
6.66,37
6.69,127
6.74,56
6.79,118
6.8,20
6.98,20
6.99,21225
7.0,17
7.06,10
7.14,23
7.19,77
7.36,14
7.49,664
7.5,10
7.64,18
7.69,20
7.77,19
7.79,124
7.95,13
7.99,20129
8.0,42
8.09,20
8.19,20
8.24,43
8.39,92
8.49,136
8.54,20
8.7,20
8.74,19
8.79,13
8.88,20
8.9,13
8.98,4
8.99,9799
9.0,37
9.09,54
9.11,20
9.29,14
9.49,20
9.59,60
9.69,4
9.74,216
9.79,56
9.87,18
9.89,140
9.9,47
9.95,40
9.98,20
9.99,75795
10.0,109
10.04,58
10.19,60
10.25,9
10.39,80
10.49,140
10.79,73
10.99,5473
11.04,24
11.19,20
11.24,108
11.39,5
11.49,20
11.69,93
11.89,18
11.9,16
11.99,11764
12.0,66
12.24,20
12.4,20
12.49,260
12.59,100
12.74,98
12.79,7
12.9,11
12.95,1
12.99,10905
13.13,20
13.29,24
13.37,14
13.39,20
13.49,159
13.59,25
13.99,4255
14.38,15
14.39,20
14.49,40
14.5,8
14.73,20
14.95,20
14.99,41715
15.0,87
15.1,17
15.19,29
15.29,60
15.58,19
15.74,20
15.99,3348
16.0,9
16.24,80
16.39,20
16.66,20
16.99,3016
17.24,20
17.49,111
17.77,20
17.99,4325
18.74,40
18.89,16
18.99,2098
19.0,38
19.49,27
19.69,16
19.79,20
19.84,20
19.9,25
19.95,34
19.96,20
19.97,20
19.99,43138
20.0,86
20.04,20
20.24,20
20.99,84
21.09,8
21.24,20
21.99,164
22.49,80
22.6,16
22.79,20
22.99,98
23.39,20
23.97,20
23.99,159
24.49,20
24.59,20
24.79,20
24.99,13579
25.0,26
25.99,40
26.99,93
27.99,36
28.99,38
29.9,2
29.95,2
29.98,23
29.99,13003
30.0,20
31.96,20
31.99,40
32.99,12
33.66,1
34.99,2192
35.0,5
35.95,15
35.99,65
37.49,1
39.0,6
39.39,20
39.9,20
39.99,6451
40.0,20
44.95,15
44.98,20
44.99,730
45.0,11
49.69,5
49.99,2483
52.74,10
54.99,135
56.24,20
57.95,14
59.95,2
59.99,2880
64.95,19
64.99,81
69.03,20
69.95,5
69.99,283
74.99,53
79.99,133
84.99,17
89.99,41
94.99,79
99.0,3
99.99,167
119.99,9
124.99,1
129.99,17
149.0,4
149.99,23
159.99,2
199.99,120
249.0,2
269.99,7
299.9,1
999.0,11

Databricks visualization. Run in Databricks to view.

Prices varies on a scale from 0 to 999 $, sometime of any cents. Mean price is 7,73 $ with an initial price higher on 7,93 $ (cf last run clean_df.describe() command) (cf last run clean_df.describe() command).

In [0]:
result = clean_df \
    .groupBy(
        (F.floor(F.col('price') / 10) * 10).alias('range_price')) \
    .agg( \
        F.count('price').alias('game_nb')) \
    .orderBy('range_price')
display(result)

range_price,game_nb
0,498837
10,132626
20,27717
30,8868
40,3284
50,3061
60,408
70,186
80,58
90,249
110,9
120,18
140,27
150,2
190,120
240,2
260,7
290,1
990,11

Databricks visualization. Run in Databricks to view.

Databricks visualization. Run in Databricks to view.

#### Prices don't change ?

In [0]:
result = clean_df \
    .select(clean_df['publisher'], 'name', 'release_date', 'price', 'initialprice', 'discount') \
    .filter((clean_df['price'] != clean_df['initialprice']) & (clean_df['discount'] == 0)) \
    .orderBy('publisher', 'name', 'release_date') \
    .show(truncate=False)

+---------+----+------------+-----+------------+--------+
|publisher|name|release_date|price|initialprice|discount|
+---------+----+------------+-----+------------+--------+
+---------+----+------------+-----+------------+--------+

Prices change only with discount.

#### Are there many games with a discount?

Prices varies relying to discount. Le discount varie de 0 à 90 avec une valeur moyenne de 2,6. Le discount est rare.

In [0]:
result = clean_df \
    .select(clean_df['publisher'], 'developer', 'name', 'owners', 'positive', 'negative', 'release_date', 'price', 'initialprice', 'discount', 'genre', 'languages', 'required_age', 'category', 'platform', ) \
    .filter(clean_df.discount != 0 ) \
    .orderBy(desc('discount')) \
    .show()

+-----------+-----------+-------+-----------+--------+--------+------------+-----+------------+--------+-------------+---------+------------+-------------+--------+
|  publisher|  developer|   name|     owners|positive|negative|release_date|price|initialprice|discount|        genre|languages|required_age|     category|platform|
+-----------+-----------+-------+-----------+--------+--------+------------+-----+------------+--------+-------------+---------+------------+-------------+--------+
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
|graphxgames|graphxgames|hexagun|0 .. 20,000|       3|       1|  2019-11-04| 0.99|        9.99|      90|casual, indie|  english|           0|single-player| windows|
+-----------+-----------+-------+-----------+--------+--------+------------+-----+------------+--------+-------------+---------+------------+-------------+--------+
only showing top 20 rows

#### Vérifier la répartition des jeux discount

In [0]:
discounted_games = clean_df \
    .select(clean_df['discount'], 'name') \
    .filter(clean_df.discount != 0) \
    .agg(count('*'))

nodiscount_games = clean_df \
    .select(clean_df['discount'], 'name') \
    .filter(clean_df.discount == 0) \
    .agg(count('*'))

discounted_games_nb = discounted_games.collect()[0][0]
nodiscount_games_nb = nodiscount_games.collect()[0][0]
games_nb = discounted_games_nb + nodiscount_games_nb

percentage = discounted_games_nb / games_nb * 100
print(f'discounted_games_nb = {discounted_games_nb}\nnodiscount_games_nb = {nodiscount_games_nb}\ngames_nb = {games_nb}\npercentage = {percentage}')

discounted_games_nb = 36015
nodiscount_games_nb = 639476
games_nb = 675491
percentage = 5.3316772540270705

In [0]:
from pyspark.sql.functions import count, desc, floor, col, concat, lit

result = clean_df \
    .select(clean_df['discount']) \
    .filter(clean_df.discount != 0 ) \
    .withColumn('discount_bracket', (floor(col('discount').cast('int') / 10) * 10)) \
    .groupBy('discount_bracket') \
    .agg(count('*').alias('nb_games')) \
    .orderBy(desc('discount_bracket'))
    
result.display()

discount_bracket,nb_games
90,3257
80,4568
70,5596
60,3487
50,7639
40,3298
30,3272
20,3207
10,1691

In [0]:
from pyspark.sql.functions import count, desc, floor, col, concat, lit

result = clean_df \
    .select(clean_df['discount'], 'name', 'publisher') \
    .filter(clean_df.discount != 0 ) \
    .agg(count('*').alias('nb_games')) \
    .orderBy(desc('nb_games')) \
    .limit(5)
    
result.display()

nb_games
36015

In [0]:
from pyspark.sql.functions import count, desc, floor, col, concat, lit

result = clean_df \
    .select(clean_df['discount'], 'publisher') \
    .filter(clean_df.discount != 0 ) \
    .groupBy('discount', 'publisher') \
    .agg(count('*').alias('nb_games')) \
    .filter(col('nb_games') > 10) \
    .orderBy(desc('discount'))
    
result.display()

discount,publisher,nb_games
90,handmade games,89
90,my way games,21
90,mikołaj spychał,220
90,rex junior,60
90,"ultimate games s.a., art games studio s.a.",32
90,walter machado,240
90,toxic studio,40
90,droid riot,12
90,maximum games,40
90,succubella games,11
90,"cristian manolachi, atomic fabrik",58
90,enitvare,32
90,ionized games,40
90,reforged group,43
90,ordinary pine studio,12
90,space sheep gaming ltd,20
90,"hede games, hede",20
90,ci games,20
90,cyberwave,20
90,8floor,124
90,sabrina aridi,20
90,flightless,40
90,aldorlea games,108
90,karakuria team,20
90,interactive pixel entmt.,35
90,good shepherd entertainment,20
90,warfare studios,13
90,fatshark,99
90,laush studio,20
90,the quantum astrophysicists guild,40
90,attu games,15
90,"mass creation, na publishing inc., whispergames",20
90,paul connor,65
90,chainsawesome games,20
90,ultimate games s.a.,34
90,snkl studio,37
90,polydev team,20
90,"atomic fabrik, cristian manolachi",103
90,graphxgames,20
90,no gravity games,77
90,3dclouds,20
90,nimos games,20
90,ash & rust studios,19
90,daedalic entertainment,40
90,кико,18
90,sa industry,38
90,bedtime digital games,28
90,mikhail neznamov,39
90,rmking,20
90,oldfarmergames,17
90,sc jogos,96
90,dark design studios holdings co. ltd,49
90,onedrop,20
90,game dynasty,20
90,marginal act,20
90,"azerbaijan technology, aztech",80
90,whale rock games,20
90,mgn studios,14
90,opg euphore,13
90,defender defender,14
90,msi digital games,22
90,frogames,12
90,hede,40
90,digilie studio s.n.c.,12
90,dry cactus,20
90,summetgames,17
90,gdnomad,32
90,fusion studios,20
90,snail-ninja studio,12
90,yogscast games,20
90,wanech,20
90,"playway s.a., ultimate games s.a.",17
90,生人症候群,15
90,lukas navratil,16
90,helicopter games,20
90,everlasting fantasy,20
90,roenko games,20
90,early melon,13
90,sig publishing,20
90,"scale studio, gamesforgames",11
90,白新社,14
90,rosewater studios,11
90,enoops,20
90,evoluta studio,20
90,tero lunkka,37
90,yunus ayyildiz,18
90,black snake games,15
90,blue phoenix games,15
90,none,20
89,axel sonic,15
89,daedalic entertainment,20
89,techland,14
89,ultimate games s.a.,16
89,bloody pixel,17
88,pretty absurd,16
87,reforged group,73
87,murafka games,12
87,aldorlea games,27
87,the bratans,20
87,mikołaj spychał,20
87,warfare studios,27
87,spacefarer games ltd,20
87,seep,17
87,kuko,14
87,bullid games,13
87,pok&co,20
87,klabater,20
87,my way games,12
87,above and beyond technologies,20
87,handmade games,18
86,snkl studio,98
86,firelight interactive,40
86,daedalic entertainment,19
85,indie_games_studio,39
85,digerati,17
85,shiver games,40
85,round2games,20
85,team17 digital ltd,39
85,juicy cupcake,11
85,fellow traveller,58
85,headup,13
85,the bratans,20
85,techland publishing,20
85,electronic arts,20
85,pill bug interactive,20
85,vladislav castillo gonzalez,20
85,heart shaped games llc,20
85,11 bit studios,20
85,bekkerdev studio,20
85,thunderful publishing,15
83,trinity project,18
83,garage games,20
83,rex pex games,20
83,dillyframe,40
83,mikołaj spychał,20
83,droid riot,20
83,ak studio,20
83,enter the game,20
83,klabater,20
83,khakassia interactive,20
83,reforged group,27
83,dig publishing,22
83,supreme clans entertainment,20
83,lewis bergin,20
83,big black bear,20
83,snkl studio,14
82,firelight interactive,20
82,aldorlea games,12
82,gamestorming,11
82,xitilon,16
81,llama game studio,20
81,dnovel,20
81,ordinary pine studio,20
81,simplecmt,11
81,astero,13
81,lgv,40
81,reforged group,14
81,platstudio,20
81,ashley h.,20
81,conmtrast,50
81,cats who play,20
80,nikita morti,21
80,alawar premium,20
80,aged immortals,20
80,dgv-games,16
80,cowcat,20
80,ravenscourt,11
80,"dreadlocks ltd., techland, whispergames",20
80,techland publishing,37
80,cybreath,20
80,sometimes you,33
80,dance studio mix,18
80,coffee stain publishing,20
80,klabater,20
80,simon eltz,20
80,running pillow,18
80,enoops,168
80,brickcream,16
80,missing link games,22
80,jumit,20
80,nacon,20
80,team17 digital ltd,64
80,headup games,37
80,hyper'sthene,20
80,size five games,47
80,raw fury,20
80,untold tales,20
80,studioworks,14
80,louie inc,54
80,strategy first,171
80,alinovr,16
80,"alawar entertainment, esdigital games",19
80,gammera nest,20
80,sexy miss studio,20
80,jt,18
80,whale rock games,20
80,eroticon vr,20
80,nintai studios,20
80,handygames,16
80,flaming firefly,20
80,monster couch,20
80,axoora,20
80,no gravity games,40
80,ultimate games s.a.,20
80,ayrshire interactive,18
80,alon zubina,16
80,wtfomgames,40
80,the digital lounge,20
80,"kiss ltd, maximum games",20
80,tortuga team,20
80,firefly studios,20
80,abba games,16
80,11 bit studios,36
80,game developer x,20
80,freedom games,20
80,maximum games,19
80,"wig publishing, sig publishing",40
80,frogwares,20
80,yuna studio,13
80,anatoliy loginovskikh,80
80,headup,34
80,lamina studios,20
80,deep silver,40
80,tomimar,53
80,dominigames,20
80,fatshark,20
80,fellow traveller,52
80,eternal one games,20
80,southpeak games,11
80,girls dance studio,13
80,horsegames,20
80,goex games,17
80,"smiling dragon rpg studios, opium pulses entertainment",20
80,metthink productions,20
80,pigeons interactive,17
80,"fair weather studios, llc",20
80,seedwall,20
80,"playdigious, xd",20
80,"source byte sp. z o.o., blacer studio",20
80,"headup, whispergames",20
80,alongini,20
80,bkdove studios,20
80,alternative software ltd,30
80,bandai namco entertainment,20
80,anime fashion show,20
80,threeyes,20
80,modus games,20
80,bit dragon,20
80,dya games,20
80,redkar limited,20
80,witte´s studio,20
80,loren lemcke,20
80,main loop videogames s.l.,19
80,raptor claw games,13
80,surprise attack,11
80,among giants,13
80,ak studio,20
80,tunermaxx media gmbh,20
80,aihasto,20
80,tic toc games,20
80,ruxar,20
80,"headup, whisper games",16
79,game dynasty,17
77,hotfoodgames,16
77,reforged group,37
76,nlb project,14
75,veryhardmemegames,11
75,robert alvarez,17
75,digital tribe,37
75,phantom compass,20
75,untold tales,40
75,deck13,25
75,marvelous,34
75,funbox media ltd,171
75,gammera nest,53
75,mutant entertainment studios,20
75,tortuga team,20
75,rocketcat games,20
75,michael richard lannon,20
75,wig publishing,20
75,klabater,40
75,ubisoft,80
75,deltagemini,20
75,first games interactive,17
75,perfect world entertainment,16
75,revolution software ltd,80
75,hof studios,20
75,animakemu games,13
75,topware interactive,26
75,garage games,24
75,acgames,20
75,dig publishing,24
75,specialbit studio,39
75,thq nordic,82
75,"retroism, enlight software limited",11
75,positech games,20
75,sv games,20
75,sauropod studio,20
75,sfb games,20
75,badland publishing,20
75,code}{atch,40
75,2k,60
75,meridian4,20
75,treefall studios l.l.c.,15
75,futurevisionsgames,14
75,taleworlds entertainment,60
75,sadimakegames,11
75,fdg entertainment,13
75,all seeing eye games,20
75,tero lunkka,23
75,luci entertainment,29
75,toxic games,18
75,indie_games_studio,132
75,"2k, feral interactive (mac)",40
75,boom games,60
75,grey alien games,80
75,enka games,20
75,nomad games,20
75,archiact,20
75,wingedswordstudios,20
75,team17 digital ltd,16
75,emerick gibson,14
75,zenz vr,29
75,zqz,20
75,techland publishing,20
75,seaborgium entertainment,20
75,gruffers studio,16
75,coal valley games,20
75,alternative software ltd,29
75,new worlds games,20
75,aterdux entertainment,38
75,timeslip softworks,11
75,joymasher,12
75,funnykids,12
75,rushandev1,40
75,creativeforge games,20
75,kobra studio,20
75,doomster entertainment,20
75,necrophone games,20
75,origamihero games,60
75,volcanic games,20
75,11 bit studios,20
75,team17,20
75,lonely troops,11
75,ace maddox,20
75,the station,15
75,applava,20
75,junyjell,17
75,mastiff,12
75,j games 966,14
75,ultimate 3d novels,19
75,behold studios,20
75,analog chechen dudes,20
75,reverb publishing,20
75,"untold tales, doyoyo games",20
75,wandering wizard,20
75,no more robots,20
75,xu yantao,12
75,keinart lobre,20
75,those awesome guys,20
75,paul connor,17
75,alon zubina,17
75,application systems heidelberg,20
75,"nupixo games, whispergames",20
75,riaddev,20
75,rr productions,15
75,hammer&ravens,20
75,"ugly beard games, llc",40
75,net-assembly,18
75,event horizon,19
75,freedom games,20
75,gamily studios,21
75,xnzone,20
74,nick helweg,20
74,axel sonic,20
74,starwind games,20
74,reforged group,13
72,sa industry,19
72,кико,16
72,adrian domagalski,40
72,kuko,36
72,trinity project,20
72,cats who play,20
72,bisquitplay,20
72,dark design studios holdings co. ltd,20
71,reforged group,23
71,proativ games,87
71,owner games,20
71,leakage games,44
71,kishmish games,23
71,brainchocolate,19
70,hanako games,32
70,andy jurko,57
70,net-assembly,15
70,bandai namco entertainment,20
70,alawar entertainment,21
70,pixel forest games,19
70,boogygames studios,40
70,superhot team,20
70,inarcade,15
70,alternative software ltd,29
70,sunlight games,52
70,sinned games,20
70,all in! games,40
70,remainder studios,20
70,tribial games,17
70,prime matter,20
70,techland,20
70,pixeljam,33
70,samer hammami,20
70,inkle ltd,20
70,indie_games_studio,109
70,aihasto,28
70,ubisoft,20
70,playway s.a.,20
70,gameliberty,20
70,goldengod games,17
70,specialbit studio,20
70,nova's army,20
70,"gaming factory, ultimate games s.a.",13
70,loiste interactive,14
70,colossus game studio,15
70,zaxtorgames,12
70,merge games,40
70,the game bakers,20
70,11 bit studios,20
70,eager passion llc,15
70,techland publishing,20
70,envalid games,20
70,annapurna interactive,80
70,paulart,20
70,matthew brown,27
70,ael entertainment,32
70,basi studios,20
70,good shepherd entertainment,26
70,panic art studios,14
70,star bunny enterprises,16
70,meta interaction,20
70,no gravity games,51
70,"team17, next studios",20
70,tranquility games,17
70,amanita design,20
70,faster time games limited,21
70,curve games,20
70,kr games,20
70,fellow traveller,18
70,ankaar productions,20
70,wadjet eye games,33
70,flying islands team,20
70,kishmish games,40
70,nimos games,20
70,jason godbey,20
70,gilrs dance studio,12
70,real co.ltd,20
70,monster couch,19
70,myacg studio,17
70,shiro unlimited,20
70,"headup, whispergames",16
70,adam bradley,20
70,uruca game studio,20
70,daedalic entertainment,20
70,dry cactus,20
70,phr00t's software,14
69,aito games,20
69,damian sommer,20
69,pozzisoft,20
69,afbik studio,23
69,kobra studio,17
69,berry berry niceu,20
69,jts development,65
69,cow corp.,20
69,merlino games,16
69,amanita design,20
68,yeswecamp,20
67,kalypso media,20
67,prime matter,20
67,snail games usa,13
67,fdg entertainment,20
67,tortuga team,20
67,grapeshot games,20
67,coffee stain publishing,20
67,"u-play online,",20
67,annapurna interactive,20
66,izmir games collective,20
66,com8com1 software,20
66,aspyr,40
66,mega crit games,20
66,studio attic salt,17
66,falcon development,20
66,"koei tecmo games co., ltd.",39
66,teamcoil,20
66,jean-baptiste de clerfayt,20
66,"forward global group, ltd.",20
66,goat forest games,20
66,carbon studio,16
65,nomas games,20
65,tranquility games,40
65,synthetic domain,20
65,digital tribe,20
65,modus games,20
65,frontline: games series,20
65,the bratans,20
65,red fox,20
65,dr. cyril splutterworth,11
65,"catch & release, llc",13
65,razzart visual,15
65,burning goat studio,20
65,soulnata,16
65,adriaan de jongh,20
65,xnzone,20
65,fm simple games studio,20
65,acram digital,40
65,fenix fire entertainment,20
65,naoka games,20
65,runserver,11
65,cyberwave,20
65,winterspring games,20
65,wayupgames,20
65,nuchallenger,20
65,none,16
65,frozen dreams,21
65,enoops,12
65,lkmad,17
64,friendlyoctopus,20
62,wales interactive,57
62,绝汪,11
61,derevotyan,11
61,turtle cream,20
61,hikari field,16
60,topware interactive,65
60,digerati,20
60,louie inc,12
60,"piko interactive llc, bleem!",46
60,whale rock games,20
60,dillyframe,20
60,wasabi entertainment,122
60,pomeshkin valentin igorevich,20
60,movavi software,20
60,atomic elbow,20
60,enoops,38
60,itc studio,25
60,joe richardson,20
60,follow the fun,20
60,alternative software ltd,11
60,naoka games,19
60,bucikpro,16
60,inork game,20
60,city interactive s.a.,20
60,freedom games,17
60,superhot team,41
60,inkle ltd,20
60,abbey games,13
60,anarchy enterprises,11
60,first games interactive,24
60,application systems heidelberg,13
60,misou games,20
60,revolution software ltd,20
60,daedalic entertainment,40
60,lightup,40
60,reverie world studios,40
60,sonomio games,20
60,bejotah,14
60,supra games,20
60,patrones & escondites,20
60,seedwall,72
60,hanako games,16
60,skywalker hk,14
60,graverobber foundation,20
60,anamik majumdar,34
60,no gravity games,20
60,2p games,20
60,tranquility games,20
60,elhaitham ashmawy,20
60,one bit studio,20
60,farkhutdinov m,20
60,amayadori development,15
60,movavi software,35
60,arbitrary metric,16
60,fraoula,16
60,thegamecreators,20
60,lorebound entertainment,20
60,piko interactive llc,18
60,joshua keith,20
60,chop chop games,20
60,"breaking walls, game seer ventures",20
60,maris ozols,20
60,indie_games_studio,40
60,all in! games,20
60,team17,40
60,"united label, ci games",20
60,timeslip softworks,11
60,mastiff,20
60,monticube,17
60,west sun,17
60,lonely troops,14
60,d-pad studio,20
60,wispfire,11
60,"bifrost entertainment, dangen entertainment, gamera games, intragames co., ltd.",20
60,reb_orn,11
60,gemini stars games,20
60,awfully nice studios,17
60,hv,12
60,shiravune,18
60,fellow traveller,20
60,studio v5,20
60,merge games,20
60,robohamster,20
60,"flazm, meta publishing",20
60,mythicowl,20
60,mens sana interactive,18
60,perfect world entertainment,20
59,shortstackstudio,19
59,electronic arts,20
57,electronic sheep games,20
56,amygdalum,20
56,gestalt development studio,20
55,lighthouse games studio,38
55,acram digital,20
55,wales interactive,19
55,ratalaika games s.l.,20
55,thunderful publishing,20
55,noodlecake,20
55,platinumgames inc.,16
55,frogwares,20
55,aleksey izimov,57
55,"joe richardson, superhot presents",20
55,magic design studios,20
55,headup,20
55,indie_games_studio,20
55,all in! games,20
55,anvil game studios,20
55,nacon,20
54,vladislav castillo gonzalez,20
52,falcon interactive,20
51,big black bear,107
51,trinity project,202
51,indie_games_studio,43
51,meokigame,59
51,gestalt development studio,20
51,droid riot,16
51,sweet games,60
51,planescape game studio,20
51,enoops,56
51,hfm games,40
51,"cristian manolachi, atomic fabrik",19
51,freeanimals_software,16
51,seedwall,134
51,coffee studio,20
51,new dawn game studio,20
51,misc.261,11
51,nukgames,80
51,heyjeff,39
51,walter machado,66
51,rafael ferreira mourão martins,20
51,lot10games,18
51,barlow studio,17
51,myarcadegames studios,20
51,christophercgaming llc,64
51,anpa.us,25
51,gdnomad,60
51,split personality games,20
51,black lime studio,19
51,anatoliy loginovskikh,39
51,dnovel,54
51,boom entertainment,20
51,goex games,13
51,tape studio,19
51,cutekatestudio,16
51,panguojun,20
51,boom games,100
51,rmking,14
51,umut ay(00iblis00),17
51,wellington,15
51,hot chill,12
51,boom games team,20
51,mikołaj spychał,20
51,wolfgangis,11
51,.,12
51,muffingames,20
51,horsegames,20
51,union onion,20
51,orube game studio,17
51,stud1o,11
51,rex junior,11
51,valera entertainment,13
51,amyberyl,20
50,"ultimate games s.a., gaming factory",20
50,chagas studios,20
50,nichgames,14
50,allen cayn,17
50,shiny dolphin games llc,16
50,ivanovich games,60
50,fleon games,57
50,rusty lake,36
50,application systems heidelberg,37
50,8bitskull,20
50,smorb software,15
50,star consult s.r.l.,11
50,lamina studios,11
50,tydecon games,33
50,neon doctrine,40
50,retrobug,11
50,indiewolf games,20
50,orube game studio,18
50,hammer&ravens,20
50,"united label, ci games",20
50,"rockin' android, rockin android",12
50,dinosaur polo club,20
50,jetdogs studios,33
50,gsb studios,20
50,fobti interactive,107
50,the categlory,11
50,xreal games,20
50,do games limited,20
50,synthetic vector studios,20
50,digimight,141
50,hooting banana studios,20
50,"midboss, llc.",20
50,braingoodgames,20
50,meng games,20
50,nyamyam,34
50,araknumia software,13
50,lo-fi games,20
50,thunderful publishing,20
50,tas systems corp,22
50,leander nieuwenstein,15
50,none,20
50,firelight interactive,20
50,colossus game studio,14
50,ms games sp. z o.o.,40
50,annapurna interactive,14
50,sapphire dragon productions,56
50,portgate studios,18
50,mcg,20
50,versus evil,57
50,raw fury,20
50,eroge japan,74
50,serious bros.,20
50,flarb llc,20
50,migaloo games,12
50,"welovebot co., ltd.",20
50,broken rules,20
50,2ndup studios,16
50,dominigames,20
50,king key games,80
50,"cristian manolachi, atomic fabrik",40
50,brokenbyte,20
50,"topware interactive, ace",25
50,resnijars,20
50,virtual arts studio,20
50,fruitbat factory,151
50,r. güray aslı,20
50,心火游戏,11
50,hfm games,20
50,zix solutions,20
50,enno games,20
50,2 for 2,20
50,221 games,20
50,nomad games,49
50,frozen dreams,21
50,"rising win tech. co., ltd",18
50,谜之老六,14
50,"taylor ""loxxulus"" hatton",11
50,sony music entertainment (japan) inc. / unties,34
50,meokigame,100
50,ma ma software,14
50,会玩游戏工作室,17
50,terarin games,12
50,omnidream creations,15
50,gaming factory,20
50,gearbox publishing,36
50,nlb project,20
50,sp-time,19
50,funktronic labs,41
50,indienova,20
50,tuttifrutti interactive,20
50,hidden depths games,18
50,garage heathen,20
50,rmasia,11
50,tas systems,12
50,"koei tecmo games co., ltd.",39
50,yang sun,11
50,prestige games,84
50,renegade sector games,20
50,merge games,20
50,cdhy interactive,20
50,topware interactive ace,14
50,konfa games,20
50,dnovel,12
50,brandtner,18
50,consulog,19
50,alda games,20
50,"cape cosmic, flyhigh works",20
50,"fatbot games, s. r. o.",20
50,absurdponcho,20
50,second maze,13
50,walk without rhythm games,20
50,romantic room,40
50,marinosdev134,12
50,3dm_live_wallpapers,17
50,k-games,20
50,runic games,60
50,bennett apps,20
50,"ue4.doctor, sigma's",20
50,"tokyotoon, fruitbat factory",40
50,cloak and dagger games,40
50,mischka kamener,12
50,zordix publishing,19
50,"midnight city, majesco entertainment",19
50,thq nordic,15
50,5peaks creative,20
50,tim rachor,13
50,myacg studio,20
50,pillow castle,20
50,duckbearlab,14
50,shiravune,51
50,evil goat,20
50,temple gates games,12
50,"10mg, gesinimo games",20
50,creetah ltd,15
50,qumaron,11
50,koch media,15
50,revmatek,20
50,ruxar,20
50,nacon,20
50,clouded leopard entertainment,12
50,"monster couch, stonemaier games, indienova",20
50,lillebror media,18
50,amazon games,20
50,dionic software,20
50,hh-games,35
50,freedom games,59
50,ci games,20
50,luke mccrea,18
50,"red android, epixr games ug",17
50,lazer genu studio,20
50,rising moon games,20
50,untold tales,27
50,paul miell,15
50,clockwork origins,20
50,rocpaingames,18
50,timberline studio,20
50,qubyte interactive,16
50,happy max,18
50,last bastion studios llc,20
50,rolling crown,20
50,lorebound entertainment,12
50,red rose,20
50,topware interactive,20
50,little black book entertainment,20
50,"pixel almost perfect, plug in digital",16
50,phr00t's software,18
50,橙光游戏,12
50,magenta factory,19
50,hakan martin,20
50,fz-tech,17
50,eigomanga,20
50,dashing strike,19
50,djokagames,16
50,playplaygame,13
50,leka games,20
50,cordless games studio,20
50,pds games,20
50,virtexuniverse,14
50,merteam,15
50,gemdrop games,13
50,pisces game,20
50,petroglyph,14
50,"midnight city , majesco entertainment",16
50,rockgame s.a.,20
50,lucapy studio,20
50,cole and jordan studios,14
50,pixelconflict,20
50,split light studio,15
50,michael richard lannon,20
50,fjrd interactive,20
50,the bratans,20
50,shinu real arts,20
50,sunset dreamland,20
50,brain&brain,20
50,giorgi abelashvili,18
50,ejrgames,29
50,sonejo studios,20
50,alternative software ltd,20
50,lo-fi people,20
50,fireshine games,20
50,lonely troops,20
50,assemble entertainment,20
50,"attrito, m7 productions",20
49,analog chechen dudes,13
48,sometimes you,61
48,kindermann corp.,15
48,yunus ayyildiz,12
48,panguojun,20
48,"atomic fabrik, cristian manolachi",20
45,lunarcore games,15
45,fourfold games,11
45,anamik majumdar,100
45,ma ma software,20
45,game factory interactive,13
45,epixr games ug,20
45,clever plays,20
45,7dots,16
45,gfi,13
45,rebel graphix,20
42,"dreamstep, 绝汪",20
40,69gate,20
40,minicactus games,20
40,devolver digital,40
40,"piko interactive llc, bleem!",52
40,mooneye studios,40
40,lanqing game,20
40,caio flavio,20

In [0]:
result = clean_df \
    .select(clean_df['publisher'], 'discount') \
    .filter(clean_df.discount != 0 ) \
    .filter(clean_df.publisher.isin(['big fish games', 'ubisoft','valve'])) \
    .groupBy('publisher') \
    .agg(count('*').alias('nb_games'))
    
result.display()

publisher,nb_games
ubisoft,100

In [0]:
result = clean_df \
    .select(clean_df['owners'], 'discount') \
    .filter(clean_df.discount != 0 ) \
    .groupBy('owners') \
    .agg(count('*').alias('games_nb')) \
    .orderBy(desc('games_nb'))

result.display()

owners,games_nb
"0 .. 20,000",21168
"20,000 .. 50,000",4922
"50,000 .. 100,000",3318
"100,000 .. 200,000",2589
"200,000 .. 500,000",2289
"500,000 .. 1,000,000",774
"1,000,000 .. 2,000,000",530
"2,000,000 .. 5,000,000",305
"5,000,000 .. 10,000,000",80
"10,000,000 .. 20,000,000",20
"50,000,000 .. 100,000,000",20

In [0]:
result = clean_df \
    .select(clean_df['release_date'], 'discount') \
    .filter(clean_df.discount != 0 ) \
    .withColumn('release_year', year(to_date(col('release_date')))) \
    .groupBy('release_year') \
    .agg(count('*').alias('games_nb')) \
    .orderBy(desc('games_nb'))

result.display()

release_year,games_nb
2022,8839
2021,7686
2020,5001
2019,3767
2018,3149
2017,2369
2016,1906
2015,1364
2014,932
2013,300
2012,191
2009,190
2010,98
2008,64
2007,52
2011,51
2006,43
2003,7
1900,6

In [0]:
result = clean_df \
    .select(clean_df['genre'], 'discount') \
    .filter(clean_df.discount != 0 ) \
    .groupBy('genre') \
    .agg(count('*').alias('games_nb')) \
    .orderBy(desc('games_nb'))

result.display()

genre,games_nb
"action, indie",2259
"action, adventure, indie",2256
"adventure, indie",2004
"adventure, casual, indie",1935
"casual, indie",1826
casual,986
"action, adventure, casual, indie",923
"action, adventure, indie, rpg",923
"casual, indie, strategy",765
"action, casual, indie",764
adventure,762
action,709
indie,586
"adventure, indie, rpg",548
"adventure, casual, indie, simulation",473
"casual, indie, simulation, strategy",442
"action, adventure",438
"casual, indie, simulation",422
"action, adventure, indie, simulation",381
"indie, strategy",354
"action, adventure, casual, indie, simulation",327
"adventure, indie, simulation",322
"adventure, casual, indie, rpg",321
"indie, simulation, strategy",313
rpg,303
"adventure, indie, rpg, strategy",302
"indie, rpg, strategy",288
"action, adventure, casual, indie, rpg",283
"adventure, casual",283
"action, indie, rpg",273
"action, adventure, rpg",268
"adventure, casual, indie, rpg, strategy",250
strategy,244
"action, casual, indie, strategy",227
"action, casual",223
"action, indie, early access",223
"action, rpg",222
"action, adventure, indie, rpg, early access",220
"simulation, strategy",215
"indie, simulation",208
"action, indie, strategy",204
"indie, rpg",203
"action, adventure, indie, strategy",177
"casual, indie, rpg",176
"action, adventure, casual, indie, rpg, simulation",169
simulation,164
"action, adventure, indie, rpg, simulation",161
"action, adventure, indie, rpg, strategy",159
"action, adventure, indie, early access",158
"rpg, strategy",152
"adventure, indie, strategy",150
"adventure, rpg",147
"action, casual, indie, early access",145
"adventure, indie, rpg, simulation",143
"action, casual, indie, simulation",141
"action, adventure, casual",137
"casual, simulation",136
"action, indie, simulation",135
"adventure, casual, indie, simulation, strategy",130
"casual, strategy",115
"casual, indie, racing",107
"adventure, casual, indie, rpg, simulation, strategy",103
racing,101
"simulation, sports",100
"action, adventure, casual, indie, rpg, strategy",98
"action, adventure, casual, indie, strategy",98
"action, indie, racing",98
"casual, indie, rpg, simulation, strategy",97
"action, adventure, indie, rpg, simulation, early access",94
"simulation, strategy, early access",94
"action, indie, racing, sports",93
"adventure, casual, simulation",89
"adventure, casual, indie, rpg, simulation",88
"casual, indie, rpg, simulation",84
"indie, rpg, simulation, strategy",80
"action, casual, indie, simulation, sports",78
"indie, simulation, strategy, early access",77
"adventure, casual, indie, strategy",76
"casual, indie, sports",75
"indie, rpg, simulation",73
"action, adventure, casual, free to play, indie, massively multiplayer, racing, rpg, simulation, sports, strategy",71
"adventure, indie, rpg, early access",71
"action, simulation",71
"action, adventure, casual, indie, racing",70
"casual, indie, simulation, early access",67
"adventure, casual, indie, early access",65
"action, adventure, indie, simulation, strategy",64
"adventure, simulation",64
"indie, racing, simulation",62
"action, adventure, casual, indie, simulation, sports",61
"action, strategy",60
"adventure, casual, indie, rpg, simulation, strategy, early access",60
"action, adventure, indie, simulation, early access",60
"casual, simulation, sports",60
"action, adventure, rpg, simulation, early access",59
"indie, strategy, early access",58
"racing, simulation, sports",56
"action, adventure, strategy",56
"action, indie, simulation, sports",54
"action, indie, sports",54
"adventure, rpg, strategy",54
"indie, sports",53
"action, adventure, casual, indie, rpg, simulation, sports, strategy",53
"action, casual, indie, racing",52
"casual, indie, early access",52
"action, indie, simulation, strategy",50
"action, adventure, casual, indie, rpg, simulation, sports",50
"action, adventure, casual, indie, rpg, simulation, strategy",50
"adventure, casual, indie, racing, simulation, sports",50
"casual, simulation, strategy",49
"casual, indie, rpg, simulation, strategy, early access",48
"adventure, casual, rpg",48
"casual, indie, rpg, strategy",48
"action, adventure, casual, indie, simulation, strategy",48
"action, adventure, casual, indie, simulation, sports, strategy",47
"action, adventure, casual, indie, racing, simulation, sports, strategy",47
"action, indie, rpg, strategy",46
"strategy, early access",46
"action, casual, indie, rpg",45
"casual, indie, racing, simulation, sports",44
"action, casual, indie, simulation, early access",41
"action, indie, rpg, simulation, strategy",40
"action, adventure, casual, indie, simulation, strategy, early access",40
"action, adventure, casual, indie, rpg, early access",40
"action, casual, indie, rpg, strategy",40
"indie, rpg, strategy, early access",40
"adventure, casual, indie, rpg, early access",40
"action, adventure, indie, racing",40
"action, adventure, indie, rpg, simulation, strategy",40
"action, adventure, casual, indie, massively multiplayer, rpg, strategy, early access",40
"action, casual, indie, racing, sports",40
"adventure, casual, indie, massively multiplayer, rpg",40
"action, indie, simulation, strategy, early access",40
"action, adventure, casual, indie, rpg, strategy, early access",40
"action, adventure, casual, indie, racing, rpg, simulation",40
"indie, early access",39
"adventure, strategy",39
"action, indie, strategy, early access",38
"action, casual, indie, sports, early access",38
"adventure, indie, simulation, early access",37
"adventure, casual, indie, simulation, sports, strategy",37
"indie, simulation, early access",36
"action, casual, indie, sports",36
"action, indie, rpg, early access",35
"simulation, sports, strategy, early access",35
"rpg, simulation, strategy",33
"adventure, casual, indie, simulation, sports",33
"sports, early access",33
"action, casual, indie, simulation, strategy",32
"design & illustration, utilities",32
"casual, rpg",31
"indie, racing, simulation, early access",30
"adventure, rpg, simulation",29
"casual, indie, racing, simulation",29
"action, indie, simulation, early access",29
"action, adventure, simulation",29
"casual, indie, simulation, strategy, early access",29
"action, adventure, casual, indie, racing, rpg, simulation, sports, strategy",28
"action, casual, racing",26
"violent, gore, action, adventure, indie",25
"casual, indie, simulation, sports",25
"action, adventure, casual, indie, early access",25
"casual, indie, strategy, early access",24
"action, racing, simulation",23
"action, casual, strategy",23
"indie, simulation, sports",22
"action, casual, simulation",21
"casual, indie, rpg, simulation, sports",20
"adventure, casual, strategy",20
"rpg, simulation",20
"action, casual, indie, massively multiplayer, sports",20
"action, indie, sports, strategy",20
"action, adventure, indie, massively multiplayer, rpg, simulation",20
"adventure, massively multiplayer, early access",20
"casual, indie, simulation, sports, early access",20
"action, adventure, casual, indie, racing, simulation",20
"animation & modeling, audio production, design & illustration, education, software training, utilities, video production",20
"action, casual, indie, rpg, early access",20
"adventure, casual, rpg, simulation, strategy",20
"action, casual, indie, massively multiplayer",20
"action, casual, rpg",20
"action, adventure, indie, rpg, simulation, sports, early access",20
"indie, rpg, early access",20
"adventure, racing, simulation",20
"adventure, simulation, sports",20
"casual, indie, racing, sports",20
"action, adventure, casual, indie, racing, simulation, sports, early access",20
"action, adventure, casual, strategy",20
"casual, indie, rpg, simulation, early access",20
"adventure, casual, indie, rpg, simulation, early access",20
"adventure, casual, indie, rpg, simulation, sports, strategy",20
"casual, indie, massively multiplayer, racing, simulation, sports, early access",20
"action, indie, racing, sports, early access",20
"casual, racing",20
"action, indie, massively multiplayer",20
"indie, racing, simulation, sports",20
"action, indie, massively multiplayer, racing, simulation, sports, early access",20
"adventure, indie, rpg, simulation, strategy",20
"action, adventure, casual, simulation, strategy",20
"action, adventure, casual, indie, massively multiplayer, racing, rpg, simulation, sports, early access",20
"action, indie, massively multiplayer, sports",20
"adventure, indie, rpg, simulation, early access",20
"adventure, indie, massively multiplayer, rpg, strategy",20
"action, adventure, casual, indie, massively multiplayer, racing, simulation, strategy",20
"animation & modeling, design & illustration, education, software training, utilities, game development",20
"action, casual, indie, strategy, early access",20
"action, adventure, casual, simulation, sports",20
"action, adventure, casual, indie, sports, early access",20
"action, sports",20
"adventure, indie, simulation, strategy",20
"action, adventure, massively multiplayer, rpg, early access",20
"action, adventure, indie, racing, rpg, simulation, sports",20
"action, early access",20
"action, adventure, casual, simulation, sports, strategy, early access",20
"action, adventure, casual, free to play, indie, sports, strategy",20
"action, adventure, simulation, strategy",20
"action, adventure, casual, indie, racing, simulation, sports",20
"animation & modeling, audio production, design & illustration, software training, utilities, video production, web publishing",20
"sexual content, nudity, adventure, casual, indie, simulation",20
"action, adventure, casual, indie, racing, rpg",20
"adventure, casual, rpg, simulation",20
"action, adventure, casual, indie, racing, rpg, simulation, sports",20
"action, casual, indie, massively multiplayer, sports, strategy",20
"action, adventure, simulation, early access",20
"violent, gore, action",20
"action, indie, massively multiplayer, rpg",20
"action, simulation, strategy, early access",20
"action, adventure, casual, indie, massively multiplayer, simulation, sports, strategy",20
"action, adventure, casual, free to play, indie, strategy",20
"action, massively multiplayer, early access",20
"action, adventure, casual, indie, massively multiplayer, racing, sports, early access",20
"action, adventure, casual, indie, massively multiplayer, rpg, simulation, strategy",20
"action, adventure, massively multiplayer, rpg",20
"adventure, casual, indie, strategy, early access",20
"casual, indie, massively multiplayer, simulation, sports, early access",20
"action, adventure, indie, massively multiplayer, rpg, simulation, strategy",20
"casual, indie, racing, simulation, strategy",20
"action, indie, racing, strategy",20
"indie, rpg, simulation, sports, strategy",20
"action, adventure, casual, indie, sports, strategy",20
"action, adventure, casual, indie, rpg, simulation, strategy, early access",20
"action, casual, indie, simulation, sports, early access",20
"casual, indie, simulation, utilities",20
"action, casual, rpg, simulation, early access",20
"action, casual, indie, racing, simulation, sports, early access",20
"action, indie, massively multiplayer, simulation, strategy",20
"action, casual, indie, racing, simulation, sports",20
none,19
"action, adventure, casual, indie, massively multiplayer",19
"adventure, rpg, simulation, strategy",19
sports,18
"action, adventure, indie, simulation, sports, early access",18
"simulation, sports, strategy",18
"casual, free to play, massively multiplayer",18
"casual, rpg, simulation, strategy",18
"action, casual, indie, racing, sports, early access",17
"casual, strategy, early access",17
"indie, massively multiplayer",16
"violent, action, casual, indie, simulation",16
"action, casual, racing, simulation, sports",16
"action, simulation, strategy",15
"action, adventure, early access",15
"audio production, software training, utilities, video production, web publishing",15
"nudity, violent, action, adventure, rpg",15
"action, adventure, indie, massively multiplayer, simulation, early access",15
"action, casual, indie, rpg, simulation, strategy",15
"action, simulation, sports",13
"action, adventure, massively multiplayer, rpg, simulation",13
"casual, sports",12
"design & illustration, education",12
"adventure, casual, simulation, strategy",11
"action, casual, indie, massively multiplayer, simulation, strategy, early access",11
"action, adventure, casual, indie, rpg, simulation, early access",10
"racing, simulation",10
"action, casual, indie, massively multiplayer, rpg, simulation",10
"adventure, casual, indie, sports",10
"adventure, casual, rpg, strategy",9
"sexual content, casual, indie, simulation",9
"action, massively multiplayer, simulation",9
"action, indie, simulation, sports, strategy",9
"design & illustration, utilities, early access",9
"adventure, indie, early access",8
"action, casual, sports, strategy",8
"action, casual, simulation, sports",8
"action, adventure, casual, free to play, indie, racing, rpg, simulation, sports",8
"animation & modeling, design & illustration, utilities",7
"casual, indie, simulation, sports, strategy",7
"indie, racing",7
"action, adventure, racing, simulation",6
video production,6
"action, casual, indie, simulation, strategy, early access",6
"action, adventure, racing, simulation, early access",6
"action, casual, indie, sports, strategy",6
"action, casual, simulation, sports, strategy",6
audio production,5
"animation & modeling, design & illustration, photo editing, utilities, video production",5
"racing, sports",5
"adventure, casual, free to play, indie",5
"action, adventure, casual, indie, sports",5
"audio production, design & illustration, utilities, video production, web publishing",5
"utilities, early access",5
"gore, adventure, indie",4
"violent, action, indie",4
"animation & modeling, design & illustration, utilities, early access",4
"action, adventure, racing",4
"animation & modeling, design & illustration, education",4
"photo editing, utilities, video production",3
"utilities, game development",3
"design & illustration, education, utilities",3
"violent, action, casual",3
design & illustration,1
web publishing,1

### languages

What are the most represented languages?

In [0]:
from pyspark.sql.functions import col, explode, split, trim
result = clean_df \
    .select("language", 'name') \
    .groupBy("language") \
    .agg(countDistinct("name").alias("game_nb")) \
    .orderBy("game_nb", ascending=False) \
    .limit(5)
result.display(truncate=False)

language,game_nb
english,54174
chinese,613
japanese,197
russian,84
korean,24

In 2022, the most supported language is english with 54768 games, then german and chineese. French on 4th row with 13414 games before russian.

Are there many games prohibited for children under 16/18 ?

In [0]:
result = clean_df \
    .select('required_age') \
    .filter(clean_df['required_age'].between(16, 21)) \
    .groupBy("required_age") \
    .agg(count("*").alias("forbidden_games_nb")) \
    .orderBy('required_age')
result.display()

required_age,forbidden_games_nb
16,525
17,602
18,3081
20,11
21,15

Ca représente quel pourcentage ?

In [0]:
result = clean_df \
    .select('name', 'required_age', 'genre', 'languages', 'tag') \
    .filter(clean_df['required_age'].between(16, 21)) \
    .orderBy('required_age')
result.display()

### tags

Quels sont les tags les plus représentés sur les jeux interdits aux mineurs ?

In [0]:
result = clean_df \
    .select('required_age', 'extracted_tag', 'name') \
    .filter(clean_df['required_age'].between(16, 21)) \
    .groupBy("extracted_tag") \
    .agg(countDistinct("extracted_tag").alias("game_nb")) \
    .orderBy('game_nb', ascending=False)
result.display()

extracted_tag,game_nb
blood,1
great soundtrack,1
choices matter,1
memes,1
shoot 'em up,1
space,1
medieval,1
top-down shooter,1
illuminati,1
open world survival craft,1
sci-fi,1
dating sim,1
6dof,1
adventure,1
thriller,1
3d,1
simulation,1
funny,1
narrative,1
4 player local,1
pve,1
character customization,1
spectacle fighter,1
rogue-lite,1
jrpg,1
romance,1
superhero,1
gothic,1
detective,1
family friendly,1
wargame,1
aliens,1
stealth,1
mystery,1
sexual content,1
third person,1
competitive,1
america,1
action rpg,1
online co-op,1
war,1
2.5d,1
team-based,1
gore,1
time manipulation,1
crafting,1
vr only,1
cute,1
cartoon,1
multiple endings,1
mythology,1
action roguelike,1
fighting,1
female protagonist,1
time travel,1
colorful,1
military,1
nudity,1
survival,1
dark,1
dystopian,1
cats,1
crime,1
action,1
hentai,1
comedy,1
investigation,1
puzzle,1
violent,1
2d,1
local co-op,1
epic,1
local multiplayer,1
supernatural,1
magic,1
zombies,1
vr,1
fast-paced,1
rogue-like,1
open world,1
sandbox,1
bullet hell,1
tutorial,1
looter shooter,1
resource management,1
psychological horror,1
action-adventure,1
parody,1
gun customization,1
crpg,1
atmospheric,1
pvp,1
classic,1
platformer,1
free to play,1
mystery dungeon,1
early access,1
third-person shooter,1
vehicular combat,1
combat,1
political,1
ninja,1
otome,1
demons,1
arena shooter,1
isometric,1
drama,1
massively multiplayer,1
tactical,1
controller,1
twin stick shooter,1
world war ii,1
heist,1
alternate history,1
experimental,1
physics,1
hidden object,1
retro,1
perma death,1
psychological,1
historical,1
nsfw,1
fps,1
casual,1
sports,1
tactical rpg,1
futuristic,1
walking simulator,1
lgbtq+,1
first-person,1
shooter,1
choose your own adventure,1
anime,1
multiplayer,1
hero shooter,1
side scroller,1
conspiracy,1
stylized,1
hack and slash,1
survival horror,1
arcade,1
cinematic,1
dark comedy,1
indie,1
co-op,1
fantasy,1
metroidvania,1
soundtrack,1
story rich,1
rpg,1
strategy,1
top-down,1
exploration,1
interactive fiction,1
modern,1
1980s,1
point & click,1
dynamic narration,1
emotional,1
singleplayer,1
realistic,1
co-op campaign,1
cartoony,1
building,1
swordplay,1
politics,1
rpgmaker,1
dark fantasy,1
visual novel,1
horror,1
surreal,1
difficult,1
mature,1
turn-based,1
character action game,1
post-apocalyptic,1
dungeon crawler,1
narration,1
base-building,1
3d fighter,1
pixel graphics,1
3d platformer,1
short,1
hacking,1
dark humor,1
reboot,1
underwater,1
precision platformer,1
rts,1
turn-based tactics,1
addictive,1
procedural generation,1
moddable,1
cult classic,1
villain protagonist,1
tower defense,1
turn-based combat,1
werewolves,1
racing,1
replay value,1
bullet time,1
3d vision,1
cyberpunk,1
foreign,1
lovecraftian,1
noir,1
combat racing,1
hand-drawn,1
quick-time events,1
satire,1
nature,1
parkour,1
logic,1
unforgiving,1
turn-based strategy,1
management,1
loot,1
level editor,1
economy,1
1990's,1
martial arts,1
automobile sim,1
science,1
touch-friendly,1
comic book,1
hunting,1
text-based,1
immersive sim,1
sniper,1
destruction,1
relaxing,1
linear,1
life sim,1
based on a novel,1
medical sim,1
experience,1
old school,1
remake,1
vampire,1
gambling,1
driving,1
card game,1
conversation,1
time management,1
2d fighter,1
puzzle-platformer,1
beat 'em up,1
fmv,1
dragons,1
party,1
assassin,1
mechs,1
mod,1
minimalist,1
clicker,1
episodic,1
movie,1
games workshop,1
warhammer 40k,1
beautiful,1
360 video,1
dinosaurs,1
inventory management,1
archery,1
robots,1
on-rails shooter,1
feature film,1
2d platformer,1
minigames,1
philosophical,1
artificial intelligence,1
boxing,1
souls-like,1
party-based rpg,1
crowdfunded,1
split screen,1
match 3,1
kickstarter,1
steampunk,1
lore-rich,1
nostalgia,1
psychedelic,1
board game,1
music,1
horses,1
nonlinear,1
abstract,1

# Genre analysis

#### What are the most represented genres?

In [0]:
genre_top = clean_df \
    .select('appid', 'extracted_genre') \
    .groupBy('extracted_genre') \
    .agg(countDistinct('appid').alias('games_nb')) \
    .orderBy(desc('games_nb')) \
    .limit(5)

genre_top.show()

+---------------+--------+
|extracted_genre|games_nb|
+---------------+--------+
|         action|   23564|
|      adventure|   11254|
|         casual|    9726|
|          indie|    5400|
|     simulation|    1206|
+---------------+--------+

In 2022, the trend genre is : 
- 1st indie with 39681 games, 
- 2d action with 23759 games, 
- 3d casual with 22086 games. Warning : multiple genres coexist on games.

#### Are there any genres that have a better positive/negative review ratio?

In [0]:
reviewed_ratio = clean_df \
    .select('appid', 'extracted_genre', 'positive', 'negative') \
    .dropDuplicates(['appid', 'extracted_genre']) \
    .groupBy('extracted_genre') \
    .agg(F.sum('positive').alias('positive_sum'), F.sum('negative').alias('negative_sum')) \
    .withColumn('ratio', col('positive_sum') /  col('negative_sum')) \
    .orderBy(desc('ratio')) \
    .limit(5)
reviewed_ratio.show(truncate=False)

+--------------------+------------+------------+------------------+
|extracted_genre     |positive_sum|negative_sum|ratio             |
+--------------------+------------+------------+------------------+
|game development    |2411        |136         |17.727941176470587|
|indie               |5816540     |509109      |11.424940435152394|
|animation & modeling|121081      |13936       |8.688361079219288 |
|audio production    |56344       |7116        |7.917931422147274 |
|casual              |4014297     |508069      |7.901086269778317 |
+--------------------+------------+------------+------------------+

Genres with the best review ratio are :
- 1 photo editing with 42 positive advices for 1 negative
- 2 animation & modeling with 26 positive advices for 1 negative
- 3 design & illustration with 25 positive advices for 1 negative

Do some publishers have favorite genres?

In [0]:
top_publishers = clean_df \
    .select('appid', 'publisher', 'extracted_genre') \
    .dropDuplicates(['appid', 'extracted_genre']) \
    .groupBy('publisher', 'extracted_genre') \
    .agg(count('extracted_genre').alias('games_nb')) \
    .orderBy(desc('games_nb'))
top_publishers.show(truncate=False)

+--------------------------+---------------+--------+
|publisher                 |extracted_genre|games_nb|
+--------------------------+---------------+--------+
|big fish games            |adventure      |392     |
|8floor                    |casual         |230     |
|choice of games           |adventure      |99      |
|alawar entertainment      |adventure      |94      |
|none                      |action         |86      |
|sega                      |action         |80      |
|laush studio              |casual         |75      |
|square enix               |action         |75      |
|artifex mundi             |adventure      |72      |
|ubisoft                   |action         |70      |
|devolver digital          |action         |69      |
|blender games             |casual         |68      |
|hh-games                  |casual         |65      |
|hosted games              |adventure      |63      |
|bandai namco entertainment|action         |62      |
|ziggurat                  |action         |58      |
|thq nordic                |action         |57      |
|electronic arts           |action         |57      |
|reforged group            |indie          |54      |
|hede                      |action         |54      |
+--------------------------+---------------+--------+
only showing top 20 rows

In [0]:
from pyspark.sql.functions import count

pivot_publishers_strategy = clean_df \
    .dropDuplicates(['appid', 'extracted_genre']) \
    .filter(clean_df.publisher.isin('big fish games', '8floor', 'choice of games', 'hh-games', 'laush studio', 'valve', 'ubisoft')) \
    .groupBy('extracted_genre') \
    .pivot('publisher') \
    .agg(count('appid').alias('games_nb')) \
    .na.fill(0)
pivot_publishers_strategy.display()

extracted_genre,8floor,big fish games,choice of games,hh-games,laush studio,ubisoft,valve
casual,230,29,0,65,75,9,1
adventure,14,392,99,30,9,7,1
rpg,0,0,3,0,0,9,0
simulation,0,0,0,0,0,9,1
action,0,1,13,38,20,70,27
indie,0,0,24,0,17,1,1
racing,0,0,0,0,0,10,0
strategy,0,0,0,0,0,8,2
massively multiplayer,0,0,0,0,0,1,0
free to play,0,0,0,0,0,3,1
animation & modeling,0,0,0,0,0,0,1
none,0,1,1,0,0,0,0

In [0]:
pivot_pd = pivot_publishers_strategy.toPandas().set_index('extracted_genre')
pivot_pct = pivot_pd.div(pivot_pd.sum(axis=0), axis=1) * 100
pivot_pct = pivot_pct.round(2)
(display(pivot_pct.reset_index())) # avoid loose label genres

extracted_genre,8floor,big fish games,choice of games,hh-games,laush studio,ubisoft,valve
casual,94.26,6.86,0.0,48.87,61.98,7.09,2.86
adventure,5.74,92.67,70.71,22.56,7.44,5.51,2.86
rpg,0.0,0.0,2.14,0.0,0.0,7.09,0.0
simulation,0.0,0.0,0.0,0.0,0.0,7.09,2.86
action,0.0,0.24,9.29,28.57,16.53,55.12,77.14
indie,0.0,0.0,17.14,0.0,14.05,0.79,2.86
racing,0.0,0.0,0.0,0.0,0.0,7.87,0.0
strategy,0.0,0.0,0.0,0.0,0.0,6.3,5.71
massively multiplayer,0.0,0.0,0.0,0.0,0.0,0.79,0.0
free to play,0.0,0.0,0.0,0.0,0.0,2.36,2.86
animation & modeling,0.0,0.0,0.0,0.0,0.0,0.0,2.86
none,0.0,0.24,0.71,0.0,0.0,0.0,0.0

Factually, offer is oriented. Leaders companies label more than 50% of their products on one or two genres, mostly beetween casual, adventure, indie, strategy. Some companies sont plus diversifiées et misent sur une niche strategy sur du rpg et de l'action.   
- 1 big fish games target casual and adventure (50% / 47%)
- 2 8floor target casual at 75%
- 3 choice of games est spécialisé en rpg. Il est également présent sur le indie et adventure (32% / 32% / 26%)
- 4 hh-games cible casual, indie, action et adventure (39% to 11%)
- 5 laush studio target indie and casual (45% / 32%)
- outsider valve target action at 60%
- Ubisoft action at (32% / 30% )

#### What are the most lucrative genres?

# Platform analysis

Are most games available on Windows/Mac/Linux instead?

In [0]:
from pyspark.sql.functions import count

top_platform = clean_df \
    .select('appid', 'extracted_platform') \
    .dropDuplicates(['appid']) \
    .groupBy('extracted_platform') \
    .agg(count("extracted_platform").alias("games_nb")) \
    .orderBy('games_nb', ascending=False)
top_platform.show(truncate=False)

+------------------+--------+
|extracted_platform|games_nb|
+------------------+--------+
|windows           |41164   |
|linux             |8435    |
|mac               |5957    |
+------------------+--------+

Nous avons déjà les résultats :
windows is leader (74%), linux and mac are ones () 
- 1 windows with 41164 supported games
- 2 linux (8435)
- 3 mac (5957)
Les jeux sont accessibles en ligne indépendamment de l'os.

In [0]:
platform_pd = top_platform.toPandas().set_index('extracted_platform')
pct_platform = platform_pd.div(platform_pd.sum(axis=0), axis=1) * 100
pct_platform = pct_platform.round(2)
(display(pct_platform.reset_index())) # avoid loose label

extracted_platform,games_nb
windows,74.09
linux,15.18
mac,10.72

Are certain games developped on specifically on a platform ?

What chances of games to be bought if limited by one platform

Do certain genres tend to be preferentially available on certain platforms?

In [0]:
clean_df.printSchema()